/* Plan Bâtiment Pro v17 — windowed editor. One model, one plan renderer, lazy technical windows. */
(function(root){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const G=root.PBPGeometry,S=root.PBPStructure,F=root.PBPFoundations,B=root.PBPBuilding,R=root.PBPRoof,Z=root.PBPSpaces,P=root.PBPPrecision,C=root.PBPV17Calc;
const PX=50,EPS=.004,uid=()=>Math.random().toString(36).slice(2,10),clone=v=>JSON.parse(JSON.stringify(v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),sub=(a,b)=>({x:a.x-b.x,y:a.y-b.y}),dot=(a,b)=>a.x*b.x+a.y*b.y;
const fmt=(v,n=2)=>Number.isFinite(Number(v))?Number(v).toFixed(n).replace('.',','):'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const WALLS=new Set(['wallExterior','wallBearing','partition','foundation','beam']),EDITABLE=new Set(['wallExterior','wallBearing','partition','foundation','beam']);
const typeName={wallExterior:'Mur extérieur',wallBearing:'Mur porteur',partition:'Cloison',foundation:'Fondation',beam:'Poutre',column:'Poteau',slab:'Dalle',door:'Porte',window:'Fenêtre',opening:'Trémie',stair:'Escalier',dimension:'Cote'};
function defaults(){return{projectName:'Mon projet',levels:[{id:'foundations',name:'Fondations',elevation:-.8,height:.8},{id:'ground',name:'RDC',elevation:0,height:2.8},{id:'r1',name:'R+1',elevation:2.8,height:2.8},{id:'roof',name:'Toiture',elevation:5.6,height:1.5}],activeLevelId:'ground',elements:[],buildingDesign:{schema:1,materials:{},floors:[]},structureDesign:{schema:1,foundation:{},floors:[]},foundationAutomation:{},roofDesign:{},spaceDesign:{schema:1,visible:true,names:{}},envelopeDesign:{assemblies:[]},drawingDisplay:{dimensions:true,automatic:true,manual:true,selectedOnly:false,grid:true,unit:'m'},magnet:{enabled:true,crossLevels:true,reference:'below'},v17:{version:'17.0.0'}};}
function normalize(raw){const d=defaults(),x=raw&&typeof raw==='object'?clone(raw):{};const out={...d,...x};out.levels=Array.isArray(x.levels)&&x.levels.length?x.levels:d.levels;out.elements=Array.isArray(x.elements)?x.elements:[];out.activeLevelId=x.activeLevelId||out.levels.find(l=>l.id==='ground')?.id||out.levels[0].id;out.buildingDesign=x.buildingDesign&&typeof x.buildingDesign==='object'?x.buildingDesign:d.buildingDesign;out.structureDesign=x.structureDesign&&typeof x.structureDesign==='object'?x.structureDesign:d.structureDesign;out.foundationAutomation=x.foundationAutomation&&typeof x.foundationAutomation==='object'?x.foundationAutomation:{};out.roofDesign=x.roofDesign&&typeof x.roofDesign==='object'?x.roofDesign:{};out.spaceDesign=x.spaceDesign&&typeof x.spaceDesign==='object'?x.spaceDesign:d.spaceDesign;out.envelopeDesign=x.envelopeDesign&&typeof x.envelopeDesign==='object'?x.envelopeDesign:d.envelopeDesign;out.drawingDisplay={...d.drawingDisplay,...(x.drawingDisplay||{})};out.magnet={...d.magnet,...(x.magnet||{})};out.v17={version:'17.0.0'};return out;}
class Bus{constructor(){this.m=new Map()}on(k,f){if(!this.m.has(k))this.m.set(k,new Set());this.m.get(k).add(f)}emit(k,p){for(const f of this.m.get(k)||[])try{f(p)}catch(e){console.error(e)}}}
class Model{
 constructor(raw,bus){this.data=normalize(raw);this.bus=bus;this.history=[];this.future=[];this.revision=1}
 snapshot(){return JSON.stringify(this.data)}
 mutate(fn,label,meta={}){const before=this.snapshot();fn(this.data);const after=this.snapshot();if(before===after)return false;this.history.push(before);if(this.history.length>80)this.history.shift();this.future=[];this.revision++;this.bus.emit('changed',{label,revision:this.revision,...meta});return true}
 commitFrom(before,label,meta={}){const after=this.snapshot();if(before===after)return false;this.history.push(before);if(this.history.length>80)this.history.shift();this.future=[];this.revision++;this.bus.emit('changed',{label,revision:this.revision,...meta});return true}
 restore(text,clear=true){this.data=normalize(JSON.parse(text));if(clear){this.history=[];this.future=[]}this.revision++;this.bus.emit('changed',{label:'restore',revision:this.revision,all:true})}
 undo(){if(!this.history.length)return false;this.future.push(this.snapshot());this.data=normalize(JSON.parse(this.history.pop()));this.revision++;this.bus.emit('changed',{label:'undo',revision:this.revision,all:true});return true}
 redo(){if(!this.future.length)return false;this.history.push(this.snapshot());this.data=normalize(JSON.parse(this.future.pop()));this.revision++;this.bus.emit('changed',{label:'redo',revision:this.revision,all:true});return true}
 get levels(){return this.data.levels}get elements(){return this.data.elements}get activeLevelId(){return this.data.activeLevelId}set activeLevelId(v){this.data.activeLevelId=v}
 level(id){return this.levels.find(l=>l.id===id)}
 stories(){return this.levels.filter(l=>!l.autoFloor&&l.id!=='foundations'&&l.id!=='roof'&&!/^toiture$/i.test(l.name||'')).sort((a,b)=>a.elevation-b.elevation)}
}
class Cache{
 constructor(app){this.app=app;this.floor=new Map();this.foundation=null;this.roof=null;this.rooms=new Map();this.view3dRev=0;this.quantity=null}
 invalidate(){this.app.renderWindowBar();this.app.setPerf('Plan modifié · fenêtres techniques à recalculer')}
 state(name,key){
  if(name==='plan'||name==='isolation')return'current';
  let x=null;if(name==='floor')x=this.floor.get(key);else if(name==='foundations')x=this.foundation;else if(name==='roof')x=this.roof;else if(name==='rooms')x=this.rooms.get(key);else if(name==='3d')return this.view3dRev===this.app.model.revision?'current':'stale';else if(name==='quantities')x=this.quantity;
  if(!x)return'stale';if(x.error)return'error';return x.revision===this.app.model.revision?'current':'stale';
 }
 put(name,key,result,ms,error=null){const x={revision:this.app.model.revision,result,ms,error};if(name==='floor')this.floor.set(key,x);else if(name==='foundations')this.foundation=x;else if(name==='roof')this.roof=x;else if(name==='rooms')this.rooms.set(key,x);else if(name==='quantities')this.quantity=x;return x}
}
function pointSeg(p,a,b){const v=sub(b,a),L=dot(v,v);if(!L)return{d:dist(p,a),t:0,q:{...a}};const t=Math.max(0,Math.min(1,dot(sub(p,a),v)/L)),q={x:a.x+v.x*t,y:a.y+v.y*t};return{d:dist(p,q),t,q}}
class PlanRenderer{
 constructor(app,canvas){this.app=app;this.canvas=canvas;this.ctx=canvas.getContext('2d');this.scale=1;this.pan={x:0,y:0};this.w=1;this.h=1;new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);this.resize()}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect(),dpr=root.devicePixelRatio||1;this.canvas.width=Math.max(1,Math.floor(r.width*dpr));this.canvas.height=Math.max(1,Math.floor(r.height*dpr));this.canvas.style.width=r.width+'px';this.canvas.style.height=r.height+'px';this.ctx.setTransform(dpr,0,0,dpr,0,0);this.w=r.width;this.h=r.height;this.app.requestPlan()}
 world(p){return{x:this.w/2+p.x*PX*this.scale+this.pan.x,y:this.h/2+p.y*PX*this.scale+this.pan.y}}
 screen(p){return{x:(p.x-this.w/2-this.pan.x)/(PX*this.scale),y:(p.y-this.h/2-this.pan.y)/(PX*this.scale)}}
 grid(){if(this.app.display.grid===false)return;const c=this.ctx,minor=PX*this.scale*.5,major=PX*this.scale;if(minor<8)return;c.save();c.lineWidth=1;const ox=(this.w/2+this.pan.x)%minor,oy=(this.h/2+this.pan.y)%minor;for(let x=ox;x<this.w;x+=minor){const m=Math.abs(((x-(this.w/2+this.pan.x))/major)-Math.round((x-(this.w/2+this.pan.x))/major))<.05;c.strokeStyle=m?'#d2d9df':'#e9edf0';c.beginPath();c.moveTo(x,0);c.lineTo(x,this.h);c.stroke()}for(let y=oy;y<this.h;y+=minor){const m=Math.abs(((y-(this.h/2+this.pan.y))/major)-Math.round((y-(this.h/2+this.pan.y))/major))<.05;c.strokeStyle=m?'#d2d9df':'#e9edf0';c.beginPath();c.moveTo(0,y);c.lineTo(this.w,y);c.stroke()}c.restore()}
 fill(e,overlay){if(overlay)return'#8ea3b0';if(e.type==='wallBearing')return'#273a49';if(e.type==='partition')return'#7b8790';if(e.type==='foundation')return'#69747c';if(e.type==='beam')return'#50616d';return'#344c5d'}
 wallBatch(rows,alpha=1,overlay=false){const parts=P?.footprints?P.footprints(rows,this.app.model.levels):[];const c=this.ctx;if(parts.length){const key=p=>Math.round(p.x*1e6)+','+Math.round(p.y*1e6),edges=new Map();c.save();c.globalAlpha=alpha;for(const w of parts){const ps=w.ps.map(p=>this.world(p));c.beginPath();ps.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fillStyle=this.fill(w.e,overlay);c.fill();for(let i=0;i<w.ps.length;i++){const a=w.ps[i],b=w.ps[(i+1)%w.ps.length],ka=key(a),kb=key(b),k=ka<kb?ka+'|'+kb:kb+'|'+ka;if(!edges.has(k))edges.set(k,[]);edges.get(k).push({a,b})}}c.strokeStyle=overlay?'#667f8f':'#142b3a';c.lineWidth=1.5;c.lineJoin='miter';for(const es of edges.values()){if(es.length>1)continue;const a=this.world(es[0].a),b=this.world(es[0].b);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}c.restore();return}
  c.save();c.globalAlpha=alpha;c.lineCap='butt';c.lineJoin='miter';for(const e of rows){const a=this.world(e.a),b=this.world(e.b);c.strokeStyle=overlay?'#667f8f':'#142b3a';c.lineWidth=Math.max(3,(e.thickness||.2)*PX*this.scale+2);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.strokeStyle=this.fill(e,overlay);c.lineWidth=Math.max(2,(e.thickness||.2)*PX*this.scale);c.stroke()}c.restore()}
 rect(e,alpha=1,overlay=false){const p=this.world(e),w=(e.width||.3)*PX*this.scale,h=(e.depth||.3)*PX*this.scale,c=this.ctx;c.save();c.globalAlpha=alpha;c.fillStyle=overlay?'#8da1af':e.type==='column'?'#415969':e.type==='opening'?'rgba(255,255,255,.45)':'#8797a1';c.strokeStyle='#1f3442';c.fillRect(p.x-w/2,p.y-h/2,w,h);c.strokeRect(p.x-w/2,p.y-h/2,w,h);c.restore()}
 opening(e,alpha=1,overlay=false){const p=this.world(e),w=(e.width||.9)*PX*this.scale,c=this.ctx;c.save();c.globalAlpha=alpha;c.strokeStyle=overlay?'#8da1af':e.type==='window'?'#2f6d86':'#725f4b';c.lineWidth=3;c.beginPath();c.moveTo(p.x-w/2,p.y);c.lineTo(p.x+w/2,p.y);c.stroke();if(e.type==='door'){c.lineWidth=1;c.beginPath();c.arc(p.x-w/2,p.y,w,0,-Math.PI/2,true);c.stroke()}c.restore()}
 dimension(e,alpha=1){if(this.app.display.dimensions===false||this.app.display.manual===false)return;const a=this.world(e.a),b=this.world(e.b),L=dist(e.a,e.b),c=this.ctx;c.save();c.globalAlpha=alpha;c.strokeStyle='#876320';c.fillStyle='#876320';c.lineWidth=1;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.font='12px system-ui';c.textAlign='center';c.fillText(this.app.lengthLabel(L),(a.x+b.x)/2,(a.y+b.y)/2-7);c.restore()}
 layer(rows,alpha,overlay){const walls=rows.filter(e=>e.a&&e.b&&WALLS.has(e.type)),other=rows.filter(e=>!walls.includes(e));this.wallBatch(walls,alpha,overlay);for(const e of other){if(['door','window'].includes(e.type))this.opening(e,alpha,overlay);else if(e.type==='dimension'&&e.a&&e.b)this.dimension(e,alpha);else if(Number.isFinite(e.x)&&Number.isFinite(e.y))this.rect(e,alpha,overlay)}}
 overlayIds(){const a=this.app,ls=a.model.stories(),i=ls.findIndex(l=>l.id===a.model.activeLevelId),ids=[];if(a.overlay.below&&i>0)ids.push(ls[i-1].id);if(a.overlay.above&&i>=0&&i<ls.length-1)ids.push(ls[i+1].id);if(a.overlay.foundations&&a.model.activeLevelId!=='foundations')ids.push('foundations');return[...new Set(ids)]}
 autoDims(){const a=this.app;if(a.display.dimensions===false||a.display.automatic===false||a.drag)return;const rows=a.model.elements.filter(e=>e.levelId===a.model.activeLevelId&&e.a&&e.b&&WALLS.has(e.type)&&(!a.display.selectedOnly||e.id===a.selected?.id)),c=this.ctx;c.save();c.font='11px system-ui';c.textAlign='center';for(const e of rows){const A=this.world(e.a),B=this.world(e.b);if(Math.hypot(B.x-A.x)<30)continue;const text=a.lengthLabel(dist(e.a,e.b)),x=(A.x+B.x)/2,y=(A.y+B.y)/2-16,w=c.measureText(text).width+10;c.fillStyle='rgba(255,255,255,.95)';c.fillRect(x-w/2,y-9,w,18);c.fillStyle='#315b70';c.fillText(text,x,y+4)}c.restore()}
 selection(){const e=this.app.selected;if(!e||e.levelId!==this.app.model.activeLevelId)return;const c=this.ctx;c.save();c.strokeStyle='#1976a7';c.fillStyle='#fff';c.lineWidth=1.5;if(e.a&&e.b){const a=this.world(e.a),b=this.world(e.b);c.setLineDash([5,4]);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.setLineDash([]);for(const end of ['a','b']){const p=end==='a'?a:b,active=this.app.selectedPart===end;c.fillStyle=active?'#1976a7':'#fff';c.beginPath();c.arc(p.x,p.y,active?6.5:5.5,0,Math.PI*2);c.fill();c.stroke()}if(Math.hypot(b.x-a.x,b.y-a.y)>44){const x=(a.x+b.x)/2,y=(a.y+b.y)/2;c.fillStyle=this.app.selectedPart?'#fff':'#1976a7';c.beginPath();c.moveTo(x,y-4);c.lineTo(x+4,y);c.lineTo(x,y+4);c.lineTo(x-4,y);c.closePath();c.fill();c.stroke()}}else if(Number.isFinite(e.x)){const p=this.world(e);c.setLineDash([5,4]);c.beginPath();c.arc(p.x,p.y,8,0,Math.PI*2);c.stroke()}c.restore()}
 guides(){const s=this.app.snapResult,start=this.app.angleStart(),target=this.app.angleTarget();if(!s&&!start)return;const c=this.ctx;c.save();if(s){c.strokeStyle='#bf8021';c.fillStyle='#875519';c.lineWidth=1;c.setLineDash([5,4]);for(const g of s.guides||[]){const a=this.world(g.a),b=this.world(g.b);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}c.setLineDash([])}if(start&&target){const ang=((Math.atan2(target.y-start.y,target.x-start.x)*180/Math.PI)%360+360)%360,p=this.world(target),text=(s?.label?s.label+' · ':'')+ang.toFixed(1)+'°';c.font='11px system-ui';const w=c.measureText(text).width+12,x=Math.min(Math.max(6,p.x+12),this.w-w-6),y=Math.min(Math.max(22,p.y-14),this.h-8);c.fillStyle='#fff9ea';c.fillRect(x-3,y-13,w,19);c.fillStyle='#875519';c.fillText(text,x+2,y)}c.restore()}
 draw(){const c=this.ctx;c.clearRect(0,0,this.w,this.h);c.fillStyle='#fbfcfd';c.fillRect(0,0,this.w,this.h);this.grid();const a=this.app,alpha=a.overlay.opacity/100;for(const id of this.overlayIds())this.layer(a.model.elements.filter(e=>e.mode==='construction'&&!e.generator&&e.levelId===id),alpha,true);this.layer(a.model.elements.filter(e=>e.mode==='construction'&&!e.generator&&e.levelId===a.model.activeLevelId),1,false);if(a.drawingStart&&a.pointerWorld&&['wallExterior','wallBearing','partition','foundation','beam','dimension'].includes(a.activeTool)){const A=this.world(a.drawingStart),B=this.world(a.pointerWorld);c.save();c.strokeStyle='#2e7fa7';c.lineWidth=2;c.setLineDash([7,5]);c.beginPath();c.moveTo(A.x,A.y);c.lineTo(B.x,B.y);c.stroke();c.restore()}this.autoDims();this.selection();this.guides()}
 hit(screen){const w=this.screen(screen),rows=this.app.model.elements.filter(e=>e.mode==='construction'&&!e.generator&&e.levelId===this.app.model.activeLevelId);for(let i=rows.length-1;i>=0;i--){const e=rows[i];if(e.a&&e.b){const q=pointSeg(w,e.a,e.b),th=Math.max(.12,(e.thickness||.2)/2+.05);if(q.d<th)return e}else if(Number.isFinite(e.x)&&Math.hypot(w.x-e.x,w.y-e.y)<Math.max(e.width||.5,e.depth||.5)/2+.15)return e}return null}
 corner(screen,type='mouse'){const rad=type==='touch'?17:11,rows=this.app.model.elements.filter(e=>e.mode==='construction'&&!e.generator&&e.levelId===this.app.model.activeLevelId&&e.a&&e.b&&WALLS.has(e.type));let best=null,d=Infinity;for(const e of rows)for(const end of ['a','b']){const p=this.world(e[end]),x=Math.hypot(screen.x-p.x,screen.y-p.y);if(x<rad&&x<d){best={element:e,end};d=x}}return best}
}
class TechRenderer{
 constructor(app,canvas){this.app=app;this.canvas=canvas;this.ctx=canvas.getContext('2d');this.scale=1;this.pan={x:0,y:0};this.w=1;this.h=1;new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);this.resize()}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect(),dpr=root.devicePixelRatio||1;this.canvas.width=Math.max(1,Math.floor(r.width*dpr));this.canvas.height=Math.max(1,Math.floor(r.height*dpr));this.canvas.style.width=r.width+'px';this.canvas.style.height=r.height+'px';this.ctx.setTransform(dpr,0,0,dpr,0,0);this.w=r.width;this.h=r.height}
 world(p){return{x:this.w/2+p.x*PX*this.scale+this.pan.x,y:this.h/2+p.y*PX*this.scale+this.pan.y}}
 draw(baseLevel,elements){const c=this.ctx;c.clearRect(0,0,this.w,this.h);c.fillStyle='#fbfcfd';c.fillRect(0,0,this.w,this.h);const walls=this.app.model.elements.filter(e=>e.levelId===baseLevel&&e.mode==='construction'&&!e.generator&&e.a&&e.b&&WALLS.has(e.type));c.save();c.globalAlpha=.35;for(const e of walls){const a=this.world(e.a),b=this.world(e.b);c.strokeStyle='#506878';c.lineWidth=Math.max(2,(e.thickness||.2)*PX*this.scale);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}c.restore();for(const e of elements||[]){if(e.polygon){const ps=e.polygon.map(p=>this.world(p));c.save();c.globalAlpha=e.void?.18:.22;c.beginPath();ps.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();if(!e.void){c.fillStyle=e.role==='panel'?'#cfb88c':'#bdc7cc';c.fill()}c.strokeStyle='#81939d';if(e.void)c.setLineDash([6,4]);c.stroke();c.restore()}else if(e.a&&e.b){const a=this.world(e.a),b=this.world(e.b);c.save();c.strokeStyle=e.role==='loadTransferRequired'?'#b05b2d':e.foundationRole?'#6f7b82':'#9b7448';c.lineWidth=Math.max(1,(e.thickness||e.width||.05)*PX*this.scale);if(e.role==='loadTransferRequired')c.setLineDash([6,4]);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.restore()}else if(Number.isFinite(e.x)&&Number.isFinite(e.y)){const p=this.world(e),w=(e.width||.5)*PX*this.scale,d=(e.depth||.5)*PX*this.scale;c.save();c.globalAlpha=.7;c.fillStyle='#89979f';c.fillRect(p.x-w/2,p.y-d/2,w,d);c.restore()}}}
}
class View3D{
 constructor(app,canvas){this.app=app;this.canvas=canvas;this.ctx=canvas.getContext('2d');this.angle=-.7;this.tilt=.55;this.zoom=38;this.w=1;this.h=1;this.drag=null;new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);this.bind();this.resize()}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect(),dpr=root.devicePixelRatio||1;this.canvas.width=Math.max(1,Math.floor(r.width*dpr));this.canvas.height=Math.max(1,Math.floor(r.height*dpr));this.canvas.style.width=r.width+'px';this.canvas.style.height=r.height+'px';this.ctx.setTransform(dpr,0,0,dpr,0,0);this.w=r.width;this.h=r.height}
 project(x,y,z){const ca=Math.cos(this.angle),sa=Math.sin(this.angle),rx=x*ca-y*sa,ry=x*sa+y*ca;return{x:this.w/2+rx*this.zoom,y:this.h*.62+(ry*Math.sin(this.tilt)-z*Math.cos(this.tilt))*this.zoom}}
 wall(e,l){const z=Number(e.zBase??l?.elevation??0),h=Number(e.height)||Number(l?.height)||2.8,a=this.project(e.a.x,e.a.y,z),b=this.project(e.b.x,e.b.y,z),c=this.project(e.b.x,e.b.y,z+h),d=this.project(e.a.x,e.a.y,z+h),x=this.ctx;x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.lineTo(c.x,c.y);x.lineTo(d.x,d.y);x.closePath();x.fillStyle=e.type==='wallBearing'?'#687985':e.type==='partition'?'#b4bdc2':'#8b9ca6';x.fill();x.strokeStyle='#536773';x.stroke()}
 beam(e,z=0){const a=this.project(e.a.x,e.a.y,Number(e.a.z??e.zBase??z)),b=this.project(e.b.x,e.b.y,Number(e.b.z??e.zBase??z)),c=this.ctx;c.strokeStyle=e.role==='loadTransferRequired'?'#b05b2d':'#a37b4d';c.lineWidth=Math.max(2,(e.thickness||e.width||.06)*this.zoom);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}
 draw(derived=[]){const c=this.ctx;c.clearRect(0,0,this.w,this.h);c.fillStyle='#edf2f5';c.fillRect(0,0,this.w,this.h);const levels=new Map(this.app.model.levels.map(l=>[l.id,l]));for(const e of this.app.model.elements)if(e.mode==='construction'&&!e.generator&&e.a&&e.b&&['wallExterior','wallBearing','partition','beam'].includes(e.type))this.wall(e,levels.get(e.levelId));for(const e of derived)if(e.a&&e.b)this.beam(e,levels.get(e.levelId)?.elevation||0)}
 bind(){this.canvas.addEventListener('pointerdown',e=>{this.drag={id:e.pointerId,x:e.clientX,y:e.clientY};this.canvas.setPointerCapture?.(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(!this.drag||e.pointerId!==this.drag.id)return;this.angle+=(e.clientX-this.drag.x)*.008;this.tilt=Math.max(.18,Math.min(1.12,this.tilt+(e.clientY-this.drag.y)*.004));this.drag.x=e.clientX;this.drag.y=e.clientY;this.app.render3D()});this.canvas.addEventListener('pointerup',e=>{if(this.drag?.id===e.pointerId)this.drag=null});this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(14,Math.min(95,this.zoom*(e.deltaY<0?1.08:.92)));this.app.render3D()},{passive:false})}
}
class App{
 constructor(){
  this.bus=new Bus();let raw=null,migrated=false;try{const n=localStorage.getItem('planBatimentProV17'),old=localStorage.getItem('planBatimentPro');if(n)raw=JSON.parse(n);else if(old){raw=JSON.parse(old);migrated=true}}catch(e){console.warn(e)}
  this.model=new Model(raw,this.bus);this.cache=new Cache(this);this.activeWindow='plan';this.activeTool='select';this.selected=null;this.selectedPart=null;this.drawingStart=null;this.pointerWorld=null;this.snapResult=null;this.drag=null;this.panDrag=null;this.alt=false;this.overlay={below:true,above:false,foundations:true,opacity:35};this.display={...defaults().drawingDisplay,...this.model.data.drawingDisplay};this.magnet={...defaults().magnet,...this.model.data.magnet};this.frame=0;
  this.toolSettings={wallExterior:{thickness:.32,height:2.8},wallBearing:{thickness:.20,height:2.8},partition:{thickness:.072,height:2.8},foundation:{thickness:.5,height:.5},beam:{thickness:.2,height:.3},column:{width:.25,depth:.25,height:2.8},slab:{width:3,depth:3,height:.2},door:{width:.9,depth:.12,height:2.04},window:{width:1.2,depth:.12,height:1.25},opening:{width:1,depth:2,height:.2,openingFraming:'auto'},stair:{width:1,depth:3,height:2.8},dimension:{}};
  this.plan=new PlanRenderer(this,$('#planCanvas'));this.floorView=new TechRenderer(this,$('#floorCanvas'));this.foundationView=new TechRenderer(this,$('#foundationCanvas'));this.roofView=new TechRenderer(this,$('#roofCanvas'));this.view3d=new View3D(this,$('#canvas3d'));
  this.bind();this.bus.on('changed',e=>{this.cache.invalidate();this.selected=null;this.selectedPart=null;this.fillAllSelectors();this.renderWindowBar();this.requestPlan();if(this.activeWindow==='rooms')this.renderRooms(false);if(this.activeWindow==='isolation')this.renderIsolation()});this.fillAllSelectors();this.syncToolbar();this.renderWindowBar();this.openWindow('plan');if(migrated)this.setPerf('Copie du projet v0.16 chargée dans v17 · l’original reste intact')}
 lengthLabel(L){const u=this.display.unit||'m';return u==='mm'?(L*1000).toFixed(0)+' mm':u==='cm'?(L*100).toFixed(1)+' cm':L.toFixed(2)+' m'}
 setPerf(t){$('#statusPerf').textContent=t}
 requestPlan(){if(this.activeWindow!=='plan'||this.frame)return;this.frame=requestAnimationFrame(()=>{this.frame=0;this.plan.draw()})}
 angleStart(){return this.drag?.kind==='corner'?(this.drag.end==='a'?this.drag.originalB:this.drag.originalA):this.drawingStart}
 angleTarget(){if(this.drag?.kind==='corner'){const e=this.model.elements.find(x=>x.id===this.drag.id);return e?.[this.drag.end]||null}return this.pointerWorld}
 referenceLevels(){if(!this.magnet.crossLevels)return[];const ref=this.magnet.reference||'below',stories=this.model.stories(),i=stories.findIndex(l=>l.id===this.model.activeLevelId);if(ref==='below')return i>0?[stories[i-1].id]:[];return this.model.level(ref)&&ref!==this.model.activeLevelId?[ref]:[]}
 snap(p,context={}){
  if(!P||!this.magnet.enabled||this.alt){this.snapResult=null;return p}const d=context.drag||this.drag,exclude=[];let start=context.start||this.drawingStart||null;if(d?.kind==='corner'){start=d.end==='a'?d.originalB:d.originalA;exclude.push(d.id+':'+d.end);for(const x of d.connected||[])exclude.push(x.id+':'+x.end)}
  const refs=P.references(this.model.elements.filter(e=>!e.generator),this.model.activeLevelId,this.referenceLevels(),exclude),perpendicular=[];if(start)for(const e of this.model.elements)if(e.levelId===this.model.activeLevelId&&e.a&&e.b&&e.id!==d?.id&&(dist(e.a,start)<EPS||dist(e.b,start)<EPS))perpendicular.push(P.sub(e.b,e.a));
  const out=P.snap(p,refs,{start,tolerance:9/(PX*this.plan.scale),enabled:true,perpendicular});let point={...out.point},label=out.label||'',guides=out.guides||[],references=out.references||[];
  if(start&&!label){const dx=point.x-start.x,dy=point.y-start.y,L=Math.hypot(dx,dy);if(L>.03){const a=Math.atan2(dy,dx),step=Math.PI/4,q=Math.round(a/step)*step,delta=Math.abs(Math.atan2(Math.sin(a-q),Math.cos(a-q)));if(delta<.09){point={x:start.x+Math.cos(q)*L,y:start.y+Math.sin(q)*L};label=(((q*180/Math.PI)%360+360)%360).toFixed(0)+'°';guides=[{a:start,b:point}]}}}
  this.snapResult=label?{point,guides,label,references}:null;return point
 }
 ensureJunction(point,excludeId){for(const e of this.model.elements){if(e.id===excludeId||e.levelId!==this.model.activeLevelId||!EDITABLE.has(e.type)||!e.a||!e.b)continue;const q=pointSeg(point,e.a,e.b);if(q.d<.006&&q.t>.015&&q.t<.985){const oldB={...e.b};e.b={...q.q};this.model.elements.push({...clone(e),id:uid(),a:{...q.q},b:oldB});return{point:{...q.q},split:e.id}}}return null}
 screenEvent(e){const r=$('#planCanvas').getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
 beginDrag(e){if(this.activeTool!=='select'||e.button!==0||e.isPrimary===false)return;const s=this.screenEvent(e),corner=this.plan.corner(s,e.pointerType),hit=corner?.element||this.plan.hit(s);if(!hit)return;this.selected=hit;this.selectedPart=corner?.end||null;this.renderProperties();if(!hit.a||!hit.b||!EDITABLE.has(hit.type))return;const anchors=corner?[corner.end]:['a','b'],connected=[];for(const other of this.model.elements){if(other.id===hit.id||other.levelId!==hit.levelId||!other.a||!other.b||!EDITABLE.has(other.type))continue;for(const end of ['a','b'])for(const anchor of anchors)if(dist(other[end],hit[anchor])<EPS){connected.push({id:other.id,end,anchor,origin:{...other[end]}});break}}this.drag={id:hit.id,pointerId:e.pointerId,kind:corner?'corner':'wall',end:corner?.end||null,start:this.plan.screen(s),screenStart:s,originalA:{...hit.a},originalB:{...hit.b},connected,before:this.model.snapshot(),moved:false};e.currentTarget.setPointerCapture?.(e.pointerId)}
 moveDrag(e){const d=this.drag;if(!d||e.pointerId!==d.pointerId)return false;const sp=this.screenEvent(e);if(!d.moved&&Math.hypot(sp.x-d.screenStart.x,sp.y-d.screenStart.y)<3)return true;const now=this.plan.screen(sp),dx=now.x-d.start.x,dy=now.y-d.start.y,wall=this.model.elements.find(x=>x.id===d.id);if(!wall)return true;let a={...d.originalA},b={...d.originalB};if(d.kind==='corner'){const raw=d.end==='a'?{x:d.originalA.x+dx,y:d.originalA.y+dy}:{x:d.originalB.x+dx,y:d.originalB.y+dy},target=this.snap(raw,{drag:d});if(d.end==='a')a=target;else b=target}else{a={x:d.originalA.x+dx,y:d.originalA.y+dy};b={x:d.originalB.x+dx,y:d.originalB.y+dy};let best=null;for(const [end,p] of [['a',a],['b',b]]){const s=this.snap(p,{drag:d});if(this.snapResult){const dd=dist(p,s);if(!best||dd<best.dd)best={p,s,dd}}}if(best){const ox=best.s.x-best.p.x,oy=best.s.y-best.p.y;a={x:a.x+ox,y:a.y+oy};b={x:b.x+ox,y:b.y+oy}}}if(dist(a,b)<.05)return true;wall.a=a;wall.b=b;for(const x of d.connected){const o=this.model.elements.find(y=>y.id===x.id);if(o)o[x.end]={...(x.anchor==='a'?a:b)}}d.moved=true;this.pointerWorld=now;this.setMeasure(wall);this.requestPlan();return true}
 endDrag(e){const d=this.drag;if(!d||e.pointerId!==d.pointerId)return;this.moveDrag(e);const wall=this.model.elements.find(x=>x.id===d.id);if(d.moved&&d.kind==='corner'&&wall){const p=wall[d.end],j=this.ensureJunction(p,wall.id);if(j)wall[d.end]={...j.point}}this.drag=null;this.snapResult=null;if(d.moved)this.model.commitFrom(d.before,'déplacement mur',{levelId:wall?.levelId});this.renderProperties();this.requestPlan()}
 cancelDrag(){const d=this.drag;if(!d)return;const w=this.model.elements.find(x=>x.id===d.id);if(w){w.a={...d.originalA};w.b={...d.originalB}}for(const x of d.connected){const o=this.model.elements.find(y=>y.id===x.id);if(o)o[x.end]={...x.origin}}this.drag=null;this.snapResult=null;this.requestPlan()}
 addLine(type,p){if(!this.drawingStart){this.drawingStart=p;this.pointerWorld=p;this.requestPlan();return}if(dist(this.drawingStart,p)<.05)return;const before=this.model.snapshot(),s=this.toolSettings[type]||{},a={...this.drawingStart};let b={...p};const j=this.ensureJunction(b,null);if(j)b=j.point;const el={id:uid(),mode:'construction',levelId:this.model.activeLevelId,type,a,b};if(type!=='dimension'){el.thickness=s.thickness??.2;el.height=s.height??2.8}this.model.elements.push(el);this.model.commitFrom(before,'ajout '+type,{levelId:el.levelId});this.selected=el;if(type==='dimension')this.drawingStart=null;else this.drawingStart={...b};this.pointerWorld=b;this.renderProperties();this.requestPlan()}
 addPoint(type,p){const s=this.toolSettings[type]||{},el={id:uid(),mode:'construction',levelId:this.model.activeLevelId,type,x:p.x,y:p.y,width:s.width||.8,depth:s.depth||.3,height:s.height||2.8,rotation:0};if(type==='opening')el.openingFraming=s.openingFraming||'auto';this.model.mutate(d=>d.elements.push(el),'ajout '+type,{levelId:el.levelId});this.selected=el;this.renderProperties();this.setTool('select')}
 clickPlan(e){if(this.drag)return;const sp=this.screenEvent(e),p=this.snap(this.plan.screen(sp),{start:this.drawingStart});if(this.activeTool==='select'){this.selected=this.plan.hit(sp);this.selectedPart=null;this.renderProperties();this.requestPlan();return}if(['wallExterior','wallBearing','partition','foundation','beam','dimension'].includes(this.activeTool))this.addLine(this.activeTool,p);else if(['column','slab','door','window','opening','stair'].includes(this.activeTool))this.addPoint(this.activeTool,p)}
 setTool(t){this.activeTool=t;this.drawingStart=null;this.pointerWorld=null;this.snapResult=null;$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));const s=this.toolSettings[t];$('.placement').style.display=s&&t!=='select'?'block':'none';$('#placementName').textContent=typeName[t]||t;if(s){$('#placementThickness').value=s.thickness??s.width??.1;$('#placementHeight').value=s.height??.2}this.requestPlan()}
 setMeasure(e){if(!e?.a||!e?.b)return;const L=dist(e.a,e.b),a=((Math.atan2(e.b.y-e.a.y,e.b.x-e.a.x)*180/Math.PI)%360+360)%360;$('#statusMeasure').textContent='Longueur: '+fmt(L)+' m · Angle: '+fmt(a,1)+'°'}
 renderProperties(){const p=$('#properties'),b=$('#propertiesBody'),e=this.selected;if(!e){p.hidden=true;$('#statusSelection').textContent='Aucun élément sélectionné';return}p.hidden=false;$('#statusSelection').textContent=typeName[e.type]||e.type;let h='<b>'+(typeName[e.type]||e.type)+'</b>';if(e.a&&e.b)h+='<label class="prop-row"><span>Épaisseur</span><input data-k="thickness" type="number" step="0.01" value="'+esc(e.thickness??'')+'"></label><label class="prop-row"><span>Hauteur</span><input data-k="height" type="number" step="0.05" value="'+esc(e.height??'')+'"></label><label class="prop-row"><span>Ax</span><input data-k="a.x" type="number" step="0.01" value="'+e.a.x+'"></label><label class="prop-row"><span>Ay</span><input data-k="a.y" type="number" step="0.01" value="'+e.a.y+'"></label><label class="prop-row"><span>Bx</span><input data-k="b.x" type="number" step="0.01" value="'+e.b.x+'"></label><label class="prop-row"><span>By</span><input data-k="b.y" type="number" step="0.01" value="'+e.b.y+'"></label>';else for(const [lab,k] of [['X','x'],['Y','y'],['Largeur','width'],['Profondeur','depth'],['Hauteur','height'],['Rotation','rotation']])h+='<label class="prop-row"><span>'+lab+'</span><input data-k="'+k+'" type="number" step="0.01" value="'+esc(e[k]??'')+'"></label>';h+='<button id="deleteSelected" style="width:100%;color:#9b3f2b">Supprimer</button>';b.innerHTML=h;b.querySelectorAll('[data-k]').forEach(i=>i.onchange=()=>{const k=i.dataset.k,v=Number(i.value);if(!Number.isFinite(v))return;this.model.mutate(()=>{if(k.includes('.')){const z=k.split('.');e[z[0]][z[1]]=v}else e[k]=v},'propriété',{levelId:e.levelId});this.selected=e;this.renderProperties()});$('#deleteSelected').onclick=()=>{const id=e.id;this.model.mutate(d=>d.elements=d.elements.filter(x=>x.id!==id),'suppression',{levelId:e.levelId});this.selected=null;this.renderProperties()}}
 fillLevels(select,storiesOnly=false){const old=select.value,ls=storiesOnly?this.model.stories():this.model.levels.filter(l=>!l.autoFloor);select.replaceChildren();for(const l of ls){const o=document.createElement('option');o.value=l.id;o.textContent=l.name+' ('+fmt(l.elevation)+' m)';select.append(o)}if([...select.options].some(o=>o.value===old))select.value=old}
 fillAllSelectors(){this.fillLevels($('#levelSelect'));$('#levelSelect').value=this.model.activeLevelId;for(const id of ['floorBelow','floorAbove','faSource','roofLevel','roomsLevel'])this.fillLevels($('#'+id),true);const stories=this.model.stories();if(!$('#floorBelow').value&&stories[0])$('#floorBelow').value=stories[0].id;if(!$('#floorAbove').value&&stories[1])$('#floorAbove').value=stories[1].id;this.fillMagnetRefs();this.fillIsolationWalls();this.loadFoundationUI();this.loadRoofUI()}
 fillMagnetRefs(){const s=$('#magnetRef'),old=this.magnet.reference;s.innerHTML='<option value="below">Niveau porteur inférieur</option>';for(const l of this.model.stories())if(l.id!==this.model.activeLevelId)s.insertAdjacentHTML('beforeend','<option value="'+l.id+'">'+esc(l.name)+'</option>');s.value=[...s.options].some(o=>o.value===old)?old:'below'}
 syncToolbar(){this.display=this.model.data.drawingDisplay;this.magnet=this.model.data.magnet;$('#cotesBtn').classList.toggle('active',this.display.dimensions!==false);$('#cotesBtn').textContent='↔ Cotes '+(this.display.dimensions!==false?'✓':'—');$('#gridBtn').classList.toggle('active',this.display.grid!==false);$('#gridBtn').textContent='▦ Grille '+(this.display.grid!==false?'✓':'—');$('#magnetBtn').classList.toggle('active',this.magnet.enabled!==false);$('#magnetBtn').textContent='Aimant murs '+(this.magnet.enabled!==false?'✓':'—');$('#crossLevels').checked=this.magnet.crossLevels!==false;$('#optAutoDims').checked=this.display.automatic!==false;$('#optManualDims').checked=this.display.manual!==false;$('#optSelectedDims').checked=this.display.selectedOnly===true;$('#optUnit').value=this.display.unit||'m';this.fillMagnetRefs()}
 windowStatus(name){if(name==='floor'){const cfg=this.currentFloorConfig(false);return this.cache.state('floor',cfg?.id)}if(name==='foundations')return this.cache.state('foundations');if(name==='roof')return this.cache.state('roof');if(name==='rooms')return this.cache.state('rooms',$('#roomsLevel').value||this.model.activeLevelId);if(name==='3d')return this.cache.state('3d');if(name==='quantities')return this.cache.state('quantities');return'current'}
 renderWindowBar(){const defs=[['plan','▱','Plan'],['floor','▥','Solivage'],['foundations','▰','Fondations'],['roof','⌂','Charpente'],['rooms','⌖','Pièces'],['isolation','▧','Isolation'],['3d','◇','3D'],['quantities','Σ','Métré']];$('#windowBar').innerHTML=defs.map(d=>'<button class="window-tab '+(this.activeWindow===d[0]?'active ':'')+this.windowStatus(d[0])+'" data-win="'+d[0]+'">'+d[1]+'<span>'+d[2]+'</span>'+(d[0]==='plan'||d[0]==='isolation'?'':'<i class="dot"></i>')+'</button>').join('');$$('[data-win]').forEach(b=>b.onclick=()=>this.openWindow(b.dataset.win))}
 openWindow(name){this.activeWindow=name;$$('.work-window').forEach(w=>w.classList.toggle('active',w.dataset.window===name));$('#drawbar').style.display=name==='plan'?'flex':'none';this.renderWindowBar();this.setPerf('Fenêtre '+name+' active · autres moteurs arrêtés');if(name==='plan'){this.plan.resize();this.requestPlan()}else if(name==='floor'){this.fillFloorUI();this.renderCachedFloor()}else if(name==='foundations'){this.renderCachedFoundation()}else if(name==='roof'){this.renderCachedRoof()}else if(name==='rooms'){this.renderRooms(false)}else if(name==='isolation'){this.renderIsolation()}else if(name==='3d'){this.prepare3D()}else if(name==='quantities'){this.renderQuantities(false)}}
 currentFloorConfig(create=false){const below=$('#floorBelow').value,above=$('#floorAbove').value,bd=B.settings(this.model.data.buildingDesign);let cfg=bd.floors.find(f=>f.belowId===below&&f.aboveId===above);if(!cfg&&create){const bl=this.model.level(below),ab=this.model.level(above);if(!bl||!ab)return null;cfg={...B.config(S,bl,ab),assistant:true,coverageFollowWalls:true,scenarioMode:'standard-prestudy',grade:'C24',enabled:true,coverageZones:{mode:'all',ids:[]},blockingEnabled:true,blockingPattern:'staggered'}}return cfg}
 readFloorUI(){const cfg=this.currentFloorConfig(true);if(!cfg)return null;cfg.spacing=Number($('#floorSpacing').value)||.4;cfg.q=Number($('#floorQ').value)||1.5;cfg.p=Number($('#floorP').value)||2;cfg.panel=Number($('#floorPanel').value)||0;cfg.screed=Number($('#floorScreed').value)||0;cfg.invert=$('#floorDirection').value==='other';cfg.assistant=true;cfg.coverageFollowWalls=true;return cfg}
 saveFloorUI(){const cfg=this.readFloorUI();if(!cfg)return null;const before=JSON.stringify(B.settings(this.model.data.buildingDesign));const bd=B.settings(this.model.data.buildingDesign);bd.floors=bd.floors.filter(f=>f.id!==cfg.id&&f.aboveId!==cfg.aboveId).concat([cfg]);if(JSON.stringify(bd)!==before)this.model.mutate(d=>d.buildingDesign=bd,'réglages solivage');return cfg}
 fillFloorUI(){const stories=this.model.stories();this.fillLevels($('#floorBelow'),true);this.fillLevels($('#floorAbove'),true);let below=$('#floorBelow').value;if(!below&&stories[0])below=stories[0].id,$('#floorBelow').value=below;let cfg=this.currentFloorConfig(false);if(!cfg){const i=stories.findIndex(l=>l.id===below),above=stories[i+1];if(above)$('#floorAbove').value=above.id,cfg=this.currentFloorConfig(false)}if(cfg){$('#floorSpacing').value=cfg.spacing??.4;$('#floorQ').value=cfg.q??1.5;$('#floorP').value=cfg.p??2;$('#floorPanel').value=cfg.panel??22;$('#floorScreed').value=cfg.screed??0;$('#floorDirection').value=cfg.invert?'other':'short'}this.updateFloorStatus()}
 updateFloorStatus(){const cfg=this.currentFloorConfig(false),st=this.cache.state('floor',cfg?.id),el=$('#floorStatus');el.className='status-pill '+st;el.textContent=st==='current'?'À jour':st==='error'?'Erreur':'À recalculer';this.renderWindowBar()}
 calcFloor(){const cfg=this.saveFloorUI();if(!cfg)return;const t=performance.now();try{const r=C.floor(this.model.data,cfg.id),x=this.cache.put('floor',cfg.id,r,performance.now()-t);this.floorView.draw(cfg.belowId,r.elements);this.renderIssues($('#floorResult'),r,'Section '+(r.section?r.section.b+' × '+r.section.h+' mm':'—')+' · '+(r.count||0)+' solives · '+fmt(r.area)+' m²');this.setPerf('Solivage calculé en '+x.ms.toFixed(1)+' ms');}catch(e){this.cache.put('floor',cfg.id,null,0,e);$('#floorResult').innerHTML='<span class="issue-error">'+esc(e.message)+'</span>'}this.updateFloorStatus()}
 renderCachedFloor(){const cfg=this.currentFloorConfig(false),x=cfg&&this.cache.floor.get(cfg.id);if(x?.result){this.floorView.draw(cfg.belowId,x.result.elements);this.renderIssues($('#floorResult'),x.result,'Résultat en cache · '+(x.result.count||0)+' solives')}this.updateFloorStatus()}
 loadFoundationUI(){const s=F.settings(this.model.data.foundationAutomation);$('#faEnabled').checked=s.enabled;$('#faSource').value=s.sourceLevelId||this.model.stories()[0]?.id||'';$('#faSystem').value=s.system;$('#faStripWidth').value=s.stripWidth;$('#faStripHeight').value=s.stripHeight;$('#faTerrain').value=s.terrainZ??'';$('#faBase').value=s.baseZ??-0.8}
 readFoundationUI(){return F.settings({...this.model.data.foundationAutomation,enabled:$('#faEnabled').checked,sourceLevelId:$('#faSource').value,targetLevelId:'foundations',system:$('#faSystem').value,stripWidth:Number($('#faStripWidth').value)||.6,stripHeight:Number($('#faStripHeight').value)||.3,terrainZ:$('#faTerrain').value===''?null:Number($('#faTerrain').value),baseZ:$('#faBase').value===''?null:Number($('#faBase').value)})}
 saveFoundation(){const s=this.readFoundationUI();if(JSON.stringify(s)!==JSON.stringify(F.settings(this.model.data.foundationAutomation)))this.model.mutate(d=>d.foundationAutomation=s,'réglages fondations');return s}
 updateFAStatus(){const st=this.cache.state('foundations'),el=$('#faStatus');el.className='status-pill '+st;el.textContent=st==='current'?'À jour':st==='error'?'Erreur':'À recalculer';this.renderWindowBar()}
 calcFoundations(){const s=this.saveFoundation(),t=performance.now();try{const r=C.foundations(this.model.data),x=this.cache.put('foundations',null,r,performance.now()-t);this.foundationView.draw(s.sourceLevelId,r.elements);this.renderIssues($('#faResult'),r,(r.spanCount||0)+' tronçons · '+(r.padCount||0)+' appuis');this.setPerf('Fondations calculées en '+x.ms.toFixed(1)+' ms')}catch(e){this.cache.put('foundations',null,null,0,e);$('#faResult').innerHTML='<span class="issue-error">'+esc(e.message)+'</span>'}this.updateFAStatus()}
 renderCachedFoundation(){const x=this.cache.foundation,s=F.settings(this.model.data.foundationAutomation);if(x?.result){this.foundationView.draw(s.sourceLevelId,x.result.elements);this.renderIssues($('#faResult'),x.result,'Résultat en cache')}this.updateFAStatus()}
 loadRoofUI(){const s=R.settings(this.model.data.roofDesign);$('#roofEnabled').checked=s.enabled;$('#roofLevel').value=s.supportLevelId||this.model.stories().at(-1)?.id||'';$('#roofSlope').value=s.slopeDeg;$('#roofOverhang').value=s.overhang;$('#roofSpacing').value=s.rafterSpacing;$('#roofDead').value=s.deadLoad;$('#roofSnow').value=s.snowLoad??'';$('#roofWind').value=s.windPressure??'';$('#roofInvert').checked=s.invert}
 readRoofUI(){return R.settings({...this.model.data.roofDesign,enabled:$('#roofEnabled').checked,supportLevelId:$('#roofLevel').value,slopeDeg:Number($('#roofSlope').value)||35,overhang:Number($('#roofOverhang').value)||0,rafterSpacing:Number($('#roofSpacing').value)||.6,deadLoad:Number($('#roofDead').value)||.55,snowLoad:$('#roofSnow').value===''?null:Number($('#roofSnow').value),windPressure:$('#roofWind').value===''?null:Number($('#roofWind').value),invert:$('#roofInvert').checked})}
 saveRoof(){const s=this.readRoofUI();if(JSON.stringify(s)!==JSON.stringify(R.settings(this.model.data.roofDesign)))this.model.mutate(d=>d.roofDesign=s,'réglages toiture');return s}
 updateRoofStatus(){const st=this.cache.state('roof'),el=$('#roofStatus');el.className='status-pill '+st;el.textContent=st==='current'?'À jour':st==='error'?'Erreur':'À recalculer';this.renderWindowBar()}
 calcRoof(){const s=this.saveRoof(),t=performance.now();try{const r=C.roof(this.model.data),x=this.cache.put('roof',null,r,performance.now()-t);this.roofView.draw(s.supportLevelId,r.elements);this.renderIssues($('#roofResult'),r,(r.count||0)+' éléments · '+(r.section?'section '+r.section.b+' × '+r.section.h+' mm':'géométrie'));this.setPerf('Charpente calculée en '+x.ms.toFixed(1)+' ms')}catch(e){this.cache.put('roof',null,null,0,e);$('#roofResult').innerHTML='<span class="issue-error">'+esc(e.message)+'</span>'}this.updateRoofStatus()}
 renderCachedRoof(){const x=this.cache.roof,s=R.settings(this.model.data.roofDesign);if(x?.result){this.roofView.draw(s.supportLevelId,x.result.elements);this.renderIssues($('#roofResult'),x.result,'Résultat en cache')}this.updateRoofStatus()}
 renderIssues(el,r,title){const issues=r?.issues||[],errs=issues.filter(i=>i.severity==='error'),warns=issues.filter(i=>i.severity!=='error');el.innerHTML='<b>'+esc(title)+'</b>'+errs.map(i=>'<p class="issue-error">'+esc(i.text)+'</p>').join('')+warns.slice(0,10).map(i=>'<p class="issue-warn">'+esc(i.text)+'</p>').join('')}
 renderRooms(force){const level=$('#roomsLevel').value||this.model.activeLevelId,st=this.cache.state('rooms',level);if(!force&&st==='current'){this.paintRooms(this.cache.rooms.get(level).result);return}if(!force){$('#roomsGrid').innerHTML='<div class="card">Cliquez sur <b>Détecter les pièces</b>. Aucun calcul n’est fait en arrière-plan.</div>';return}const t=performance.now();try{const r=C.rooms(this.model.data,level);this.cache.put('rooms',level,r,performance.now()-t);this.paintRooms(r);this.renderWindowBar()}catch(e){$('#roomsGrid').innerHTML='<div class="card issue-error">'+esc(e.message)+'</div>'}}
 paintRooms(r){$('#roomsGrid').innerHTML=(r.rows||[]).map(x=>'<div class="card"><h3>'+esc(x.name)+'</h3><div>Surface intérieure : <b>'+(x.area==null?'—':fmt(x.area)+' m²')+'</b></div><div style="font-size:10px;color:#6b7c87">Axes : '+fmt(x.axisArea)+' m²</div></div>').join('')||'<div class="card">Aucune pièce fermée détectée.</div>'}
 fillIsolationWalls(){const s=$('#isoWall'),old=s.value;s.innerHTML=this.model.elements.filter(e=>e.levelId===this.model.activeLevelId&&['wallExterior','wallBearing','partition'].includes(e.type)&&e.a&&e.b).map(e=>'<option value="'+e.id+'">'+esc(typeName[e.type])+' · '+fmt(dist(e.a,e.b))+' m</option>').join('');if([...s.options].some(o=>o.value===old))s.value=old}
 renderIsolation(){this.fillIsolationWalls();const rows=this.model.data.envelopeDesign?.assemblies||[];$('#isoList').innerHTML=rows.map(a=>{const w=this.model.elements.find(e=>e.id===a.hostId),L=w?dist(w.a,w.b):0,H=w?.height||0,Rv=a.lambda>0?a.thickness/1000/a.lambda:0;return'<div class="card"><h3>'+esc((a.kind||'ITI').toUpperCase())+'</h3><div>Mur : '+esc(w?.id||'support absent')+' · '+fmt(L)+' m</div><div>Isolant : '+fmt(a.thickness,0)+' mm · R ≈ '+fmt(Rv)+' m².K/W</div></div>'}).join('')||'<div class="card">Aucune isolation enregistrée.</div>'}
 saveIsolation(){const host=$('#isoWall').value;if(!host)return;const row={id:'iso:'+host+':'+$('#isoKind').value,hostId:host,levelId:this.model.activeLevelId,kind:$('#isoKind').value,thickness:Number($('#isoThickness').value)||0,lambda:Number($('#isoLambda').value)||.035};this.model.mutate(d=>{const e={assemblies:[...((d.envelopeDesign&&d.envelopeDesign.assemblies)||[])]},i=e.assemblies.findIndex(x=>x.id===row.id);if(i>=0)e.assemblies[i]=row;else e.assemblies.push(row);d.envelopeDesign=e},'isolation');this.renderIsolation()}
 prepare3D(){const derived=[];const floors=B.settings(this.model.data.buildingDesign).floors.filter(f=>f.enabled);for(const cfg of floors){let x=this.cache.floor.get(cfg.id);if(!x||x.revision!==this.model.revision){try{const t=performance.now(),r=C.floor(this.model.data,cfg.id);x=this.cache.put('floor',cfg.id,r,performance.now()-t)}catch(e){x=this.cache.put('floor',cfg.id,null,0,e)}}if(x.result)derived.push(...x.result.elements)}const fs=F.settings(this.model.data.foundationAutomation);if(fs.enabled){let x=this.cache.foundation;if(!x||x.revision!==this.model.revision)try{const t=performance.now();x=this.cache.put('foundations',null,C.foundations(this.model.data),performance.now()-t)}catch(e){x=this.cache.put('foundations',null,null,0,e)}if(x.result)derived.push(...x.result.elements)}const rs=R.settings(this.model.data.roofDesign);if(rs.enabled){let x=this.cache.roof;if(!x||x.revision!==this.model.revision)try{const t=performance.now();x=this.cache.put('roof',null,C.roof(this.model.data),performance.now()-t)}catch(e){x=this.cache.put('roof',null,null,0,e)}if(x.result)derived.push(...x.result.elements)}this._derived3d=derived;this.cache.view3dRev=this.model.revision;this.render3D();this.renderWindowBar();$('#view3dResult').innerHTML='<b>3D reconstruite.</b> Les moteurs techniques ne seront plus rappelés tant que le projet ne change pas.'}
 render3D(){this.view3d.draw(this._derived3d||[])}
 renderQuantities(force){if(!force&&this.cache.state('quantities')==='current'){this.paintQuantities(this.cache.quantity.result);return}if(!force){$('#quantityTable').innerHTML='<div class="card">Cliquez sur Calculer le métré.</div>';return}const floorResults=[];for(const cfg of B.settings(this.model.data.buildingDesign).floors.filter(f=>f.enabled)){let x=this.cache.floor.get(cfg.id);if(!x||x.revision!==this.model.revision)try{x=this.cache.put('floor',cfg.id,C.floor(this.model.data,cfg.id),0)}catch{}if(x?.result)floorResults.push(x.result)}const q=C.quantities(this.model.data,floorResults,this.cache.foundation?.result);this.cache.put('quantities',null,q,0);this.paintQuantities(q);$('#quantityStatus').className='status-pill current';$('#quantityStatus').textContent='À jour';this.renderWindowBar()}
 paintQuantities(q){const rows=q?.rows||[];$('#quantityTable').innerHTML='<table class="data-table"><thead><tr><th>Niveau</th><th>Matériau</th><th>Désignation</th><th>Unité</th><th>Quantité</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(r.level||'')+'</td><td>'+esc(r.material||'')+'</td><td>'+esc(r.label||'')+'</td><td>'+esc(r.unit||'')+'</td><td>'+fmt(r.quantity,2)+'</td></tr>').join('')+'</tbody></table>'}
 addLevel(){const stories=this.model.stories(),last=stories.at(-1),name=prompt('Nom du niveau :','R+'+Math.max(2,stories.length));if(!name||!last)return;const z=Number(prompt('Altitude (m) :',String(Number(last.elevation)+Number(last.height||2.8))));if(!Number.isFinite(z))return;const id=uid();this.model.mutate(d=>{d.levels.push({id,name,elevation:z,height:2.8});d.levels.sort((a,b)=>a.elevation-b.elevation);const roof=d.levels.find(l=>l.id==='roof');if(roof&&roof.elevation<=z)roof.elevation=z+2.8;d.activeLevelId=id},'ajout niveau',{all:true});this.model.activeLevelId=id;this.fillAllSelectors()}
 syncPlacement(){const s=this.toolSettings[this.activeTool];$('.placement').style.display=s&&this.activeTool!=='select'?'block':'none';$('#placementName').textContent=typeName[this.activeTool]||this.activeTool;if(s){$('#placementThickness').value=s.thickness??s.width??.1;$('#placementHeight').value=s.height??.2}}
 bind(){
  $$('.tool').forEach(b=>b.onclick=()=>this.setTool(b.dataset.tool));$('#planCanvas').addEventListener('pointerdown',e=>this.beginDrag(e));$('#planCanvas').addEventListener('pointermove',e=>{if(this.moveDrag(e))return;const p=this.screenEvent(e);this.pointerWorld=this.snap(this.plan.screen(p),{start:this.drawingStart});$('#statusCoords').textContent='X: '+fmt(this.pointerWorld.x)+' m · Y: '+fmt(this.pointerWorld.y)+' m';if(this.drawingStart){const L=dist(this.drawingStart,this.pointerWorld),a=((Math.atan2(this.pointerWorld.y-this.drawingStart.y,this.pointerWorld.x-this.drawingStart.x)*180/Math.PI)%360+360)%360;$('#statusMeasure').textContent='Longueur: '+fmt(L)+' m · Angle: '+fmt(a,1)+'°'}this.requestPlan()});$('#planCanvas').addEventListener('pointerup',e=>this.endDrag(e));$('#planCanvas').addEventListener('pointercancel',()=>this.cancelDrag());$('#planCanvas').addEventListener('click',e=>this.clickPlan(e));$('#planCanvas').addEventListener('dblclick',()=>{this.drawingStart=null;this.pointerWorld=null;this.requestPlan()});$('#planCanvas').addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey)this.plan.scale=Math.max(.3,Math.min(5,this.plan.scale*Math.exp(-e.deltaY*.0025)));else{this.plan.pan.x-=e.deltaX;this.plan.pan.y-=e.deltaY}this.updateZoom();this.requestPlan()},{passive:false});
  $('#placementThickness').onchange=e=>{const s=this.toolSettings[this.activeTool];if(s){if('thickness'in s)s.thickness=Number(e.target.value);else s.width=Number(e.target.value)}};$('#placementHeight').onchange=e=>{const s=this.toolSettings[this.activeTool];if(s)s.height=Number(e.target.value)};
  $('#closeProperties').onclick=()=>{this.selected=null;this.renderProperties();this.requestPlan()};$('#deleteSelected')?.addEventListener('click',()=>{});
  $('#levelSelect').onchange=e=>{this.model.activeLevelId=e.target.value;this.selected=null;this.fillMagnetRefs();this.fillIsolationWalls();this.requestPlan()};$('#addLevelBtn').onclick=()=>this.addLevel();
  $('#undoBtn').onclick=()=>{if(this.model.undo()){this.fillAllSelectors();this.requestPlan()}};$('#redoBtn').onclick=()=>{if(this.model.redo()){this.fillAllSelectors();this.requestPlan()}};
  $('#saveBtn').onclick=()=>{localStorage.setItem('planBatimentProV17',this.model.snapshot());this.setPerf('Projet v17 enregistré')};$('#exportBtn').onclick=()=>{const blob=new Blob([this.model.snapshot()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='plan-batiment-pro-v17.json';a.click();URL.revokeObjectURL(a.href)};$('#importJson').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{this.model.restore(await f.text());this.cache=new Cache(this);this.fillAllSelectors();this.openWindow('plan')}catch(err){alert('Fichier invalide : '+err.message)}e.target.value=''};$('#newBtn').onclick=()=>{if(!confirm('Créer un nouveau projet v17 ?'))return;this.model=new Model(defaults(),this.bus);this.cache=new Cache(this);this.fillAllSelectors();this.openWindow('plan')};
  $('#cotesBtn').onclick=()=>{this.display.dimensions=!this.display.dimensions;this.model.data.drawingDisplay={...this.display};this.syncToolbar();this.requestPlan()};$('#gridBtn').onclick=()=>{this.display.grid=!this.display.grid;this.model.data.drawingDisplay={...this.display};this.syncToolbar();this.requestPlan()};$('#magnetBtn').onclick=()=>{this.magnet.enabled=!this.magnet.enabled;this.model.data.magnet={...this.magnet};this.syncToolbar();this.requestPlan()};$('#crossLevels').onchange=e=>{this.magnet.crossLevels=e.target.checked;this.model.data.magnet={...this.magnet};this.requestPlan()};$('#magnetRef').onchange=e=>{this.magnet.reference=e.target.value;this.model.data.magnet={...this.magnet};this.requestPlan()};
  $('#drawOptionsBtn').onclick=()=>$('#drawOptions').showModal();$('#overlayBtn').onclick=()=>$('#overlayDialog').showModal();$('#optAutoDims').onchange=e=>{this.display.automatic=e.target.checked;this.model.data.drawingDisplay={...this.display};this.requestPlan()};$('#optManualDims').onchange=e=>{this.display.manual=e.target.checked;this.model.data.drawingDisplay={...this.display};this.requestPlan()};$('#optSelectedDims').onchange=e=>{this.display.selectedOnly=e.target.checked;this.model.data.drawingDisplay={...this.display};this.requestPlan()};$('#optUnit').onchange=e=>{this.display.unit=e.target.value;this.model.data.drawingDisplay={...this.display};this.requestPlan()};$('#overlayBelow').onchange=e=>{this.overlay.below=e.target.checked;this.requestPlan()};$('#overlayAbove').onchange=e=>{this.overlay.above=e.target.checked;this.requestPlan()};$('#overlayFoundations').onchange=e=>{this.overlay.foundations=e.target.checked;this.requestPlan()};$('#overlayOpacity').oninput=e=>{this.overlay.opacity=Number(e.target.value);this.requestPlan()};
  $('#zoomIn').onclick=()=>{this.plan.scale=Math.min(5,this.plan.scale*1.15);this.updateZoom();this.requestPlan()};$('#zoomOut').onclick=()=>{this.plan.scale=Math.max(.3,this.plan.scale/1.15);this.updateZoom();this.requestPlan()};$('#zoomReset').onclick=()=>{this.plan.scale=1;this.plan.pan={x:0,y:0};this.updateZoom();this.requestPlan()};
  $('#floorBelow').onchange=()=>{const stories=this.model.stories(),i=stories.findIndex(l=>l.id===$('#floorBelow').value);if(i>=0&&stories[i+1])$('#floorAbove').value=stories[i+1].id;this.fillFloorUI()};$('#floorAbove').onchange=()=>this.fillFloorUI();$('#floorSave').onclick=()=>{this.saveFloorUI();this.updateFloorStatus()};$('#floorCalc').onclick=()=>this.calcFloor();
  $('#faSave').onclick=()=>{this.saveFoundation();this.updateFAStatus()};$('#faCalc').onclick=()=>this.calcFoundations();$('#roofSave').onclick=()=>{this.saveRoof();this.updateRoofStatus()};$('#roofCalc').onclick=()=>this.calcRoof();
  $('#roomsRefresh').onclick=()=>this.renderRooms(true);$('#roomsLevel').onchange=()=>this.renderRooms(false);$('#isoSave').onclick=()=>this.saveIsolation();$('#quantityCalc').onclick=()=>this.renderQuantities(true);$('#toolsMobile').onclick=()=>document.body.classList.toggle('tools-open');
  root.addEventListener('keydown',e=>{this.alt=e.altKey;if(e.key==='Escape'){this.cancelDrag();this.drawingStart=null;this.requestPlan()}if((e.key==='Delete'||e.key==='Backspace')&&this.selected&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){const id=this.selected.id,level=this.selected.levelId;this.model.mutate(d=>d.elements=d.elements.filter(x=>x.id!==id),'suppression',{levelId:level});this.selected=null;this.renderProperties()}});root.addEventListener('keyup',e=>{this.alt=e.altKey});root.addEventListener('blur',()=>{this.alt=false});
 }
 updateZoom(){$('#zoomReset').textContent=Math.round(this.plan.scale*100)+' %'}
}
const app=new App();root.PBPV17=app;
})(window);