/* Plan Bâtiment Pro v0.12.1 — autonomous project dashboard. */
(function(){'use strict';
const app=window.planApp,A=window.PBPAutonomy,$=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v));if(!app||!A)throw Error('Noyau autonome indisponible.');
const P=ProjectModel.prototype,oldSnap=P.snapshot,oldRestore=P.restore;P.snapshot=function(){const d=JSON.parse(oldSnap.call(this));d.projectAutonomy=A.settings(this.projectAutonomy);return JSON.stringify(d);};P.restore=function(t){const d=JSON.parse(t);oldRestore.call(this,t);this.projectAutonomy=A.settings(d.projectAutonomy);};
let last=null,busy=false;const stateText={ok:'✓',partial:'◐',missing:'!',error:'⛔',pending:'○',planned:'◇'};
function refresh(){last=A.analyze(app.model);renderBadge();if($('#autoDialog')?.open)renderDialog();}
function renderBadge(){const r=last||A.analyze(app.model),b=$('#autoBadge');if(!b)return;const errors=Object.values(r.modules).filter(x=>x.state==='error').length,missing=r.todos.length;b.textContent='AUTO '+(r.settings.mode==='automatic'?'✓':'EXPERT')+' · '+r.project.levels+' niv. · sismique '+(r.seismic.zone||'?')+(errors?' · '+errors+' blocage(s)':missing?' · '+missing+' à compléter':' · prêt');b.classList.toggle('bad',!!errors);}
function moduleRows(r){return Object.values(r.modules).map(x=>'<div class="auto-module '+x.state+'"><span>'+stateText[x.state]+'</span><b>'+x.label+'</b><small>'+x.detail+'</small></div>').join('');}
function renderDialog(){const r=A.analyze(app.model);last=r;$('#autoMode').value=r.settings.mode;$('#autoType').value=r.settings.buildingType;$('#autoUse').value=r.settings.use;$('#autoImportance').value=r.settings.importance;$('#autoSoil').value=r.settings.soilClass;$('#autoZone').value=r.settings.seismicZone||'';const f=window.PBPFoundations?.settings?.(app.model.foundationAutomation)||{};$('#autoLocation').textContent=f.communeName?(f.communeName+(f.inseeCode?' · '+f.inseeCode:'')):'Localisation à définir dans Fondations auto';const s=r.seismic;$('#autoSeismic').innerHTML='<b>Zone '+(s.zone||'—')+(s.zone?' · '+s.label:'')+'</b>'+(s.agr!=null?'<br>agr = '+s.agr.toFixed(2)+' m/s²':'')+(s.category?'<br>Catégorie '+s.category+' · γI = '+s.gammaI.toFixed(1):'')+(s.ag!=null?'<br>ag = '+s.ag.toFixed(2)+' m/s²':'')+(s.S!=null?'<br>Classe de sol '+s.soilClass+' · S = '+s.S.toFixed(2):'')+'<br><span class="'+(s.applicable?'auto-warn':'auto-muted')+'">'+(s.zone?(s.applicable?'Règles parasismiques à intégrer au dimensionnement de ce bâtiment.':'Pas d’exigence générale EC8 détectée par ce test simplifié pour bâtiment neuf ; vérifier le contexte précis.'):'Zone sismique non déterminée.')+'</span>';$('#autoModules').innerHTML=moduleRows(r);$('#autoTodos').innerHTML=r.todos.length?r.todos.map(x=>'<li>'+x+'</li>').join(''):'<li>Aucune donnée bloquante identifiée par le noyau actuel.</li>';}
function read(){return A.settings({...A.settings(app.model.projectAutonomy),mode:$('#autoMode').value,buildingType:$('#autoType').value,use:$('#autoUse').value,importance:$('#autoImportance').value,soilClass:$('#autoSoil').value,seismicZone:$('#autoZone').value?Number($('#autoZone').value):null});}
async function seismicLookup(){if(busy)return;const f=window.PBPFoundations?.settings?.(app.model.foundationAutomation)||{},code=f.inseeCode,status=$('#autoLookupStatus');if(!code){status.textContent='Commencez par renseigner le code postal / la commune dans Fondations auto.';return;}busy=true;status.textContent='Recherche Géorisques…';try{const out=await A.lookupSeismicByInsee(code);app.model.commit();A.set(app.model,{...read(),seismicZone:out.zone,seismicSource:'Géorisques / code INSEE',seismicCheckedAt:new Date().toISOString()});status.textContent='Zone '+out.zone+' récupérée automatiquement.';refresh();app.renderer2d?.draw();app.renderer3d?.draw();}catch(e){status.textContent='Sismicité non récupérée automatiquement : '+e.message+'. Vous pouvez saisir la zone en mode Expert.';}finally{busy=false;}}
function init(){
 const style=document.createElement('style');style.textContent=`.auto-card{padding:8px 0;border-bottom:1px solid #dfe6eb}.auto-card button{width:100%;font-size:12px}.auto-card small{display:block;font-size:10px;color:#667985;margin-top:4px}#autoBadge{position:absolute;left:8px;top:8px;z-index:9;background:#eef6faef;border:1px solid #a9c8d8;border-radius:6px;padding:5px 8px;font-size:10px;color:#28586d;pointer-events:none}#autoBadge.bad{background:#fff0ed;border-color:#dfaaa0;color:#873a2d}#autoDialog{width:min(650px,95vw);max-height:92vh;overflow:auto}#autoForm{display:block;padding:15px}#autoForm h3{margin:0 0 10px}.auto-row{display:grid!important;grid-template-columns:1fr minmax(150px,42%);gap:8px;align-items:center;margin:9px 0;font-size:12px}.auto-row select{width:100%;padding:6px;border:1px solid #ccd8df;border-radius:5px;background:white}.auto-panel{background:#eff5f8;border:1px solid #d0e0e7;border-radius:7px;padding:9px;margin:9px 0;font-size:12px;line-height:1.55}.auto-module{display:grid;grid-template-columns:20px 150px 1fr;gap:6px;align-items:start;padding:7px;border-bottom:1px solid #e5eaee;font-size:11px}.auto-module small{color:#60727d}.auto-module.error{color:#9a3528}.auto-module.ok>span{color:#297143}.auto-module.partial>span,.auto-module.missing>span{color:#9a6b1b}.auto-muted{color:#667985}.auto-warn{color:#8b5f18;font-weight:600}#autoTodos{font-size:11px;line-height:1.5}.auto-actions{display:flex;gap:7px;justify-content:flex-end;position:sticky;bottom:-15px;background:white;border-top:1px solid #dce5ea;margin:12px -15px -15px;padding:12px 15px}.auto-primary{background:#245c7d;color:white}`;document.head.appendChild(style);
 const card=document.createElement('div');card.className='auto-card';card.innerHTML='<button id="autoOpen">⚙ Projet autonome</button><small>Contexte projet · calculs liés · réglementation</small>';$('.mode-title').after(card);const badge=document.createElement('div');badge.id='autoBadge';$('#canvasShell').appendChild(badge);
 const d=document.createElement('dialog');d.id='autoDialog';d.innerHTML='<form id="autoForm"><h3>Noyau autonome du projet</h3><p class="auto-muted">Le logiciel déduit et recalcule ce qui peut l’être. Une donnée technique indisponible n’est jamais inventée.</p><label class="auto-row">Mode<select id="autoMode"><option value="automatic">Automatique</option><option value="expert">Expert</option></select></label><label class="auto-row">Type de bâtiment<select id="autoType"><option value="house-single">Maison plain-pied</option><option value="house-storey">Maison à étage</option><option value="apartment-building">Immeuble d’habitation</option><option value="other">Autre bâtiment</option></select></label><label class="auto-row">Usage<select id="autoUse"><option value="residential">Habitation</option><option value="mixed">Mixte</option><option value="other">Autre</option></select></label><label class="auto-row">Catégorie sismique<select id="autoImportance"><option value="auto">Automatique</option><option value="I">I</option><option value="II">II</option><option value="III">III</option><option value="IV">IV</option></select></label><label class="auto-row">Zone sismique<select id="autoZone"><option value="">Automatique / à déterminer</option><option value="1">1 · très faible</option><option value="2">2 · faible</option><option value="3">3 · modérée</option><option value="4">4 · moyenne</option><option value="5">5 · forte</option></select></label><label class="auto-row">Classe de sol EC8<select id="autoSoil"><option value="unknown">À déterminer</option><option value="A">A</option><option value="B">B</option><option value="C">C</option><option value="D">D</option><option value="E">E</option></select></label><div class="auto-panel"><b>Localisation</b><br><span id="autoLocation"></span><p><button type="button" id="autoLookup">Actualiser le zonage sismique</button></p><div id="autoLookupStatus" class="auto-muted"></div></div><div id="autoSeismic" class="auto-panel"></div><h4>État des moteurs</h4><div id="autoModules"></div><h4>Ce qu’il reste réellement à fournir / calculer</h4><ul id="autoTodos"></ul><div class="auto-actions"><button type="button" id="autoClose">Fermer</button><button type="submit" class="auto-primary">Appliquer et recalculer</button></div></form>';document.body.appendChild(d);
 $('#autoOpen').onclick=()=>{renderDialog();d.showModal();};$('#autoClose').onclick=()=>d.close();$('#autoLookup').onclick=seismicLookup;$('#autoForm').onsubmit=e=>{e.preventDefault();app.model.commit();A.set(app.model,read());refresh();window.PBPFoundationUI?.refresh?.();window.PBPBuildingUI?.refresh?.();app.renderer2d?.draw();app.renderer3d?.draw();d.close();};for(const id of ['autoMode','autoType','autoUse','autoImportance','autoZone','autoSoil'])$('#'+id).onchange=()=>{app.model.projectAutonomy=read();renderDialog();};
 $('.version').textContent='v0.12.1';document.title='Plan Bâtiment Pro — v0.12.1';window.PBPAutonomyReady=true;refresh();
 const f=window.PBPFoundations?.settings?.(app.model.foundationAutomation)||{};if(f.inseeCode&&!A.settings(app.model.projectAutonomy).seismicZone)A.lookupSeismicByInsee(f.inseeCode).then(x=>{A.set(app.model,{seismicZone:x.zone,seismicSource:'Géorisques / code INSEE',seismicCheckedAt:new Date().toISOString()});refresh();}).catch(()=>{});
}
window.PBPAutonomyUI={refresh,open:()=>$('#autoOpen')?.click(),getReport:()=>clone(last||A.analyze(app.model))};if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();
