/* Plan Bâtiment Pro v0.12.0 — central autonomous project context. */
(function(root){
'use strict';
const clone=v=>JSON.parse(JSON.stringify(v));
const ZONES={1:{label:'Très faible',agr:.4},2:{label:'Faible',agr:.7},3:{label:'Modérée',agr:1.1},4:{label:'Moyenne',agr:1.6},5:{label:'Forte',agr:3}};
const GAMMA={I:.8,II:1,III:1.2,IV:1.4};
const SOIL_S={normal:{A:1,B:1.35,C:1.5,D:1.6,E:1.8},zone5:{A:1,B:1.2,C:1.15,D:1.35,E:1.4}};
const defaults=()=>({schema:1,mode:'automatic',buildingType:'house-storey',use:'residential',importance:'auto',soilClass:'unknown',seismicZone:null,seismicSource:'unknown',seismicCheckedAt:'',permitIntent:true,autoRecalculate:true,autoDocuments:true,ruleSet:'FR-2026-09'});
function settings(v){v=v&&typeof v==='object'?v:{};const s={...defaults(),...clone(v)};if(!['automatic','expert'].includes(s.mode))s.mode='automatic';if(!['house-single','house-storey','apartment-building','other'].includes(s.buildingType))s.buildingType='house-storey';if(!['residential','mixed','other'].includes(s.use))s.use='residential';if(!['auto','I','II','III','IV'].includes(s.importance))s.importance='auto';if(!['unknown','A','B','C','D','E'].includes(s.soilClass))s.soilClass='unknown';s.seismicZone=Number.isInteger(+s.seismicZone)&&+s.seismicZone>=1&&+s.seismicZone<=5?+s.seismicZone:null;s.autoRecalculate=s.autoRecalculate!==false;s.autoDocuments=s.autoDocuments!==false;s.permitIntent=s.permitIntent!==false;return s;}
function habitableLevels(model){const f=root.PBPGeometry?.foundationIds?root.PBPGeometry.foundationIds(model):new Set(['foundations']);return (model.levels||[]).filter(l=>!l.autoFloor&&!f.has(l.id)&&l.id!=='roof'&&!/^toiture$/i.test(l.name||'')).sort((a,b)=>a.elevation-b.elevation);}
function buildingHeight(model){const ls=habitableLevels(model);if(!ls.length)return 0;const low=Math.min(...ls.map(l=>Number(l.elevation)||0)),high=Math.max(...ls.map(l=>(Number(l.elevation)||0)+(Number(l.height)||0)));return Math.max(0,high-low);}
function inferImportance(s,model){if(s.importance!=='auto')return{category:s.importance,source:'manual'};const h=buildingHeight(model);if(s.buildingType==='house-single'||s.buildingType==='house-storey')return{category:'II',source:'habitation individuelle'};if(s.buildingType==='apartment-building')return{category:h<=28?'II':'III',source:h<=28?'habitation collective ≤ 28 m':'habitation collective > 28 m'};return{category:null,source:'à définir'};}
function seismic(zone,category,soilClass){const z=ZONES[zone]||null,gamma=GAMMA[category]||null,soil=soilClass&&soilClass!=='unknown'?soilClass:null;const applicable=!!z&&!!category&&((zone>=3&&['II','III','IV'].includes(category))||(zone===2&&['III','IV'].includes(category)));const S=z&&soil?(zone===5?SOIL_S.zone5[soil]:SOIL_S.normal[soil]):null;return{zone:zone||null,label:z?.label||'À déterminer',agr:z?.agr??null,category:category||null,gammaI:gamma,ag:z&&gamma?z.agr*gamma:null,soilClass:soil,S,applicable,completeForSiteParameters:!!(z&&gamma&&soil),standard:'NF EN 1998-1 / EN 1998-5 + arrêté du 22 octobre 2010 modifié'};}
function safe(fn,fallback=null){try{return fn();}catch{return fallback;}}
function status(state,label,detail,action=null){return{state,label,detail,action};}
function analyze(model){
 const s=settings(model.projectAutonomy),imp=inferImportance(s,model),seis=seismic(s.seismicZone,imp.category,s.soilClass),levels=habitableLevels(model),height=buildingHeight(model);
 const fr=safe(()=>root.PBPFoundationUI?.getReport?.()),br=safe(()=>root.PBPBuildingUI?.getReport?.()),sr=safe(()=>root.PBPStructureUI?.getReport?.());
 const todos=[],modules={},foundationErrors=fr?.issues?.filter(i=>i.severity==='error')||[];
 if(fr?.settings?.enabled){const geo=fr.standards?.geotech;modules.foundations=foundationErrors.length?status('error','Fondations',foundationErrors[0].text):geo?.ready?status('ok','Fondations','Pré-dimensionnement géotechnique disponible ; exécution à justifier.'):status('missing','Fondations','qRd / NEd ou données géotechniques incomplètes.');if(!geo?.ready)todos.push('Renseigner qRd et NEd depuis l’étude géotechnique / descente de charges.');}else modules.foundations=status('pending','Fondations','Automatisation non activée.');
 const floors=br?.floors||[],floorErrors=floors.flatMap(x=>x.issues||[]).filter(i=>i.severity==='error');
 modules.floors=floors.length?(floorErrors.length?status('error','Planchers / solivage',floorErrors[0].text):floors.every(x=>x.complete)?status('ok','Planchers / solivage',floors.length+' plancher(s) de préétude calculé(s).'):status('missing','Planchers / solivage','Calcul incomplet.')):status('pending','Planchers / solivage','Aucun plancher automatique calculé.');
 modules.structure=sr?status('partial','Structure','Moteur structure relié ; descente de charges globale encore à consolider.'):status('pending','Structure','Moteur structure à consolider.');
 const rr=safe(()=>root.PBPRoofUI?.getReport?.()),er=safe(()=>root.PBPEnvelopeUI?.getReport?.());
 modules.roof=rr?.settings?.enabled?(rr.complete?status('partial','Charpente','Chevrons EC5 de préétude calculés ; pannes/fermes/assemblages restent à compléter.'):status(rr?.issues?.some(i=>i.severity==='error')?'error':'missing','Charpente',rr?.issues?.[0]?.text||'Calcul incomplet.')):status('pending','Charpente','Charpente automatique non activée.');
 modules.envelope=er?.rows?.length?(er.issues?.some(i=>i.severity==='error')?status('error','Second œuvre / Isolation',er.issues.find(i=>i.severity==='error').text):status('ok','Second œuvre / Isolation',er.rows.length+' paroi(s) calculée(s) : montants, plaques et isolants.')):status('pending','Second œuvre / Isolation','Aucun doublage ou cloison sèche calculé.');
 modules.joinery=status('planned','Menuiseries','Calcul menuiseries/linteaux à construire.');modules.permit=status('partial','Permis de construire','Cotation architecturale disponible ; dossier PC complet à générer depuis le modèle.');modules.view3d=status('ok','3D','Vue 3D synchronisée avec la géométrie courante.');
 if(rr?.settings?.enabled&&!rr.complete)todos.push('Compléter les charges neige/vent et la géométrie nécessaires à la charpente.');if(!er?.rows?.length)todos.push('Définir les doublages/cloisons et l’isolation intérieure/extérieure du projet.');if(!s.seismicZone)todos.push('Déterminer la zone sismique depuis la commune du projet.');else if(seis.applicable&&s.soilClass==='unknown')todos.push('Renseigner la classe de sol A–E issue des données géotechniques.');if(!imp.category)todos.push('Définir la catégorie d’importance sismique du bâtiment.');if(seis.applicable)todos.push('Compléter le calcul parasismique avec masses, régularité, contreventement et paramètres Eurocode 8.');
 return{settings:s,project:{levels:levels.length,height,buildingType:s.buildingType,use:s.use,mode:s.mode},importance:imp,seismic:seis,modules,todos:[...new Set(todos)],ready:!Object.values(modules).some(x=>x.state==='error'),generatedAt:new Date().toISOString()};
}
function set(model,patch){model.projectAutonomy=settings({...settings(model.projectAutonomy),...patch});return model.projectAutonomy;}
async function lookupSeismicByInsee(code){if(!/^\d{5}$/.test(String(code||'')))throw Error('Code INSEE invalide');const r=await fetch('https://georisques.gouv.fr/api/v1/zonage_sismique?code_insee='+encodeURIComponent(code));if(!r.ok)throw Error('Géorisques sismicité indisponible');const data=await r.json();let zone=null,seen=0;function walk(v,k=''){if(zone||seen++>1000||v==null)return;if(typeof v==='number'&&v>=1&&v<=5&&/(zone|sism|niveau)/i.test(k)){zone=Math.trunc(v);return;}if(typeof v==='string'){const m=v.match(/(?:zone|sismic[^0-9]*)([1-5])/i)||v.match(/^([1-5])$/);if(m){zone=+m[1];return;}}if(Array.isArray(v))for(const x of v)walk(x,k);else if(typeof v==='object')for(const [kk,x] of Object.entries(v))walk(x,kk);}walk(data);if(!zone)throw Error('Zone sismique non reconnue dans la réponse');return{zone,data};}
const api={settings,habitableLevels,buildingHeight,inferImportance,seismic,analyze,set,lookupSeismicByInsee,ZONES,GAMMA,SOIL_S};
if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.PBPAutonomy=api;
})(typeof window!=='undefined'?window:globalThis);
