/* v0.9 compositions, floor levels, services clearance and quantity take-off. */
(function(){'use strict';const B=PBPBuilding,G=PBPGeometry,S=PBPStructure,F=PBPFoundations,app=planApp,$=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,n=2)=>Number.isFinite(v)?v.toFixed(n).replace('.',','):'—';
let draft=null,levelId='',floorId='',tab='materials',key='',cached=null,ready=false,rendering=false,selectKey='';
const P=ProjectModel.prototype,oldSnap=P.snapshot,oldRestore=P.restore,oldAdd=P.addElement,oldUpdate=P.updateElement;
P.snapshot=function(){const d=JSON.parse(oldSnap.call(this));d.buildingDesign=B.settings(this.buildingDesign);d.elements=d.elements.filter(e=>e.generator!==B.TAG);d.levels=d.levels.filter(l=>!l.autoFloor);return JSON.stringify(d);};
P.restore=function(text){oldRestore.call(this,text);this.buildingDesign=B.settings(JSON.parse(text).buildingDesign);this.elements=this.elements.filter(e=>e.generator!==B.TAG);key='';sync(this);};
function assign(e,m,force=true){const p=B.settings(m.buildingDesign).materials[e.levelId];if(p&&p.type!=='unknown'&&['wallExterior','wallBearing','partition'].includes(e.type)){e.materialSpec=clone(p);const extras=Number(p.insulation)+Number(p.inside)+Number(p.outside),total=(Number(p.core)+extras)/1000;if(!force&&Number(e.thickness)*1000>extras)e.materialSpec.core=Number(e.thickness)*1000-extras;else e.thickness=total;}return e;}
P.addElement=function(data){return oldAdd.call(this,assign({...data,levelId:data.levelId||this.activeLevelId},this,false));};
P.updateElement=function(id,patch){const e=this.elements.find(e=>e.id===id);if(e?.materialSpec&&patch.thickness!==undefined){const p=e.materialSpec,core=Number(patch.thickness)*1000-Number(p.insulation)-Number(p.inside)-Number(p.outside);if(!(core>0)){alert('Cette épaisseur ne laisse pas de place au cœur porteur après les parements et isolants.');return;}patch={...patch,materialSpec:{...p,core}};}return oldUpdate.call(this,id,patch);};
function calculate(m=app.model){const signature=JSON.stringify([m.buildingDesign,m.structureDesign,m.foundationAutomation,m.levels.filter(l=>!l.autoFloor),m.elements.filter(e=>e.generator!==B.TAG)]);if(key!==signature){cached=B.report(m,G,S,F);key=signature;}return cached;}
function sync(m){const r=calculate(m),stories=m.levels.filter(l=>!l.autoFloor);m.levels=stories.concat(r.levels).sort((a,b)=>a.elevation-b.elevation);if(!m.levels.some(l=>l.id===m.activeLevelId))m.activeLevelId=stories.find(l=>l.id==='ground')?.id||stories[0]?.id;return r;}
function selector(){if(!ready)return;const sig=JSON.stringify(app.model.levels.map(l=>[l.id,l.name,l.elevation,l.height]));if(sig!==selectKey){selectKey=sig;const s=$('#levelSelect');s.replaceChildren();for(const l of app.model.levels){const o=document.createElement('option');o.value=l.id;o.textContent=(l.kind==='floor'?'▤ ':'')+l.name+' ('+fmt(l.elevation)+' m)';s.appendChild(o);}s.value=app.model.activeLevelId;}}
function refresh(){key='';sync(app.model);selector();app.renderer2d?.draw();app.renderer3d?.draw();}
for(const R of [PlanRenderer2D,ConstructionRenderer3D]){const draw=R.prototype.draw;R.prototype.draw=function(...args){if(rendering)return draw.apply(this,args);rendering=true;const m=this.app.model,original=m.elements;try{const r=sync(m);m.elements=original.concat(r.elements.filter(e=>!e.hiddenLayer));selector();return draw.apply(this,args);}finally{m.elements=original;rendering=false;}};}
const layer=PlanRenderer2D.prototype.drawLayer;
const colors={concrete:'#a7afb5',panel:'#cfb88c',insulation:'#e7d793',ravoirage:'#c3b9a7',screed:'#b8b8ae',finish:'#d1c1ad',ceiling:'#e2e5e8'};
PlanRenderer2D.prototype.drawLayer=function(elements,alpha,overlay){const own=elements.filter(e=>e.generator===B.TAG),rest=elements.filter(e=>e.generator!==B.TAG);layer.call(this,rest,alpha,overlay);const c=this.ctx;c.save();
 for(const e of own.filter(e=>e.polygon)){c.globalAlpha=alpha*(e.void?.35:.30);c.beginPath();e.polygon.map(p=>this.worldToScreen(p)).forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.strokeStyle='#788d9b';c.lineWidth=1;if(e.void)c.setLineDash([5,5]);else{c.fillStyle=colors[e.role]||'#ddd';c.fill();}c.stroke();c.setLineDash([]);}
 c.globalAlpha=alpha;for(const e of own.filter(e=>e.a)){const a=this.worldToScreen(e.a),b=this.worldToScreen(e.b);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.lineWidth=Math.max(1,e.thickness*50*this.scale);c.strokeStyle='#937043';c.stroke();}c.restore();};
const box=ConstructionRenderer3D.prototype.box,wall=ConstructionRenderer3D.prototype.wall;
ConstructionRenderer3D.prototype.box=function(e,l,a){if(e.generator!==B.TAG||!e.polygon)return box.call(this,e,l,a);const bottom=e.polygon.map(p=>this.project(p.x,p.y,e.zBase)),top=e.polygon.map(p=>this.project(p.x,p.y,e.zBase+e.height));if(e.void){const c=this.ctx;c.save();c.globalAlpha=a*.5;c.strokeStyle='#8196a5';c.setLineDash([5,4]);for(const ps of [bottom,top]){c.beginPath();ps.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.stroke();}c.restore();return;}for(let i=0;i<bottom.length;i++){let j=(i+1)%bottom.length;this.polygon([bottom[i],bottom[j],top[j],top[i]],colors[e.role]||'#ccc','#697c86',a);}this.polygon(top,colors[e.role]||'#ccc','#697c86',a);};
ConstructionRenderer3D.prototype.wall=function(e,l,a){const orig=this.polygon,palette={concrete:'#a7afb6',brick:'#c08d79',block:'#b2b4af',timber:'#bd9b69'},fill=e.generator===B.TAG?'#ad8654':palette[e.materialSpec?.type];if(fill)this.polygon=function(ps,color,stroke,alpha){return orig.call(this,ps,fill,stroke,alpha);};try{return wall.call(this,e,e.generator===B.TAG?{...l,elevation:e.zBase}:l,a);}finally{this.polygon=orig;}};
function stories(){const ids=G.foundationIds(app.model);return app.model.levels.filter(l=>!l.autoFloor&&!ids.has(l.id)&&l.id!=='roof'&&!/^toiture$/i.test(l.name||'')).sort((a,b)=>a.elevation-b.elevation);}
function row(label,k,value,type='number',options=[],scope='floor'){const attr='data-b-'+scope+'="'+k+'"';return '<label class="b-row"><span>'+esc(label)+'</span>'+(type==='select'?'<select '+attr+'>'+options.map(([v,n])=>'<option value="'+esc(v)+'"'+(String(v)===String(value)?' selected':'')+'>'+esc(n)+'</option>').join('')+'</select>':'<input '+attr+' type="'+type+'" '+(type==='checkbox'?(value?'checked':''):'value="'+esc(value??'')+'"')+(type==='number'?' step="any"':'')+'>')+'</label>';}
function validDraft(){for(const p of Object.values(draft.materials)){if(!(Number(p.core)>0&&Number(p.core)<=3000)||['inside','outside','insulation','waste'].some(k=>p[k]!==null&&(!(Number(p[k])>=0)||Number(p[k])>3000))){alert('Composition invalide : vérifier les épaisseurs positives.');return false;}if(p.type==='timber'&&(!(p.studWidth>0)||!(p.studSpacing>=p.studWidth)||p.rails<0)){alert('Ossature : vérifier largeur, entraxe et lisses.');return false;}}for(const f of draft.floors){for(const k of ['insulationThickness','ravoirage','screed','panel','finishThickness','ceilingThickness'])if(f[k]!==null&&(!(Number(f[k])>=0)||Number(f[k])>1000)){alert('Épaisseur invalide : '+k);return false;}}return true;}
function current(){return draft.floors.find(f=>f.id===floorId);}
function levelOptions(){return stories().map(l=>[l.id,l.name]);}
function switchTab(t){tab=t;document.querySelectorAll('[data-b-tab]').forEach(b=>b.classList.toggle('active',b.dataset.bTab===t));document.querySelectorAll('[data-b-page]').forEach(p=>p.hidden=p.dataset.bPage!==t);preview();}
function renderMaterials(){const p=draft.materials[levelId]||B.material();draft.materials[levelId]=p;
 $('#bMaterials').innerHTML=row('Niveau','levelId',levelId,'select',levelOptions(),'level')+row('Hauteur des murs de ce niveau (m)','height',app.model.levels.find(l=>l.id===levelId)?.height,'number',[],'story')+row('Matériau des murs','type',p.type,'select',[['unknown','Non renseigné'],['concrete','Béton'],['brick','Brique'],['block','Parpaing'],['timber','Ossature bois']], 'material')+
 '<p class="b-muted">Composition de métré, pas épaisseur porteuse calculée. Les valeurs sont des exemples modifiables. Chaque étage conserve sa composition propre.</p>'+[['Cœur porteur (mm)','core'],['Isolation rapportée (mm)','insulation'],['Parement intérieur (mm)','inside'],['Parement extérieur (mm)','outside'],['Unités de maçonnerie par m² — fiche produit','rate'],['Largeur montants bois (mm)','studWidth'],['Entraxe montants bois (mm)','studSpacing'],['Nombre de lisses horizontales','rails'],['Pertes maçonnerie (%)','waste']].map(([l,k])=>row(l,k,p[k],'number',[],'material')).join('')+row('Référence produit / étude','reference',p.reference,'text',[],'material')+
 '<div class="b-result" id="bWallThickness"></div><button type="button" id="bApplyMaterial">Appliquer la composition aux murs de ce niveau</button><p class="b-muted">Cette action concerne les murs extérieurs, porteurs et cloisons du niveau choisi. Les autres niveaux ne changent pas. Les prochains murs reprennent cette composition.</p>';
 $('#bMaterials [data-b-story]').onchange=e=>{const height=Number(e.target.value);if(!(height>.1&&height<30)){alert('Hauteur de niveau invalide.');return;}app.model.commit();app.model.levels.find(l=>l.id===levelId).height=height;for(const wall of app.model.elements)if(wall.levelId===levelId&&['wallExterior','wallBearing','partition'].includes(wall.type))wall.height=height;refresh();preview();};
 $('#bMaterials [data-b-level]').onchange=e=>{levelId=e.target.value;renderMaterials();};
 $('#bMaterials').querySelectorAll('[data-b-material]').forEach(el=>el.addEventListener(el.type==='number'?'input':'change',()=>{p[el.dataset.bMaterial]=el.type==='number'?(el.value===''?null:Number(el.value)):el.value;$('#bWallThickness').textContent='Épaisseur composée : '+fmt((Number(p.core)+Number(p.insulation)+Number(p.inside)+Number(p.outside))/10,1)+' cm';}));
 $('#bWallThickness').textContent='Épaisseur composée : '+fmt((Number(p.core)+Number(p.insulation)+Number(p.inside)+Number(p.outside))/10,1)+' cm';
 $('#bApplyMaterial').onclick=()=>{if(!(p.core>0)||['inside','outside','insulation','waste'].some(k=>Number(p[k])<0)){alert('Vérifiez les épaisseurs et quantités positives.');return;}app.model.commit();app.model.buildingDesign=B.settings(draft);for(const e of app.model.elements)if(e.levelId===levelId)assign(e,app.model);if(levelId===app.model.activeLevelId)for(const type of ['wallExterior','wallBearing','partition'])app.toolSettings[type].thickness=(Number(p.core)+Number(p.insulation)+Number(p.inside)+Number(p.outside))/1000;refresh();preview();};
}
function addFloor(){const ls=stories(),active=ls.find(l=>l.id===app.model.activeLevelId),upper=active&&ls.indexOf(active)>0?active:ls[1];if(!upper){alert('Ajoutez d’abord un étage au-dessus du RDC.');return;}const lower=ls[ls.indexOf(upper)-1];let f=draft.floors.find(f=>f.aboveId===upper.id);if(!f){f=B.config(S,lower,upper);draft.floors.push(f);}floorId=f.id;renderFloor();switchTab('floors');}
function renderFloor(){const f=current();$('#bFloorList').innerHTML=draft.floors.map(f=>'<option value="'+esc(f.id)+'">'+esc(f.name)+'</option>').join('');$('#bFloorList').value=floorId;
 if(!f){$('#bFloorFields').innerHTML='<p>Ajoutez un plancher : il deviendra un niveau distinct dans la barre principale.</p>';$('#bTechnical').innerHTML='<p>Ajoutez d’abord un plancher.</p>';return;}
 $('#bFloorFields').innerHTML=row('Nom du plancher-niveau','name',f.name,'text')+row('Activer le niveau lié','enabled',f.enabled,'checkbox')+row('Niveau inférieur — murs/appuis','belowId',f.belowId,'select',levelOptions())+row('Niveau supérieur — sol fini','aboveId',f.aboveId,'select',levelOptions())+row('Système','system',f.system,'select',[['wood','Solivage bois calculé en préétude'],['concrete','Dalle béton portée — épaisseur prescrite']])+
 '<p class="b-muted">La dalle est un niveau structurel, pas un étage habitable. Les murs/appuis du dessous pilotent son emprise. Les niveaux voisins fixent l’espace disponible ; un manque de hauteur est signalé, jamais comblé en réduisant une section.</p>'+
 (f.system==='wood'?row('Entraxe maximal des solives (m)','spacing',f.spacing)+row('Inverser le sens de portée','invert',f.invert,'checkbox')+row('Bois du scénario','grade',f.grade,'select',[['unknown','À confirmer'],['C24','Bois massif C24']])+row('Classe de service','service',f.service,'select',[[1,'1 — intérieur sec'],[2,'2 — plus humide']])+row('Maintien latéral prévu','restraint',f.restraint,'checkbox')+row('Charges du scénario confirmées','loadsConfirmed',f.loadsConfirmed,'checkbox')+row('Reprise sur les solives','transfer',f.transfer,'select',[['unknown','À déterminer'],['none','Plancher seul — aucun porteur repris'],['bearing','Mur/poteau à reprendre : étude nécessaire']]):row('Béton : épaisseur issue de l’étude (mm)','slabThickness',f.slabThickness))+
 '<details><summary>Composition complète et charges — de bas en haut</summary>'+[['Plafond sous-face (mm)','ceilingThickness'],['Panneau bois (mm)','panel'],['Masse volumique panneau (kg/m³)','panelDensity'],['Isolation rapportée (mm)','insulationThickness'],['Densité isolation (kg/m³)','insulationDensity'],['Ravoirage distinct (mm)','ravoirage'],['Densité ravoirage (kg/m³)','ravoirageDensity'],['Chape (mm)','screed'],['Densité chape (kg/m³)','screedDensity'],['Revêtement (mm)','finishThickness'],['Revêtements : charge (kN/m²)','finishes'],['Plafond : charge (kN/m²)','ceiling'],['Isolation entre solives : charge (kN/m²)','insulation'],['Cloisons légères (kN/m²)','partitions'],['Exploitation Q (kN/m²)','q'],['Charge ponctuelle P (kN)','p'],['Objectif hauteur libre (m)','clearHeight']].map(([l,k])=>row(l,k,f[k])).join('')+row('Montrer toutes les couches','showAllLayers',f.showAllLayers,'checkbox')+'</details>';
 $('#bFloorFields').querySelectorAll('[data-b-floor]').forEach(el=>el.addEventListener(el.type==='number'?'input':'change',()=>{f[el.dataset.bFloor]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;if(el.dataset.bFloor==='system')renderFloor();preview();}));
 renderTechnical();preview();
}
function renderTechnical(){const f=current();if(!f)return;f.technical={...B.technical(),...f.technical};const t=f.technical;
 if(!t.networks.length)t.networks=[['electricite',20],['eau',20],['evacuation',100],['ventilation',125]].map(([kind,diameter])=>({kind,enabled:false,diameter,insulation:0,slope:null,length:null}));
 $('#bTechnical').innerHTML='<p class="b-notice"><b>Aucune hauteur universelle de plénum ou de gaine.</b> Le minimum dépend des réseaux, des accessoires, de la pose, du feu/acoustique et des prescriptions applicables. Les valeurs de diamètre ci-dessous sont des exemples, pas un dimensionnement de réseau.</p>'+row('Emplacement des réseaux','location',t.location,'select',[['plenum','Vide sous la structure (plénum)'],['ravoirage','Ravoirage au-dessus de la structure'],['chape','Chape rapportée — incorporation à refuser'],['structure','Dans la structure — étude spécifique']], 'technical')+row('Réseaux superposés / croisements','stacked',t.stacked,'checkbox',[],'technical')+row('Dégagement global prescrit (mm)','clearance',t.clearance,'number',[],'technical')+row('Hauteur minimale prescrite du système (mm)','prescribed',t.prescribed,'number',[],'technical')+row('Référence de la prescription','reference',t.reference,'text',[],'technical')+row('Présence de gaz — étude spécifique','gas',t.gas,'checkbox',[],'technical')+
 t.networks.map((n,i)=>'<fieldset><legend>'+esc(n.kind)+'</legend>'+row('Réseau présent','enabled',n.enabled,'checkbox',[],i)+row('Diamètre extérieur / gaine (mm)','diameter',n.diameter,'number',[],i)+row('Isolation radiale (mm)','insulation',n.insulation,'number',[],i)+(n.kind==='evacuation'?row('Pente prescrite (%)','slope',n.slope,'number',[],i)+row('Longueur du parcours en pente (m)','length',n.length,'number',[],i):'')+'</fieldset>').join('')+
 '<p class="b-muted">Pas de perçage automatique de solive, ni de réservation structurelle réputée conforme. L’encombrement ne couvre pas les espacements horizontaux, raccords, accès, rayons de courbure et compartimentages incendie.</p><div id="bTechResult"></div><details><summary>Repères vérifiés — domaines distincts</summary><p>ETEL du logement : repère 600 mm × 250 mm, du sol au plafond. Ce n’est pas une hauteur de vide horizontal.</p><p>Gaz en vide sanitaire de maison individuelle : les conditions d’accès (repère 0,60 m), de ventilation et de parcours sont spécifiques. Le repère n’est pas transposé au plénum ni aux ERP.</p><p><a href="https://www.legrand.fr/pro/normes-et-reglementations/norme-nf-c-15-100/norme-nf-c-15-100-suivez-le-guide" target="_blank" rel="noopener">Legrand — ETEL</a> · <a href="https://cegibat.grdf.fr/reponse-expert/maison-individuelle-canalisation-gaz-vide-sanitaire" target="_blank" rel="noopener">GRDF — vide sanitaire habitation</a> · <a href="https://www.infociments.fr/batiment/dossier-technique-chapes-et-carrelage-chapes-incorporations-et-chapes-traditionnelles-base-de-liants-hydrauliques-5" target="_blank" rel="noopener">Ravoirage et DTU 26.2</a></p><p>Références consultées le 23 septembre 2026 ; clauses complètes, prescriptions fabricant et applicabilité au projet à vérifier.</p></details>';
 $('#bTechnical').querySelectorAll('input,select').forEach(el=>el.addEventListener(el.type==='number'?'input':'change',()=>{const a=[...el.attributes].find(a=>a.name.startsWith('data-b-'));if(!a)return;const scope=a.name.slice(7),obj=scope==='technical'?t:t.networks[Number(scope)];obj[a.value]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;preview();}));
}
function draftModel(){return {...app.model,buildingDesign:draft};}
function preview(){if(!draft)return;const m=draftModel(),r=B.report(m,G,S,F),f=current(),fr=r.floors.find(r=>r.config.id===f?.id);
 if(fr){$('#bFloorResult').innerHTML='<div class="b-result"><b>'+esc(fr.config.name)+'</b><br>Arase des murs inférieurs : '+fmt(fr.sourceTop)+' m · départ du niveau supérieur : '+fmt(fr.top)+' m.<br>Épaisseur disponible au-dessus des appuis : '+fmt(fr.available*100,1)+' cm.<br>Composition nécessaire au-dessus des appuis : '+fmt(fr.required*100,1)+' cm.<br>Enveloppe totale avec plafond/vide : '+fmt(fr.totalThickness*100,1)+' cm.<br>Hauteur libre restante dessous : '+fmt(fr.clearHeight)+' m.'+(fr.section?'<br>Section commune d’essai : <b>'+fr.section.b+' × '+fr.section.h+' mm</b> · '+fr.count+' solives tracées.':'')+'<br>Emprise calculée : '+fmt(fr.area)+' m².<br><b>PRÉÉTUDE, PAS VALIDATION POUR CONSTRUIRE</b></div>'+fr.issues.map(i=>'<p class="'+(i.severity==='error'?'b-error':'b-muted')+'">'+esc(i.text)+'</p>').join('')+'<div class="b-stack">'+fr.layers.map(l=>'<div>'+esc(l.name)+' : '+fmt(l.h*1000,0)+' mm · sous-face '+fmt(l.z)+' m</div>').join('')+'</div>';
 if($('#bTechResult')){const t=fr.technical||B.techReport(f.technical);$('#bTechResult').innerHTML='<div class="b-result">Encombrement géométrique : '+fmt(t.geometric,0)+' mm.<br>Réservation selon données connues : '+fmt(t.required,0)+' mm.<br><b>'+(t.complete?'Prescriptions saisies — applicabilité à vérifier':'Minimum complet indéterminé')+'</b></div>'+t.issues.map(i=>'<p class="'+(i.severity==='error'?'b-error':'b-muted')+'">'+esc(i.text)+'</p>').join('');}
 }else $('#bFloorResult').innerHTML='<p>Aucun plancher actif.</p>';
 $('#bQuantities').innerHTML='<p class="b-notice">Métré brut estimatif. Les volumes de matériaux ne sont pas des capacités porteuses. Aucun dimensionnement automatique des murs, armatures ou fondations selon le seul matériau.</p><table><thead><tr><th>Niveau / poste</th><th>Matériau</th><th>Quantité</th></tr></thead><tbody>'+r.quantities.rows.map(x=>'<tr title="'+esc(x.note)+'"><td>'+esc(x.level)+'<small>'+esc(x.label)+'</small></td><td>'+esc(x.material)+'</td><td>'+fmt(x.quantity,x.unit==='unités'?1:3)+' '+esc(x.unit)+'</td></tr>').join('')+'</tbody></table>'+r.quantities.issues.map(s=>'<p class="b-muted">'+esc(s)+'</p>').join('');
}
function coordinate(){const f=current();if(!f)return;const m=draftModel(),r=B.floorReport(m,f,G,S);if(!Number.isFinite(r.requiredTop)||(f.system==='wood'&&!r.section)){alert('Complétez les hypothèses et la section avant de coordonner.');return;}const target=app.model.levels.find(l=>l.id===f.aboveId),oldElevation=target.elevation,delta=r.requiredTop-oldElevation;if(Math.abs(delta)<.0001)return;if(!confirm('Décaler le niveau supérieur et les niveaux au-dessus de '+fmt(delta)+' m ? Cela ne valide pas leur structure.'))return;app.model.commit();app.model.buildingDesign=B.settings(draft);for(const l of app.model.levels)if(!l.autoFloor&&l.elevation>=oldElevation-1e-8)l.elevation+=delta;refresh();preview();}
function open(t='materials'){draft=B.settings(app.model.buildingDesign);const ls=stories();levelId=ls.find(l=>l.id===app.model.activeLevelId)?.id||ls[0]?.id||'';floorId=draft.floors.find(f=>f.id===app.model.activeLevelId||f.aboveId===app.model.activeLevelId)?.id||draft.floors[0]?.id||'';renderMaterials();renderFloor();switchTab(t);$('#bDialog').showModal();}
function init(){const style=document.createElement('style');style.textContent=`#bDialog{width:min(610px,95vw);max-height:92vh;overflow:auto}#bForm{display:block;padding:15px}#bForm h3{margin:0 0 10px;font-size:17px}#bForm p{font-size:12px;line-height:1.5}#bForm [hidden]{display:none!important}.b-row{display:grid!important;grid-template-columns:1fr minmax(115px,42%);align-items:center;gap:9px;font-size:12px;margin:9px 0}#bForm input:not([type=checkbox]),#bForm select{width:100%;min-width:0;padding:6px;border:1px solid #cbd6de;border-radius:5px;background:#fff}#bForm input[type=checkbox]{justify-self:start}.b-tabs{display:flex;flex-wrap:wrap;gap:5px;position:sticky;top:-15px;background:white;padding:8px 0;z-index:3}.b-tabs button{font-size:11px}.b-notice{background:#fff7e6;border-left:3px solid #b88932;padding:9px;color:#73541e;font-size:12px}.b-result{background:#edf4f8;border:1px solid #d2e0e8;border-radius:6px;padding:9px;line-height:1.6;font-size:12px;margin:9px 0}.b-muted{color:#627682;font-size:11px!important}.b-error{color:#a43824;font-weight:600}#bForm details{margin:12px 0;border-top:1px solid #dde5eb;padding-top:8px}#bForm summary{cursor:pointer;font-size:12px;font-weight:700}.b-actions{position:sticky;bottom:-15px;display:flex;gap:7px;justify-content:flex-end;background:#fff;border-top:1px solid #dce4eb;padding:12px 15px;margin:12px -15px -15px}.b-actions button{font-size:12px}#bSave{background:#245c7d;color:#fff}#bForm table{width:100%;font-size:11px;border-collapse:collapse}#bForm th,#bForm td{text-align:left;border-bottom:1px solid #e0e7ec;padding:7px}#bForm td small{display:block;color:#72838e}#bForm fieldset{border:1px solid #dce4ea;border-radius:7px;margin:12px 0}#bForm legend{font-size:12px;font-weight:700}.b-stack{font-size:11px;line-height:1.7;padding:8px;background:#f6f8fa}.b-card{padding:8px 0;border-bottom:1px solid #dce3e9}.b-card button{width:100%;font-size:12px;margin-bottom:5px}.b-card small{font-size:10px;color:#607583;display:block}`;document.head.appendChild(style);
 const card=document.createElement('div');card.className='b-card';card.innerHTML='<button id="bOpenFloors">▤ Planchers-niveaux auto</button><button id="bOpenMaterials">Matériaux & métré</button><small>Dalles, chapes, solives et vides techniques</small>';$('.mode-title').after(card);
 const dlg=document.createElement('dialog');dlg.id='bDialog';dlg.innerHTML='<form id="bForm"><h3>Bâtiment · compositions et niveaux structurels</h3><div class="b-tabs"><button type="button" data-b-tab="materials">Murs / matériaux</button><button type="button" data-b-tab="floors">Planchers-niveaux</button><button type="button" data-b-tab="technical">Gaines / vides</button><button type="button" data-b-tab="quantities">Métré</button></div><section data-b-page="materials" id="bMaterials"></section><section data-b-page="floors"><select id="bFloorList" aria-label="Plancher"></select><p><button type="button" id="bAddFloor">+ Plancher entre deux niveaux</button> <button type="button" id="bCoordinate">Coordonner les altitudes</button></p><div id="bFloorFields"></div><div id="bFloorResult" role="status"></div></section><section data-b-page="technical" id="bTechnical"></section><section data-b-page="quantities" id="bQuantities"></section><p class="b-muted"><a href="docs/BATIMENT.md" target="_blank" rel="noopener">Méthode, limites et références</a></p><div class="b-actions"><button type="button" id="bCancel">Fermer</button><button type="submit" id="bSave">Appliquer au projet</button></div></form>';document.body.appendChild(dlg);
 $('#bOpenFloors').onclick=()=>open('floors');$('#bOpenMaterials').onclick=()=>open('materials');$('#bCancel').onclick=()=>dlg.close();$('#bAddFloor').onclick=addFloor;$('#bCoordinate').onclick=coordinate;$('#bFloorList').onchange=e=>{floorId=e.target.value;renderFloor();};document.querySelectorAll('[data-b-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.bTab));
 $('#bForm').onsubmit=e=>{e.preventDefault();if(!validDraft())return;app.model.commit();app.model.buildingDesign=B.settings(draft);refresh();const f=current();if(f?.enabled&&app.model.levels.some(l=>l.id===f.id)&&['floors','technical'].includes(tab)){app.model.activeLevelId=f.id;$('#levelSelect').value=f.id;$('#levelSelect').dispatchEvent(new Event('change',{bubbles:true}));}dlg.close();refresh();};
 $('.version').textContent='v0.9';document.title='Plan Bâtiment Pro — v0.9';ready=true;window.PBPBuildingReady=true;refresh();}
window.PBPBuildingUI={open,refresh,getReport:()=>clone(calculate())};if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();})();
