/* Plan Bâtiment Pro v0.12.0 — second œuvre / insulation UI and dedicated 2D trace. */
(function(){'use strict';
const app=planApp,E=PBPEnvelope,$=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v));let draft=null,currentId='',ready=false;
const P=ProjectModel.prototype,oldSnap=P.snapshot,oldRestore=P.restore;P.snapshot=function(){const d=JSON.parse(oldSnap.call(this));d.envelopeDesign=E.settings(this.envelopeDesign);return JSON.stringify(d);};P.restore=function(t){const d=JSON.parse(t);oldRestore.call(this,t);this.envelopeDesign=E.settings(d.envelopeDesign);};
function report(){return E.report(app.model);}
function refresh(){app.renderer2d?.draw();app.renderer3d?.draw();window.PBPAutonomyUI?.refresh?.();}
function hosts(level){return (app.model.elements||[]).filter(e=>e.levelId===level&&e.a&&e.b&&['wallExterior','wallBearing','partition'].includes(e.type)&&!e.generator);}
function uid(){return 'env:'+Math.random().toString(36).slice(2,10);}
function row(label,id,type='number'){return '<label class="env-row"><span>'+label+'</span><input id="'+id+'" type="'+type+'" step="any"></label>';}
function selectHtml(id,label,items){return '<label class="env-row"><span>'+label+'</span><select id="'+id+'">'+items.map(x=>'<option value="'+x[0]+'">'+x[1]+'</option>').join('')+'</select></label>';}
function renderForm(){
 const levels=(app.model.levels||[]).filter(l=>!l.autoFloor&&l.id!=='foundations'&&l.id!=='roof'),a=draft||E.assemblyDefaults();
 $('#envLevel').innerHTML=levels.map(l=>'<option value="'+l.id+'">'+l.name+'</option>').join('');$('#envLevel').value=a.levelId||app.model.activeLevelId;
 renderHosts();
 for(const [id,key] of [['envKind','kind'],['envSide','side'],['envSpacing','studSpacing'],['envStudW','studWidth'],['envStudD','studDepth'],['envBoardW','boardWidth'],['envBoardH','boardHeight'],['envBoardT','boardThickness'],['envBoardsIn','boardsInside'],['envBoardsOut','boardsOutside'],['envWaste','waste'],['envInsIn','insulationInside'],['envLamIn','lambdaInside'],['envInsOut','insulationOutside'],['envLamOut','lambdaOutside'],['envRw','acousticRw'],['envAcRef','acousticReference'],['envSysRef','systemReference']]){const el=$('#'+id);if(!el)continue;el.value=a[key]??'';}
 $('#envDouble').checked=!!a.doubleStud;preview();
}
function renderHosts(){const level=$('#envLevel').value||draft?.levelId||app.model.activeLevelId,hs=hosts(level);$('#envHost').innerHTML=hs.map(h=>'<option value="'+h.id+'">'+({wallExterior:'Mur extérieur',wallBearing:'Mur porteur',partition:'Cloison'})[h.type]+' · '+Math.hypot(h.b.x-h.a.x,h.b.y-h.a.y).toFixed(2)+' m</option>').join('');if(draft?.hostId&&hs.some(h=>h.id===draft.hostId))$('#envHost').value=draft.hostId;}
function read(){const a={...(draft||E.assemblyDefaults()),id:currentId||draft?.id||uid(),levelId:$('#envLevel').value,hostId:$('#envHost').value,kind:$('#envKind').value,side:Number($('#envSide').value),doubleStud:$('#envDouble').checked};for(const [id,key] of [['envSpacing','studSpacing'],['envStudW','studWidth'],['envStudD','studDepth'],['envBoardW','boardWidth'],['envBoardH','boardHeight'],['envBoardT','boardThickness'],['envBoardsIn','boardsInside'],['envBoardsOut','boardsOutside'],['envWaste','waste'],['envInsIn','insulationInside'],['envLamIn','lambdaInside'],['envInsOut','insulationOutside'],['envLamOut','lambdaOutside'],['envRw','acousticRw']]){const el=$('#'+id);a[key]=el.value===''?null:Number(el.value);}a.acousticReference=$('#envAcRef').value;a.systemReference=$('#envSysRef').value;return E.normalize(a);}
function preview(){if(!ready)return;draft=read();const q=E.quantity(app.model,draft),box=$('#envResult');if(!q.host){box.textContent='Choisissez un mur support.';return;}box.innerHTML='<b>'+q.L.toFixed(2)+' m × '+q.H.toFixed(2)+' m</b> · surface nette '+q.netArea.toFixed(2)+' m²'+(q.openingArea>0?' · ouvertures déduites '+q.openingArea.toFixed(2)+' m²':'')+'<br>Montants : <b>'+q.studs+'</b> ('+q.studBase+' courants + '+q.jambStuds+' de tableaux'+(draft.doubleStud?', doublés':'')+') · longueur '+q.studLength.toFixed(2)+' m<br>Rails : <b>'+q.rails.toFixed(2)+' m</b> (haut '+q.railsTop.toFixed(2)+' + bas '+q.railsBottom.toFixed(2)+') · plaques : <b>'+q.boards+'</b> ('+q.boardsInside+' int. / '+q.boardsOutside+' ext.)<br>Isolant : '+q.insulationArea.toFixed(2)+' m² · '+q.insulationVolume.toFixed(3)+' m³ · R isolant = <b>'+q.thermalR.toFixed(2)+' m².K/W</b>'+(draft.acousticRw!=null?'<br>Performance acoustique déclarée : '+draft.acousticRw+' dB':'')+q.issues.map(i=>'<p class="'+(i.severity==='error'?'env-error':'env-muted')+'">'+i.text+'</p>').join('');}
function saveOne(){draft=read();if(!draft.hostId)return;app.model.commit();const s=E.settings(app.model.envelopeDesign),i=s.assemblies.findIndex(x=>x.id===draft.id);if(i>=0)s.assemblies[i]=draft;else s.assemblies.push(draft);app.model.envelopeDesign=s;currentId=draft.id;refresh();renderList();}
function applyLevel(){draft=read();const hs=hosts(draft.levelId).filter(h=>draft.kind==='partition'?h.type==='partition':h.type==='wallExterior');if(!hs.length)return;app.model.commit();const s=E.settings(app.model.envelopeDesign);for(const h of hs){let a={...draft,id:uid(),hostId:h.id};const old=s.assemblies.findIndex(x=>x.levelId===a.levelId&&x.hostId===h.id&&x.kind===a.kind);if(old>=0){a.id=s.assemblies[old].id;s.assemblies[old]=a;}else s.assemblies.push(a);}app.model.envelopeDesign=s;refresh();renderList();}
function renderList(){const s=E.settings(app.model.envelopeDesign),list=$('#envList');list.innerHTML=s.assemblies.length?s.assemblies.map(a=>{const h=(app.model.elements||[]).find(e=>e.id===a.hostId),q=E.quantity(app.model,a);return '<button type="button" data-env-id="'+a.id+'">'+({iti:'ITI',ite:'ITE',mixed:'ITI+ITE',acoustic:'Acoustique',partition:'Cloison Placoplatre'})[a.kind]+' · '+(h?Math.hypot(h.b.x-h.a.x,h.b.y-h.a.y).toFixed(2)+' m':'support absent')+' · '+q.studs+' montants</button>';}).join(''):'<p class="env-muted">Aucune paroi de second œuvre.</p>';list.querySelectorAll('[data-env-id]').forEach(b=>b.onclick=()=>{const a=s.assemblies.find(x=>x.id===b.dataset.envId);currentId=a.id;draft=clone(a);renderForm();});}
function remove(){if(!currentId)return;app.model.commit();const s=E.settings(app.model.envelopeDesign);s.assemblies=s.assemblies.filter(a=>a.id!==currentId);app.model.envelopeDesign=s;currentId='';draft=E.assemblyDefaults();refresh();renderList();renderForm();}
function drawEnvelope(renderer){
 const r=report(),c=renderer.ctx;c.save();c.lineWidth=1.4;
 for(const q of r.rows){if(!q.host||q.assembly.levelId!==app.model.activeLevelId)continue;const a=q.assembly,h=q.host,A=renderer.worldToScreen(h.a),B=renderer.worldToScreen(h.b),dx=B.x-A.x,dy=B.y-A.y,L=Math.hypot(dx,dy);if(L<2)continue;const ux=dx/L,uy=dy/L,nx=-uy,ny=ux,kind=a.kind;
  if(kind==='partition'){const half=Math.max(5,(a.studDepth+q.layers.boardIn+q.layers.boardOut)*50*renderer.scale/2);c.strokeStyle='#70617c';c.setLineDash([]);for(const s of [-1,1]){c.beginPath();c.moveTo(A.x+nx*half*s,A.y+ny*half*s);c.lineTo(B.x+nx*half*s,B.y+ny*half*s);c.stroke();}c.strokeStyle='#9b6d9f';const spacing=Math.max(8,a.studSpacing*50*renderer.scale);for(let t=0;t<=L;t+=spacing){const x=A.x+ux*t,y=A.y+uy*t;c.beginPath();c.moveTo(x-nx*half,y-ny*half);c.lineTo(x+nx*half,y+ny*half);c.stroke();}}
  else{const off=(Number(h.thickness)||.2)*25*renderer.scale*a.side+(kind==='ite'?-1:1)*7;c.strokeStyle=kind==='ite'?'#568456':kind==='acoustic'?'#9a5793':'#3d78a0';c.setLineDash(kind==='acoustic'?[8,3,2,3]:[7,4]);c.beginPath();c.moveTo(A.x+nx*off,A.y+ny*off);c.lineTo(B.x+nx*off,B.y+ny*off);c.stroke();c.setLineDash([]);if(['iti','mixed','acoustic'].includes(kind)){const step=Math.max(8,a.studSpacing*50*renderer.scale);c.strokeStyle=kind==='acoustic'?'#9a5793':'#3d78a0';for(let t=0;t<=L+.1;t+=step){const x=A.x+ux*Math.min(t,L)+nx*off,y=A.y+uy*Math.min(t,L)+ny*off;c.beginPath();c.moveTo(x-nx*4,y-ny*4);c.lineTo(x+nx*4,y+ny*4);c.stroke();}}else{for(let t=6;t<L;t+=14){const x=A.x+ux*t+nx*off,y=A.y+uy*t+ny*off;c.beginPath();c.moveTo(x-nx*3,y-ny*3);c.lineTo(x+nx*3,y+ny*3);c.stroke();}}}
 }
 c.restore();
}
function init(){
 const style=document.createElement('style');style.textContent='.env-card{padding:8px 0;border-bottom:1px solid #e0e7eb}.env-card button{width:100%;font-size:12px}.env-card small{font-size:10px;color:#657985;display:block;margin-top:4px}#envDialog{width:min(650px,95vw);max-height:92vh;overflow:auto}#envForm{display:block;padding:15px}.env-row{display:grid!important;grid-template-columns:1fr minmax(150px,43%);gap:8px;align-items:center;margin:8px 0;font-size:12px}.env-row input,.env-row select{width:100%;padding:6px;border:1px solid #ccd8df;border-radius:5px;background:white}.env-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.env-result{background:#eef5f8;border:1px solid #d0e0e8;border-radius:7px;padding:9px;font-size:12px;line-height:1.6}.env-muted{color:#647985;font-size:11px}.env-error{color:#9b382a;font-weight:600}.env-actions{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.env-actions button{font-size:11px}#envList{display:grid;gap:4px}#envList button{text-align:left;font-size:11px}.env-save{background:#245c7d;color:white}';document.head.appendChild(style);
 const card=document.createElement('div');card.className='env-card';card.innerHTML='<button id="envOpen">▥ Second œuvre / Isolation</button><small>ITI · ITE · acoustique · plaques · montants</small>';$('.mode-title').after(card);
 const d=document.createElement('dialog');d.id='envDialog';d.innerHTML='<form id="envForm" onsubmit="return false"><h3>Parois de second œuvre et isolation</h3>'+selectHtml('envLevel','Niveau',[])+selectHtml('envHost','Mur support',[])+selectHtml('envKind','Type',[['iti','Doublage thermique intérieur (ITI)'],['ite','Isolation thermique extérieure (ITE)'],['mixed','Isolation intérieure + extérieure'],['acoustic','Contre-cloison acoustique'],['partition','Cloison plaques de plâtre isolée']])+selectHtml('envSide','Côté du support',[['1','Côté A'],['-1','Côté B']])+'<div class="env-grid">'+row('Entraxe montants (m)','envSpacing')+row('Largeur montant (m)','envStudW')+row('Profondeur montant (m)','envStudD')+row('Largeur plaque (m)','envBoardW')+row('Hauteur plaque (m)','envBoardH')+row('Épaisseur plaque (m)','envBoardT')+row('Plaques côté intérieur','envBoardsIn')+row('Plaques côté extérieur','envBoardsOut')+row('Pertes / chutes (0,08 = 8%)','envWaste')+row('Isolant intérieur (m)','envInsIn')+row('Lambda intérieur W/m.K','envLamIn')+row('Isolant extérieur (m)','envInsOut')+row('Lambda extérieur W/m.K','envLamOut')+row('Rw/RA déclaré (dB)','envRw')+'</div><label class="env-row"><span>Montants doublés</span><input id="envDouble" type="checkbox"></label>'+row('Référence acoustique','envAcRef','text')+row('Référence système / fabricant','envSysRef','text')+'<div id="envResult" class="env-result"></div><div class="env-actions"><button type="button" id="envSave" class="env-save">Ajouter / mettre à jour</button><button type="button" id="envLevelAll">Appliquer à tout le niveau</button><button type="button" id="envDelete">Supprimer</button><button type="button" id="envClose">Fermer</button></div><h4>Parois du projet</h4><div id="envList"></div><p class="env-muted">Le tracé est volontairement différent d’un mur structurel : lignes fines/hachurées pour doublages et montants visibles pour cloisons sèches. Les quantités sont géométriques ; une performance acoustique certifiée doit provenir du système réel.</p></form>';document.body.appendChild(d);
 $('#envOpen').onclick=()=>{const s=E.settings(app.model.envelopeDesign);currentId='';draft={...E.assemblyDefaults(),levelId:app.model.activeLevelId};ready=true;renderForm();renderList();d.showModal();};$('#envClose').onclick=()=>d.close();$('#envSave').onclick=saveOne;$('#envLevelAll').onclick=applyLevel;$('#envDelete').onclick=remove;$('#envLevel').onchange=()=>{renderHosts();preview();};$('#envHost').onchange=preview;$('#envForm').addEventListener('input',preview);$('#envForm').addEventListener('change',preview);
 const base=PlanRenderer2D.prototype.draw;PlanRenderer2D.prototype.draw=function(...args){const m=this.app.model,r=report(),hidden=new Set(r.hiddenHostIds||[]),original=m.elements;try{m.elements=original.filter(e=>!hidden.has(e.id));const out=base.apply(this,args);drawEnvelope(this);return out;}finally{m.elements=original;}};
 $('.version').textContent='v0.12.0';document.title='Plan Bâtiment Pro — v0.12.0';window.PBPEnvelopeUIReady=true;ready=true;refresh();
}
window.PBPEnvelopeUI={getReport:()=>clone(report()),refresh,open:()=>$('#envOpen')?.click()};if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();
