/* Geometry tools: constrained wall translation, closed faces, 3D levels. */
(function(root){'use strict';
const EPS=.004,sub=(a,b)=>({x:a.x-b.x,y:a.y-b.y}),add=(a,b)=>({x:a.x+b.x,y:a.y+b.y}),dot=(a,b)=>a.x*b.x+a.y*b.y,cross=(a,b)=>a.x*b.y-a.y*b.x,len=a=>Math.hypot(a.x,a.y),dist=(a,b)=>len(sub(a,b));
const point=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y),copy=e=>({id:e.id,a:{...e.a},b:{...e.b}}),types=new Set(['wallExterior','wallBearing','partition','foundation','beam']);
const wall=e=>e&&e.mode==='construction'&&!e.generator&&!e.locked&&types.has(e.type)&&point(e.a)&&point(e.b)&&dist(e.a,e.b)>.001;
const area=p=>p.reduce((s,a,i)=>s+cross(a,p[(i+1)%p.length]),0)/2;
function dragPlan(elements,w){if(!wall(w))return null;const s=copy(w),v=sub(s.b,s.a),L=len(v),u={x:v.x/L,y:v.y/L},n={x:-u.y,y:u.x},refs=[],originals=[s];
 for(const e of elements){if(e.id===s.id||e.levelId!==w.levelId||!wall(e))continue;let touched=false;
 for(const end of ['a','b']){const p=e[end],t=dot(sub(p,s.a),u)/L;if(t>=-EPS/L&&t<=1+EPS/L&&dist(p,add(s.a,{x:u.x*t*L,y:u.y*t*L}))<=EPS){refs.push({id:e.id,end,anchor:dist(p,s.a)<=EPS?'a':dist(p,s.b)<=EPS?'b':'inside',p:{...p},a:{...e.a},b:{...e.b}});touched=true;}}
 const ev=sub(e.b,e.a);for(const end of ['a','b']){const p=s[end],t=dot(sub(p,e.a),ev)/dot(ev,ev);if(t>EPS/len(ev)&&t<1-EPS/len(ev)&&dist(p,add(e.a,{x:ev.x*t,y:ev.y*t}))<=EPS)refs.push({id:e.id,end:null,anchor:end,p:{...p},a:{...e.a},b:{...e.b}});}if(touched)originals.push(copy(e));}
 return {selected:s,u,n,L,refs,originals};}
function slide(g,d){const fail=message=>({ok:false,message,updates:[]});if(!g||!point(d))return fail('Geste invalide.');if(!g.refs.length)return {ok:true,updates:[{id:g.selected.id,a:add(g.selected.a,d),b:add(g.selected.b,d)}]};
 const h=dot(d,g.n),t=dot(d,g.u),offset={x:g.n.x*h,y:g.n.y*h},a=add(g.selected.a,offset),b=add(g.selected.b,offset),targets={a:[],b:[]},refs=[];
 for(const r of g.refs){const v=sub(r.b,r.a),den=cross(g.u,v);let p;if(Math.abs(den)<1e-7*len(v)){if(Math.abs(h)>1e-7)return fail('Jonction colinéaire : utilisez un coin pour modifier cette liaison.');p=add(r.p,{x:g.u.x*t,y:g.u.y*t});}else{const k=cross(sub(r.a,a),v)/den;p=add(a,{x:g.u.x*k,y:g.u.y*k});}if(r.end===null){const k=dot(sub(p,r.a),v)/dot(v,v);if(k<0||k>1)return fail('Le coin sortirait de son appui.');}if(r.anchor!=='inside')targets[r.anchor].push(p);refs.push({...r,p});}
 for(const end of ['a','b'])if(targets[end].some(p=>dist(p,targets[end][0])>EPS))return fail('Plusieurs axes bloquent ce nœud ; aucun angle modifié.');
 const nextA=targets.a[0]||a,nextB=targets.b[0]||b,updates=new Map(g.originals.map(e=>[e.id,copy(e)]));updates.set(g.selected.id,{id:g.selected.id,a:nextA,b:nextB});const L=dot(sub(nextB,nextA),g.u);if(L<Math.min(.05,g.L)-1e-9)return fail('Mur trop court ou inversé.');
 for(const r of refs){if(r.anchor==='inside'){const k=dot(sub(r.p,nextA),g.u);if(k<-EPS||k>L+EPS)return fail('Une jonction sortirait du mur.');}if(r.end)updates.get(r.id)[r.end]=r.anchor==='a'?nextA:r.anchor==='b'?nextB:r.p;}
 for(const old of g.originals){const e=updates.get(old.id),v=sub(e.b,e.a),ov=sub(old.b,old.a);if(len(v)<Math.min(.05,len(ov))-1e-9||dot(v,ov)<=0||Math.abs(cross(v,ov))>EPS*len(ov))return fail('Le raccord serait inversé ou déformé.');}return {ok:true,updates:[...updates.values()]};}
function intersects(a,b){if(!a||!b)return false;for(const p of [a,b])for(let i=0;i<p.length;i++){const v=sub(p[(i+1)%p.length],p[i]),n={x:-v.y,y:v.x},L=len(n);if(L<EPS)continue;const aa=a.map(p=>dot(p,n)/L),bb=b.map(p=>dot(p,n)/L);if(Math.min(Math.max(...aa),Math.max(...bb))-Math.max(Math.min(...aa),Math.min(...bb))<=EPS)return false;}return true;}
function faces(model,source,S){const walls=model.elements.filter(e=>S.isSupport(e)&&e.levelId===source),out={faces:[],issues:[]};
 if(!walls.length||walls.length>180){out.issues.push('Nombre d’appuis nul ou supérieur à 180.');return out;}const ts=walls.map(()=>[0,1]);
 for(let i=0;i<walls.length;i++)for(let j=i+1;j<walls.length;j++){const a=walls[i],b=walls[j],r=sub(a.b,a.a),s=sub(b.b,b.a),q=sub(b.a,a.a),den=cross(r,s);if(Math.abs(den)>1e-9){const t=cross(q,s)/den,u=cross(q,r)/den;if(t>=-EPS/len(r)&&t<=1+EPS/len(r)&&u>=-EPS/len(s)&&u<=1+EPS/len(s)){ts[i].push(Math.max(0,Math.min(1,t)));ts[j].push(Math.max(0,Math.min(1,u)));}}else if(Math.abs(cross(q,r))/len(r)<EPS){const x=[b.a,b.b].map(p=>dot(sub(p,a.a),r)/dot(r,r));if((Math.min(1,Math.max(...x))-Math.max(0,Math.min(...x)))*len(r)>EPS){out.issues.push('Axes porteurs superposés : corriger les doublons.');return out;}}}
 if(ts.reduce((n,a)=>n+a.length-1,0)>2400){out.issues.push('Trop d’intersections pour le calcul interactif.');return out;}
 const nodes=[],edges=[],at=(e,t)=>add(e.a,{x:(e.b.x-e.a.x)*t,y:(e.b.y-e.a.y)*t});function node(p){let i=nodes.findIndex(n=>dist(n.p,p)<=EPS);if(i<0){i=nodes.length;nodes.push({p,edges:[]});}return i;}
 for(let i=0;i<walls.length;i++){const a=ts[i].sort((a,b)=>a-b).filter((t,k,a)=>!k||t-a[k-1]>1e-8);for(let k=0;k<a.length-1;k++){const x=node(at(walls[i],a[k])),y=node(at(walls[i],a[k+1]));if(x===y)continue;const id=edges.length;edges.push({a:x,b:y,wall:walls[i]});nodes[x].edges.push({to:y,id});nodes[y].edges.push({to:x,id});}}
 for(const n of nodes)n.edges.sort((a,b)=>Math.atan2(nodes[a.to].p.y-n.p.y,nodes[a.to].p.x-n.p.x)-Math.atan2(nodes[b.to].p.y-n.p.y,nodes[b.to].p.x-n.p.x));const seen=new Set();
 for(let start=0;start<nodes.length;start++)for(const first of nodes[start].edges){const key0=start+':'+first.id;if(seen.has(key0))continue;let curr=start,next=first,closed=false,ps=[],parts=[];
 for(let k=0;k<edges.length*2+2;k++){const key=curr+':'+next.id;if(seen.has(key)){closed=key===key0;break;}seen.add(key);ps.push(nodes[curr].p);parts.push(edges[next.id].wall);const to=next.to,arr=nodes[to].edges,i=arr.findIndex(e=>e.id===next.id);curr=to;next=arr[(i-1+arr.length)%arr.length];}
 if(!closed||ps.length<3||area(ps)<.04)continue;const corners=[];for(let i=0;i<ps.length;i++){const a=sub(ps[i],ps[(i+ps.length-1)%ps.length]),b=sub(ps[(i+1)%ps.length],ps[i]);if(Math.abs(cross(a,b))>1e-5*len(a)*len(b)||dot(a,b)<0)corners.push(i);}
 const points=corners.map(i=>ps[i]),vectors=points.map((p,i)=>sub(points[(i+1)%points.length],p)),rectangle=points.length===4&&vectors.every((v,i)=>len(v)>.2&&Math.abs(dot(v,vectors[(i+1)%4]))<1e-5*len(v)*len(vectors[(i+1)%4]));
 const sides=corners.map((a,i)=>{const end=corners[(i+1)%corners.length],members=[];let j=a;do{members.push(parts[j]);j=(j+1)%ps.length;}while(j!==end);return {a:points[i],b:points[(i+1)%points.length],members:[...new Map(members.map(w=>[w.id,w])).values()]};});out.faces.push({points,sides,rectangle,area:area(points)});}
 // Nested/disconnected contours are not a courtyard hole implementation.
 const inside=(p,ps)=>{let yes=false;for(let i=0,j=ps.length-1;i<ps.length;j=i++)if((ps[i].y>p.y)!==(ps[j].y>p.y)&&p.x<(ps[j].x-ps[i].x)*(p.y-ps[i].y)/(ps[j].y-ps[i].y)+ps[i].x)yes=!yes;return yes;};
 const reject=new Set();for(let i=0;i<out.faces.length;i++)for(let j=i+1;j<out.faces.length;j++){const a=out.faces[i].points,b=out.faces[j].points,cent=p=>({x:p.reduce((s,p)=>s+p.x,0)/p.length,y:p.reduce((s,p)=>s+p.y,0)/p.length});if(inside(cent(a),b)||inside(cent(b),a)){reject.add(i);reject.add(j);}}
 if(reject.size){out.faces=out.faces.filter((f,i)=>!reject.has(i));out.issues.push('Contours emboîtés exclus : les vides ne sont pas comblés automatiquement.');}
 if(!out.faces.length)out.issues.push('Aucune emprise fermée exploitable.');if(nodes.some(n=>n.edges.length===1))out.issues.push('Supports à extrémité libre : dessin potentiellement partiel.');return out;}
function foundationIds(m){const s=new Set(['foundations']);for(const l of m.levels)if(l.kind==='foundations'||/^fondations?$/i.test(l.name||''))s.add(l.id);const f=m.foundationAutomation;if(f?.targetLevelId&&f.targetLevelId!==f.sourceLevelId)s.add(f.targetLevelId);return s;}
function visible(m,show){const a=m.levels.find(l=>l.id===m.activeLevelId),ids=foundationIds(m);return a?m.levels.filter(l=>(l.id===a.id||l.elevation<a.elevation)&&(!ids.has(l.id)||show)).slice().sort((a,b)=>a.elevation-b.elevation):[];}
const api={EPS,sub,add,dot,cross,len,dist,area,wall,dragPlan,slide,faces,intersects,foundationIds,visible};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.PBPGeometry=api;
})(typeof window!=='undefined'?window:globalThis);
