/* Preserve free corner editing; slide wall bodies parallel to their neighbours. */
(function(){'use strict';const G=PBPGeometry,app=planApp,$=s=>document.querySelector(s);let drag=null,suppress=false;
const P=ProjectModel.prototype,oldSnap=P.snapshot,oldRestore=P.restore;
P.snapshot=function(){const d=JSON.parse(oldSnap.call(this));d.view3D={showFoundations:this.view3D?.showFoundations===true,showFloor:this.view3D?.showFloor!==false,showRoofCover:this.view3D?.showRoofCover!==false};return JSON.stringify(d);};
P.restore=function(text){oldRestore.call(this,text);const v=JSON.parse(text).view3D||{};this.view3D={showFoundations:v.showFoundations===true,showFloor:v.showFloor!==false,showRoofCover:v.showRoofCover!==false};};
ConstructionRenderer3D.prototype.draw=function(){if(!this.ctx||!this.width)return;const c=this.ctx;c.clearRect(0,0,this.width,this.height);c.fillStyle='#eef2f5';c.fillRect(0,0,this.width,this.height);this.drawGround();const m=this.app.model,show=m.view3D?.showFoundations===true,levels=G.visible(m,show);
 for(const l of levels)for(const e of m.elements){if(e.mode!=='construction'||e.levelId!==l.id||(!show&&(e.foundationRole||e.type==='foundation')))continue;if(e.a&&e.b&&['wallExterior','wallBearing','partition','foundation','beam'].includes(e.type))this.wall(e,l,1);else if(['column','slab','opening','stair'].includes(e.type))this.box(e,l,1);}
 const input=$('#gShowFoundations');if(input)input.checked=show;const floor=$('#gShowFloor');if(floor)floor.checked=m.view3D?.showFloor!==false;const text=$('#g3DLevels');if(text)text.textContent=levels.map(l=>l.name).join(' + ')||'Fondations masquées';};
const redraw=()=>{app.renderer2d?.draw();app.renderer3d?.draw();},screen=e=>{const r=$('#planCanvas').getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};};
const apply=rows=>{for(const p of rows){const e=app.model.elements.find(e=>e.id===p.id);if(e){e.a={...p.a};e.b={...p.b};}}};
function status(text='Angles conservés · raccords allongés/raccourcis'){const e=app.selectedElement;if(e?.a){const L=G.dist(e.a,e.b),input=$('#propertiesBody input[data-prop="length"]');if(input)input.value=L.toFixed(2);$('#statusMeasure').textContent='Longueur : '+L.toFixed(2)+' m';}$('#statusSelection').textContent=text;}
function finish(cancel=false){if(!drag)return;const d=drag;drag=null;app.parallelDrag=null;if(cancel&&d.model===app.model){apply(d.core.originals);if(d.moved){app.model.history=d.history;app.model.future=d.future;}}const cv=$('#planCanvas');cv.classList.remove('dragging-wall');suppress=true;app.suppressClick=true;setTimeout(()=>{suppress=false;app.suppressClick=false;},0);if(cv.hasPointerCapture(d.pointer))cv.releasePointerCapture(d.pointer);status(cancel?'Déplacement annulé':d.message);redraw();}
function move(e){if(!drag||drag.pointer!==e.pointerId)return;if(drag.model!==app.model){finish();return;}const p=screen(e);if(!drag.moved&&Math.hypot(p.x-drag.screen.x,p.y-drag.screen.y)<3)return;const world=app.renderer2d.screenToWorld(p),r=G.slide(drag.core,G.sub(world,drag.world));if(!r.ok){drag.message=r.message;status(r.message);return;}const changed=r.updates.some(p=>{const old=drag.core.originals.find(e=>e.id===p.id);return old&&(G.dist(old.a,p.a)>1e-8||G.dist(old.b,p.b)>1e-8);});if(!changed&&!drag.moved)return;if(!drag.moved){drag.history=app.model.history.slice();drag.future=app.model.future.slice();app.model.commit();drag.moved=true;}apply(r.updates);drag.message='Angles conservés · raccords allongés/raccourcis';status();redraw();}
function init(){const cv=$('#planCanvas');cv.addEventListener('pointerdown',e=>{if(app.activeTool!=='select'||e.button!==0||e.isPrimary===false)return;const p=screen(e);if(app.renderer2d.hitTestCorner(p,e.pointerType))return;const hit=app.renderer2d.hitTest(p);if(!G.wall(hit))return;e.stopImmediatePropagation();app.suppressClick=false;cv.dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:e.clientX,clientY:e.clientY}));app.selectedElement=hit;app.selectedPart=null;app.hoverCorner=null;drag={core:G.dragPlan(app.model.elements,hit),model:app.model,pointer:e.pointerId,screen:p,world:app.renderer2d.screenToWorld(p),moved:false};app.parallelDrag=drag;cv.setPointerCapture(e.pointerId);cv.classList.add('dragging-wall');status();redraw();},true);
 cv.addEventListener('pointermove',e=>{if(drag){e.stopImmediatePropagation();move(e);}},true);cv.addEventListener('pointerup',e=>{if(drag&&drag.pointer===e.pointerId){e.stopImmediatePropagation();move(e);if(drag){const same=drag.core.originals.every(p=>{const v=app.model.elements.find(e=>e.id===p.id);return v&&G.dist(v.a,p.a)<1e-8&&G.dist(v.b,p.b)<1e-8;});finish(drag.moved&&same);}}},true);
 cv.addEventListener('click',e=>{if(suppress){e.stopImmediatePropagation();e.preventDefault();}},true);for(const ev of ['pointercancel','lostpointercapture'])cv.addEventListener(ev,()=>finish(true),true);cv.addEventListener('wheel',e=>{if(drag){e.stopImmediatePropagation();e.preventDefault();}},{capture:true,passive:false});window.addEventListener('blur',()=>finish(true));window.addEventListener('keydown',e=>{if(drag&&(e.key==='Escape'||e.key==='Delete'||e.key==='Backspace'||e.ctrlKey||e.metaKey)){e.stopImmediatePropagation();e.preventDefault();finish(true);}},true);
 const div=document.createElement('div');div.style.cssText='position:absolute;right:8px;top:8px;z-index:5;background:#fffffff0;border:1px solid #ccd5dd;border-radius:6px;padding:7px 9px;max-width:72%;font-size:11px;display:grid;gap:5px';div.innerHTML='<label title="Affichage uniquement, pas une validation technique"><input id="gShowFoundations" type="checkbox"> Fondations</label><label title="Masque uniquement les couches de plancher. Les solives et rives restent visibles."><input id="gShowFloor" type="checkbox" checked> Plancher</label><small id="g3DLevels" style="display:block"></small>';$('#view3d').appendChild(div);$('#gShowFoundations').onchange=e=>{app.model.commit();app.model.view3D={...(app.model.view3D||{}),showFoundations:e.target.checked,showFloor:app.model.view3D?.showFloor!==false};redraw();};$('#gShowFloor').onchange=e=>{app.model.commit();app.model.view3D={...(app.model.view3D||{}),showFoundations:app.model.view3D?.showFoundations===true,showFloor:e.target.checked};redraw();};$('.hint').textContent='Corps du mur : angles conservés. Coin : déplacement libre. Échap annule le geste.';window.PBPGeometryReady=true;redraw();}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();})();
