/* v0.10.1 guided automatic joists; guarded navigation and recoverable calculation. Never silently confirms engineering assumptions. */
(function(){'use strict';const app=planApp,B=PBPBuilding,S=PBPStructure,G=PBPGeometry,$=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,n=2)=>Number.isFinite(v)?v.toFixed(n).replace('.',','):'—';
let step=0,config=null,report=null,base=null,levels=[],adjust=false,material='dry',modelAtOpen=null;
let busy=false,token=0,validation='',calcError='',lastAdvance=0;
const FIELD_LIMITS={q:[0,20],p:[0,50],finishes:[0,20],partitions:[0,20],panel:[0,100],screed:[0,250],spacing:[.15,1]};
const FIELD_NAMES={q:'Exploitation Q',p:'Charge ponctuelle',finishes:'Revêtements',partitions:'Cloisons',panel:'Panneau bois',screed:'Chape',spacing:'Entraxe cible maximal'};
function stories(m=app.model){const f=G.foundationIds(m);return m.levels.filter(l=>!l.autoFloor&&!f.has(l.id)&&l.id!=='roof'&&!/^toiture$/i.test(l.name||'')).sort((a,b)=>a.elevation-b.elevation);}
function oldZones(m,f){return S.settings(m.structureDesign).floors.filter(z=>z.enabled&&z.levelId===f.aboveId);}
function modelFor(f){const m={...app.model,levels:clone(app.model.levels),buildingDesign:B.settings(app.model.buildingDesign),structureDesign:S.settings(app.model.structureDesign)};m.structureDesign.floors=m.structureDesign.floors.map(z=>z.levelId===f.aboveId?{...z,enabled:false}:z);m.buildingDesign.floors=m.buildingDesign.floors.filter(z=>z.aboveId!==f.aboveId).concat([f]);return m;}
function chooseSource(id){const ls=stories(),below=ls.find(l=>l.id===id)||ls[0],above=ls[ls.indexOf(below)+1];config=null;if(!above)return;const existing=B.settings(app.model.buildingDesign).floors.find(f=>f.aboveId===above.id);config={...B.config(S,below,above),...(existing?clone(existing):{})};config.belowId=below.id;config.aboveId=above.id;config.system='wood';config.autoSection=true;config.enabled=true;config.grade='C24';config.assistant=true;material=Number(config.screed)>0?'screed':'dry';adjust=false;}
function open(){if(app.dragWall||app.parallelDrag){alert('Terminez le déplacement du mur avant d’ouvrir l’assistant.');return;}levels=stories();if(levels.length<2){alert('Ajoutez un étage au-dessus du RDC pour définir le plancher entre les deux niveaux.');return;}cancelPending();validation='';calcError='';report=null;lastAdvance=0;modelAtOpen=app.model;const current=levels.find(l=>l.id===app.model.activeLevelId),floor=app.model.levels.find(l=>l.id===app.model.activeLevelId);chooseSource(floor?.belowId||(current&&levels.indexOf(current)<levels.length-1?current.id:levels[Math.max(0,levels.indexOf(current)-1)]?.id));base=app.model.snapshot();step=0;render();$('#joistWizard').showModal();}
function row(label,id,value,type='number'){return '<label class="jw-row"><span>'+label+'</span><input id="'+id+'" type="'+type+'" '+(type==='checkbox'?(value?'checked':''):'value="'+esc(value)+'"')+(type==='number'?' step="any"':'')+'></label>';}
function read(){if(step!==0||!config)return;config.restraint=$('#jwRestraint').checked;config.loadsConfirmed=$('#jwLoads').checked;config.transfer=$('#jwTransfer').checked?'none':'unknown';for(const key of ['q','p','finishes','partitions','panel','screed','spacing']){const el=$('#jw_'+key);if(el)config[key]=el.value===''?null:Number(el.value);}config.service=Number($('#jwService').value);config.assistantMaxSpacing=config.spacing;}
function compute(){if(!config)return;const f={...config,autoSection:true,enabled:true,grade:'C24'},m=modelFor(f);let r=B.floorReport(m,f,G,S);let delta=0;
 if(adjust&&Number.isFinite(r.requiredTop)){const upper=m.levels.find(l=>l.id===f.aboveId);delta=Math.max(0,r.requiredTop-upper.elevation);if(delta>1e-7){const threshold=upper.elevation;for(const l of m.levels)if(!l.autoFloor&&l.elevation>=threshold-1e-8)l.elevation+=delta;r=B.floorReport(m,f,G,S);}}
 return{f,m,r,delta};}
function drawPreview(){const canvas=$('#jwPreview');if(!canvas||!config)return;const c=canvas.getContext('2d'),W=canvas.width,H=canvas.height;let detect;try{detect=G.faces(app.model,config.belowId,S);}catch(error){detect={faces:[],issues:['Aperçu indisponible : '+(error.message||'géométrie à vérifier')+'. Revenez au plan pour vérifier les appuis.']};}
 const compatible=detect.faces.filter(f=>f.rectangle).length,notes=[...detect.issues];
 if(detect.faces.length>compatible)notes.push('Une ou plusieurs travées ne sont pas rectangulaires : elles restent hors du calcul automatique.');
 const info=$('#jwDetection');if(info){info.replaceChildren();const title=document.createElement('p');title.textContent=compatible?compatible+' travée(s) rectangulaire(s) détectée(s).':'Aucune travée rectangulaire fermée détectée sur le niveau choisi.';info.appendChild(title);for(const text of notes){const line=document.createElement('p');line.className='jw-note';line.textContent=text;info.appendChild(line);}if(!compatible){const line=document.createElement('p');line.textContent='Vérifiez le niveau des appuis et fermez le contour avec des murs porteurs ou extérieurs. « Calculer le solivage » affiche aussi les éléments à compléter.';info.appendChild(line);}}
 const points=detect.faces.flatMap(f=>f.points);c.fillStyle='#f6f9fb';c.fillRect(0,0,W,H);if(!points.length){c.fillStyle='#74572b';c.font='14px system-ui';c.fillText('Contour porteur fermé manquant',20,35);return;}
 const xs=points.map(p=>p.x),ys=points.map(p=>p.y),loX=Math.min(...xs),loY=Math.min(...ys),scale=Math.min((W-50)/(Math.max(...xs)-loX||1),(H-40)/(Math.max(...ys)-loY||1)),xy=p=>({x:25+(p.x-loX)*scale,y:20+(p.y-loY)*scale});
 for(const face of detect.faces){c.strokeStyle=face.rectangle?'#536e7d':'#b17730';c.lineWidth=4;c.beginPath();face.points.map(xy).forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.stroke();if(!face.rectangle)continue;
 const choices=[0,1].map(i=>({i,span:G.dist(face.points[i],face.points[(i+3)%4])})).sort((a,b)=>a.span-b.span||a.i-b.i),i=choices[config.invert?1:0].i;const a=face.points[i],b=face.points[(i+1)%4],other=face.points[(i+3)%4];c.lineWidth=1.5;c.strokeStyle='#9b7746';for(let k=1;k<8;k++){const t=k/8,p=xy({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}),q=xy({x:other.x+(b.x-a.x)*t,y:other.y+(b.y-a.y)*t});c.beginPath();c.moveTo(p.x,p.y);c.lineTo(q.x,q.y);c.stroke();}const center=xy({x:face.points.reduce((s,p)=>s+p.x,0)/4,y:face.points.reduce((s,p)=>s+p.y,0)/4});c.fillStyle='#fff';c.fillRect(center.x-27,center.y-10,54,18);c.fillStyle='#294c61';c.font='12px system-ui';c.textAlign='center';c.fillText(fmt(choices[config.invert?1:0].span)+' m',center.x,center.y+3);c.textAlign='left';}}
function render(){const body=$('#jwBody');$('#jwStep').textContent=['1 · Niveau et matériaux','2 · Sens du solivage','3 · Calcul et éléments manquants'][step];$('#jwBack').hidden=step===0;$('#jwNext').hidden=step===2;$('#jwApply').hidden=step!==2;$('#jwProgress').textContent=(step+1)+' / 3';$('#jwNext').textContent=step===1?'Calculer le solivage':'Suivant';$('#jwApply').disabled=step!==2||busy||!report?.r?.complete||!!report?.r?.issues?.some(i=>i.severity==='error');$('#jwValidation').textContent=validation;$('#jwValidation').hidden=!validation;
 if(step===0){body.innerHTML='<label class="jw-row"><span>À partir du niveau (appuis)</span><select id="jwSource">'+levels.map(l=>'<option value="'+esc(l.id)+'"'+(l.id===config?.belowId?' selected':'')+'>'+esc(l.name)+'</option>').join('')+'</select></label>'+(!config?'<p class="jw-error">Aucun étage supérieur. Ajoutez d’abord un étage à ce niveau.</p>':'<p>Le plancher sera créé entre <b>'+esc(levels.find(l=>l.id===config.belowId)?.name)+'</b> et <b>'+esc(levels.find(l=>l.id===config.aboveId)?.name)+'</b>, comme niveau structurel indépendant.</p><label class="jw-row"><span>Matériau et composition</span><select id="jwMaterial"><option value="dry"'+(material==='dry'?' selected':'')+'>Bois massif C24 · plancher sec</option><option value="screed"'+(material==='screed'?' selected':'')+'>Bois massif C24 · avec chape</option></select></label><p class="jw-muted">Les appuis, travées, longueurs et sections d’essai sont calculés depuis le plan. Les hypothèses ci-dessous doivent correspondre au projet.</p>'+row('Maintien latéral des solives prévu','jwRestraint',config.restraint,'checkbox')+row('Charges du scénario ci-dessous vérifiées','jwLoads',config.loadsConfirmed,'checkbox')+row('Aucun mur ou poteau repris sur les solives','jwTransfer',config.transfer==='none','checkbox')+'<label class="jw-row"><span>Ambiance du bois</span><select id="jwService"><option value="1"'+(+config.service===1?' selected':'')+'>Intérieur sec · classe 1</option><option value="2"'+(+config.service===2?' selected':'')+'>Classe de service 2</option></select></label><details><summary>Charges, panneau et entraxe — hypothèses à vérifier</summary><p class="jw-muted">Valeurs de scénario, pas des prescriptions universelles. L’entraxe réel est réparti automatiquement sans dépasser la cible. La compatibilité du panneau relève de sa documentation fabricant.</p>'+[['Exploitation Q (kN/m²)','q'],['Charge ponctuelle (kN)','p'],['Revêtements (kN/m²)','finishes'],['Cloisons (kN/m²)','partitions'],['Panneau bois (mm)','panel'],['Chape (mm)','screed'],['Entraxe cible maximal (m)','spacing']].map(([l,k])=>row(l,'jw_'+k,config[k])).join('')+'</details>'+ (oldZones(app.model,config).length?'<p class="jw-note">À la génération, les anciennes zones manuelles de cet étage seront désactivées, sans être effacées, pour éviter les doublons.</p>':''));
 $('#jwSource').onchange=e=>{read();chooseSource(e.target.value);render();};if(config)$('#jwMaterial').onchange=e=>{read();material=e.target.value;config.screed=material==='dry'?0:(config.screed||50);render();};$('#jwNext').disabled=!config;
 }else if(step===1){body.innerHTML='<p>Choisissez le sens. Les murs porteurs et poutres existants déterminent automatiquement les travées ; aucune zone à tracer.</p><div class="jw-directions"><button type="button" id="jwShort" class="'+(!config.invert?'active':'')+'">Portées les plus courtes</button><button type="button" id="jwOther" class="'+(config.invert?'active':'')+'">Sens perpendiculaire</button></div><canvas id="jwPreview" width="510" height="260" aria-label="Aperçu du sens des solives"></canvas><div id="jwDetection" role="status"></div><p class="jw-muted">Cet aperçu montre le sens par travée, pas encore un nombre de solives validé. Une portée trop grande pourra nécessiter un appui supplémentaire à étudier.</p>';$('#jwShort').onclick=()=>{config.invert=false;render();};$('#jwOther').onclick=()=>{config.invert=true;render();};drawPreview();$('#jwNext').disabled=false;
 }else{
 if(busy){body.innerHTML='<p role="status" class="jw-result">Calcul en cours… Vous pouvez revenir à l’étape précédente ou annuler.</p>';return;}
 if(calcError||!report?.r){body.innerHTML='<p class="jw-error" role="alert">'+esc(calcError||'Le calcul doit être relancé.')+'</p><p>Votre plan n’a pas été modifié. Revenez au choix du sens pour réessayer ou vérifier les appuis.</p><button type="button" id="jwRetry">Relancer le calcul</button>';$('#jwRetry').onclick=queueResult;return;}
 const r=report.r,issues=[...new Set(r.issues.map(i=>i.text))],bays=r.bays||[],error=r.issues.some(i=>i.severity==='error');const canApply=r.complete&&!error;
 body.innerHTML='<div class="jw-result"><b>'+(canApply?'Tracé automatique disponible en préétude':'Éléments ou données à compléter')+'</b><br>Emprise : '+fmt(r.area)+' m² · '+bays.length+' travée(s).'+(r.section?'<br>Section commune d’essai : <b>'+r.section.b+' × '+r.section.h+' mm</b>':'')+'<br>'+r.count+' solives générées.'+(bays.length?'<br>Portées : '+bays.map(b=>fmt(b.geometry?.L)+' m').join(' / ')+'<br>Entraxes répartis : '+bays.map(b=>fmt(b.spacing*100,1)+' cm').join(' / '):'')+(Number.isFinite(r.required)?'<br>Épaisseur au-dessus des appuis : '+fmt(r.required*100,1)+' cm':'')+'</div>'+(Number.isFinite(r.requiredTop)?row('Ajuster l’altitude de l’étage et des niveaux au-dessus si nécessaire','jwAdjust',adjust,'checkbox'):'')+(report.delta>1e-7?'<p class="jw-note">À la génération : hausse de '+fmt(report.delta*100,1)+' cm des niveaux concernés. Cette modification sera annulable.</p>':'')+'<div class="jw-issues">'+issues.map(text=>'<p class="'+(r.issues.find(i=>i.text===text)?.severity==='error'?'jw-error':'jw-muted')+'">'+esc(text)+'</p>').join('')+'</div><p class="jw-muted">Sections comparées par le modèle limité existant. Aucun appui, chevêtre, assemblage ou ferraillage n’est inventé. Une préétude ne valide pas la construction.</p>';
 if($('#jwAdjust'))$('#jwAdjust').onchange=e=>{adjust=e.target.checked;queueResult();};$('#jwApply').disabled=!canApply;
 }}
// Navigation and calculation are separate: never advance on an implicit submit,
// leave a stale enabled Generate button, or strand the user after an exception.
function cancelPending(){token++;busy=false;}
function showValidation(text){validation=text;const box=$('#jwValidation');box.textContent=text;box.hidden=!text;box.scrollIntoView({block:'nearest'});}
function readValidated(){
 read();if(!config)return 'Choisissez un niveau avec un étage au-dessus.';
 for(const [key,[lo,hi]] of Object.entries(FIELD_LIMITS)){
  const value=config[key];if(value===null||value===''||!Number.isFinite(Number(value))||Number(value)<lo||Number(value)>hi){
   const input=$('#jw_'+key);input?.closest('details')?.setAttribute('open','');input?.focus();
   return FIELD_NAMES[key]+' : renseignez une valeur entre '+lo+' et '+hi+'. Les hypothèses structurelles ne sont pas confirmées automatiquement.';
  }
 }
 return '';
}
function advance(){
 if(busy||step<0||step>1)return;
 const now=performance.now();if(lastAdvance&&now-lastAdvance<350)return;
 try{
  if(step===0){const error=readValidated();if(error){showValidation(error);return;}validation='';step=1;lastAdvance=now;render();}
  else{validation='';lastAdvance=now;step=2;queueResult();}
 }catch(error){showValidation('Impossible de poursuivre : '+(error.message||'données à vérifier')+'. Votre plan n’a pas été modifié.');}
}
function back(){cancelPending();validation='';calcError='';report=null;step=Math.max(0,step-1);lastAdvance=0;render();}
function queueResult(){
 const ticket=++token;busy=true;calcError='';report=null;step=2;render();
 // Give the browser a frame to show progress and ignore repeated trackpad taps.
 setTimeout(()=>{
  if(ticket!==token||!$('#joistWizard').open)return;
  try{
   const result=compute();
   if(!result?.r||!Array.isArray(result.r.issues))throw Error('Résultat de calcul incomplet.');
   report=result;
  }catch(error){calcError='Le calcul n’a pas abouti : '+(error.message||'vérifiez les données du plan')+'.';report=null;}
  finally{if(ticket===token){busy=false;render();}}
 },40);
}
function apply(){
 if(step!==2||busy||!report?.r)return;
 if(app.model!==modelAtOpen||app.model.snapshot()!==base){showValidation('Le projet a changé depuis l’ouverture. Fermez puis rouvrez Solivage auto pour recalculer. Aucun plancher ajouté.');return;}
 try{report=compute();}catch(error){calcError='Le calcul n’a pas abouti : '+(error.message||'données à vérifier')+'.';report=null;render();return;}
 if(!report?.r?.complete||report.r.issues.some(i=>i.severity==='error')){render();return;}
 const model=app.model,before=model.snapshot(),history=[...model.history],future=[...model.future];
 try{
  model.commit();model.buildingDesign=report.m.buildingDesign;model.structureDesign=report.m.structureDesign;model.levels=report.m.levels;model.activeLevelId=report.f.id;
  PBPBuildingUI.refresh();$('#levelSelect').value=report.f.id;$('#levelSelect').dispatchEvent(new Event('change',{bubbles:true}));PBPBuildingUI.refresh();$('#joistWizard').close();
 }catch(error){
  model.restore(before);model.history=history;model.future=future;PBPBuildingUI.refresh();
  calcError='La génération a été annulée : '+(error.message||'erreur inattendue')+'. Le projet a été rétabli.';report=null;render();
 }
}
function init(){const style=document.createElement('style');style.textContent=`#stOpen,#stAdd,[data-st-tab="floors"],#bAddFloor,#bOpenFloors{display:none!important}#joistWizard{width:min(580px,94vw);max-height:90vh;overflow:auto}#jwForm{display:block;padding:16px}#jwForm h3{font-size:18px;margin:0 0 12px}.jw-row{display:grid!important;grid-template-columns:1fr minmax(100px,43%);gap:10px;align-items:center;font-size:12px;margin:12px 0}#jwForm input:not([type=checkbox]),#jwForm select{width:100%;min-width:0;padding:7px;border:1px solid #cad5df;border-radius:5px;background:white}#jwForm p{font-size:12px;line-height:1.5}.jw-muted{font-size:11px!important;color:#657782}.jw-error{color:#a63223;font-weight:600}.jw-note{background:#fff6df;padding:9px;color:#795725}.jw-result{padding:12px;background:#edf4f8;border:1px solid #d0e0e8;border-radius:8px;line-height:1.8;font-size:13px}.jw-directions{display:flex;gap:8px;margin-bottom:10px}.jw-directions button{flex:1;font-size:12px}#jwPreview{width:100%;height:auto;border:1px solid #d5e0e7;border-radius:8px}.jw-actions{position:sticky;bottom:-16px;display:flex;gap:6px;justify-content:flex-end;background:white;border-top:1px solid #dce4eb;padding:12px 16px;margin:12px -16px -16px}#jwApply,#jwNext{background:#245c7d;color:white}#jwForm button:disabled{opacity:.45;cursor:not-allowed}#jwStep{font-size:13px;color:#34596c;font-weight:700}#jwProgress{font-size:12px;color:#657782;float:right}#joistAutoBtn{width:100%;font-size:12px;margin:0 0 6px}#jwForm [hidden]{display:none!important}`;document.head.appendChild(style);
 const btn=document.createElement('button');btn.id='joistAutoBtn';btn.textContent='▤ Solivage auto';$('#faOpen').after(btn);btn.onclick=open;
 // Keep existing saved data and materials/technical controls; route floor entry
 // to the guided path rather than exposing a second creation command.
 $('[data-b-tab="floors"]').onclick=()=>{$('#bDialog').close();open();};$('#bOpenFloors').onclick=open;
 const foundationCard=$('.fa-card');$('.mode-title').after(foundationCard);const d=document.createElement('dialog');d.id='joistWizard';d.innerHTML='<form id="jwForm" novalidate><span id="jwProgress"></span><h3>Solivage automatique</h3><div id="jwStep"></div><p id="jwValidation" class="jw-error" role="alert" hidden></p><div id="jwBody"></div><div class="jw-actions"><button type="button" id="jwCancel">Annuler</button><button type="button" id="jwBack">Retour</button><button type="button" id="jwNext">Suivant</button><button type="submit" id="jwApply">Générer et suivre les murs</button></div></form>';document.body.appendChild(d);$('#jwCancel').onclick=()=>{cancelPending();d.close();};d.addEventListener('close',cancelPending);$('#jwBack').onclick=back;$('#jwNext').onclick=advance;$('#jwForm').onsubmit=e=>{e.preventDefault();if(step===2)apply();else advance();};$('#jwForm').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.repeat&&!e.isComposing&&e.target.matches('input[type=number]')){e.preventDefault();advance();}});$('.version').textContent='v0.10.1';document.title='Plan Bâtiment Pro — v0.10.1';window.PBPJoistWizardReady=true;}
window.PBPJoistWizard={open};if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();})();
