/* v0.10 wall/corner magnet; references never mutate the other floors. */
(function(){'use strict';const C=PBPPrecision,G=PBPGeometry,app=planApp,$=s=>document.querySelector(s);let result=null,alt=false,ready=false,optsKey='';
const defaults=()=>({enabled:true,crossLevels:true,reference:'below',pixels:9});
const P=ProjectModel.prototype,snapshot=P.snapshot,restore=P.restore;P.snapshot=function(){const d=JSON.parse(snapshot.call(this));d.magnet={...defaults(),...this.magnet};return JSON.stringify(d);};P.restore=function(t){restore.call(this,t);this.magnet={...defaults(),...JSON.parse(t).magnet};result=null;};
function settings(){return{...defaults(),...app.model.magnet};}
function referenceIds(){const m=app.model,s=settings(),a=m.levels.find(l=>l.id===m.activeLevelId);if(!s.enabled||!s.crossLevels||!a)return[];if(s.reference!=='below')return m.levels.some(l=>l.id===s.reference&&l.id!==a.id)?[s.reference]:[];const foundations=G.foundationIds(m);const candidates=m.levels.filter(l=>!l.autoFloor&&!foundations.has(l.id)&&l.id!==a.id&&l.elevation<a.elevation-1e-8).sort((a,b)=>b.elevation-a.elevation);return candidates.length?[candidates[0].id]:[];}
function sources(){const m=app.model,es=m.elements.filter(e=>!e.generator);for(const fn of [()=>PBPFoundationUI.getReport(),()=>PBPStructureUI.getReport(),()=>PBPBuildingUI.getReport()]){try{es.push(...(fn().elements||[]));}catch{}}const demo=new Set(m.foundationAutomation?.enabled&&m.foundationAutomation.hideDemo?PBPFoundations.demoIds(m.elements):[]);return [...new Map(es.filter(e=>!demo.has(e.id)).map(e=>[e.id,e])).values()];}
function guides(p,context={}){const s=settings(),d=context.drag||app.dragWall,exclude=[];let start=context.start||null;const es=sources();
 if(d?.kind==='corner'){const end=d.end,base=end==='a'?d.originalA:d.originalB;start=end==='a'?d.originalB:d.originalA;exclude.push(d.id+':'+end);for(const c of d.connected)exclude.push(c.id+':'+c.end);context.movingBase=base;}
 const refs=C.references(es,app.model.activeLevelId,referenceIds(),exclude),perpendicular=[];if(start){for(const e of es)if(e.levelId===app.model.activeLevelId&&e.a&&e.b&&(C.dist(e.a,start)<.004||C.dist(e.b,start)<.004)&&e.id!==d?.id)perpendicular.push(C.sub(e.b,e.a));}
 const out=C.snap(p,refs,{start,tolerance:Math.max(4,Math.min(16,s.pixels))/(50*app.renderer2d.scale),enabled:s.enabled&&!alt,perpendicular});result=out.label?out:null;return out.point;
}
window.PBPMagnet={snap:guides,referenceIds,getResult:()=>result};
// Existing drawing and corner handlers call this hook, injected into their source.
const oldOverlay=PlanRenderer2D.prototype.getOverlayLevelIds;PlanRenderer2D.prototype.getOverlayLevelIds=function(){return[...new Set(oldOverlay.call(this).concat(referenceIds()))].filter(id=>id!==app.model.activeLevelId);};
const oldSlide=G.slide;G.slide=function(g,delta){let r=oldSlide(g,delta);if(!r.ok||!settings().enabled||alt)return r;const e=r.updates.find(e=>e.id===g.selected.id);if(!e)return r;const exclude=g.originals.flatMap(e=>[e.id+':a',e.id+':b']),refs=C.references(sources(),app.model.activeLevelId,referenceIds(),exclude),tol=settings().pixels/(50*app.renderer2d.scale);result=null;
 for(const end of ['a','b']){const v=C.snap(e[end],refs,{tolerance:tol}),diff=C.sub(v.point,e[end]);if(!v.label)continue;const offset=g.refs.length?C.mul(g.n,C.dot(diff,g.n)):diff;const next=oldSlide(g,C.add(delta,offset)),wall=next.updates.find(e=>e.id===g.selected.id);if(next.ok&&wall&&C.dist(wall[end],v.point)<1e-6){result=v;r=next;break;}}
 return r;};
function updateUI(){if(!ready)return;const m=app.model,s=settings(),select=$('#magRef'),key=JSON.stringify([m.levels.map(l=>[l.id,l.name]),m.activeLevelId,s]);if(key===optsKey)return;optsKey=key;select.replaceChildren();for(const [v,text] of [['below','Niveau porteur inférieur'],...m.levels.filter(l=>l.id!==m.activeLevelId).map(l=>[l.id,l.name])]){const o=document.createElement('option');o.value=v;o.textContent=text;select.appendChild(o);}select.value=s.reference;if(!select.value)select.value='below';$('#magToggle').classList.toggle('active',s.enabled);$('#magToggle').textContent='Aimant murs '+(s.enabled?'✓':'—');$('#magCross').checked=s.crossLevels;const status=$('#statusSnap');if(status)status.textContent=s.enabled?'Aimant murs ✓':'Aimant désactivé';}
const draw=PlanRenderer2D.prototype.draw;PlanRenderer2D.prototype.draw=function(...args){const r=draw.apply(this,args);updateUI();if(!result||(!app.drawingStart&&!app.dragWall&&!app.parallelDrag&&app.activeTool==='select'))return r;const c=this.ctx;c.save();c.strokeStyle='#bf8021';c.fillStyle='#8a5415';c.lineWidth=1;c.setLineDash([5,4]);for(const g of result.guides){const a=this.worldToScreen(g.a),b=this.worldToScreen(g.b);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}c.setLineDash([]);const p=this.worldToScreen(result.point);c.beginPath();c.arc(p.x,p.y,5,0,Math.PI*2);c.stroke();const names=result.references.filter(id=>id!==app.model.activeLevelId).map(id=>app.model.levels.find(l=>l.id===id)?.name||id),text=result.label+(names.length?' · '+names.join(', '):'');c.font='11px system-ui';const w=Math.min(this.width-16,c.measureText(text).width+12),x=Math.min(Math.max(6,p.x+12),this.width-w-6),y=Math.min(Math.max(23,p.y-14),this.height-8);c.fillStyle='#fff9eafa';c.fillRect(x-3,y-13,w,19);c.fillStyle='#875519';c.fillText(text,x+2,y,Math.max(10,w-8));c.restore();return r;};
function refresh(){optsKey='';result=null;app.renderer2d.draw();}
function init(){const card=document.createElement('div');card.className='precision-card';card.innerHTML='<button id="magToggle" type="button">Aimant murs ✓</button><label><input type="checkbox" id="magCross" checked> Repères entre niveaux</label><select id="magRef" aria-label="Niveau de référence"></select><small>90°, axes et extrémités · Alt : libérer</small>';$('.tools-panel .tool-section').before(card);const style=document.createElement('style');style.textContent='.precision-card{padding:8px 0;border-top:1px solid #d9e1e7;font-size:11px}.precision-card button,.precision-card select{width:100%;margin-bottom:6px;font-size:11px}.precision-card label{display:flex;gap:5px;align-items:center;margin:4px 0}.precision-card small{display:block;color:#647781;line-height:1.4}';document.head.appendChild(style);$('#magToggle').onclick=()=>{app.model.magnet={...settings(),enabled:!settings().enabled};refresh();};$('#magCross').onchange=e=>{app.model.magnet={...settings(),crossLevels:e.target.checked};refresh();};$('#magRef').onchange=e=>{app.model.magnet={...settings(),reference:e.target.value};refresh();};const cv=$('#planCanvas');for(const name of ['pointermove','pointerdown'])cv.addEventListener(name,e=>{alt=e.altKey;},true);for(const name of ['pointerup','pointercancel','pointerleave'])cv.addEventListener(name,()=>{result=null;},true);window.addEventListener('keydown',e=>{alt=e.altKey;if(e.key==='Escape'){result=null;}});window.addEventListener('keyup',e=>{alt=e.altKey;});window.addEventListener('blur',()=>{alt=false;result=null;});ready=true;window.PBPPrecisionReady=true;refresh();}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();})();
