/* PBP v0.7 - scoped engineering pre-study UI; preserves the v0.5 gestures. */
(function(){
'use strict';
const S=window.PBPStructure,F=window.PBPFoundations,app=window.planApp;
if(!S||!F||!app)throw Error('Module structure indisponible.');
const $=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,n=2)=>Number.isFinite(v)?v.toFixed(n).replace('.',','):'—';
let ready=false,cacheKey='',cached=null,injecting=0,draft=null,draftFA=null,selected='',tab='floors',draftLevels=[],draftWalls={};
const proto=window.ProjectModel.prototype,oldSnapshot=proto.snapshot,oldRestore=proto.restore;
proto.snapshot=function(){const d=JSON.parse(oldSnapshot.call(this));d.structureDesign=S.settings(this.structureDesign);d.elements=d.elements.filter(e=>e.generator!==S.TAG);return JSON.stringify(d);};
proto.restore=function(text){oldRestore.call(this,text);this.structureDesign=S.settings(JSON.parse(text).structureDesign);this.elements=this.elements.filter(e=>e.generator!==S.TAG);cacheKey='';};
const foundationCompute=F.compute;
F.compute=function(model){const r=S.foundation(model);const result=foundationCompute({...model,foundationAutomation:r.effective});if(result.settings.enabled)result.issues.push(...r.issues);return result;};
function report(){const m=app.model,key=JSON.stringify([m.structureDesign,m.foundationAutomation,m.levels,m.elements.filter(e=>e.generator!==S.TAG)]);if(key!==cacheKey){cached=S.report(m);cacheKey=key;}return cached;}
function refresh(){cacheKey='';app.renderer2d?.draw();app.renderer3d?.draw();}
function badge(r){if(!ready)return;const count=r.floors.length,b=$('#stBadge');b.hidden=!count;
 if(count)b.textContent='Structure : '+count+' zone(s) de plancher · PRÉÉTUDE À VALIDER'+(r.floors.some(f=>f.issues.some(i=>i.severity==='error'))?' · alertes à corriger':'');
 $('#stState').textContent=count?count+' zone(s) liée(s) aux appuis':'Dalles, solives et hauteurs par niveau';
}
for(const R of [window.PlanRenderer2D,window.ConstructionRenderer3D]){
 const base=R.prototype.draw;R.prototype.draw=function(...args){if(injecting)return base.apply(this,args);const r=report(),m=this.app.model,original=m.elements;injecting++;
 try{m.elements=original.concat(r.elements);return base.apply(this,args);}finally{m.elements=original;injecting--;badge(r);}};
}
const oldLayer=window.PlanRenderer2D.prototype.drawLayer;
window.PlanRenderer2D.prototype.drawLayer=function(elements,alpha,overlay){
 const c=this.ctx,own=elements.filter(e=>e.generator===S.TAG);c.save();c.globalAlpha=alpha;
 for(const e of own.filter(e=>e.polygon)){c.beginPath();e.polygon.map(p=>this.worldToScreen(p)).forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fillStyle='#e5e9eb';c.fill();c.strokeStyle='#8e9a9e';c.stroke();}
 for(const e of own.filter(e=>e.floorRole==='joist')){const a=this.worldToScreen(e.a),b=this.worldToScreen(e.b);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.strokeStyle=overlay?'#8499a8':'#9a7852';c.lineWidth=Math.max(1,e.thickness*50*this.scale);c.stroke();}
 c.restore();return oldLayer.call(this,elements.filter(e=>e.generator!==S.TAG),alpha,overlay);
};
const oldWall=window.ConstructionRenderer3D.prototype.wall;
window.ConstructionRenderer3D.prototype.wall=function(el,level,alpha){return oldWall.call(this,el,el.generator===S.TAG?{...level,elevation:el.zBase}:level,alpha);};
const oldBox=window.ConstructionRenderer3D.prototype.box;
window.ConstructionRenderer3D.prototype.box=function(el,level,alpha){
 if(el.generator!==S.TAG||!el.polygon)return oldBox.call(this,el,level,alpha);
 const b=el.polygon.map(p=>this.project(p.x,p.y,el.zBase)),t=el.polygon.map(p=>this.project(p.x,p.y,el.zBase+el.height));
 for(let i=0;i<4;i++){const j=(i+1)%4;this.polygon([b[i],b[j],t[j],t[i]],'#bdc6ca','#63737b',alpha);}this.polygon(t,'#e2e7e9','#63737b',alpha);
};
function row(label,key,value,type='number',options=null,scope='floor'){
 const attr=`data-st-${scope}="${key}"`,control=type==='select'?`<select ${attr}>${options.map(([v,t])=>`<option value="${esc(v)}"${String(v)===String(value)?' selected':''}>${esc(t)}</option>`).join('')}</select>`:type==='checkbox'?`<input ${attr} type="checkbox"${value?' checked':''}>`:`<input ${attr} type="${type}" value="${esc(value)}"${type==='number'?' step="any"':''}>`;
 return `<label class="st-row${type==='checkbox'?' st-check':''}"><span>${esc(label)}</span>${control}</label>`;
}
const issueHTML=issues=>'<ul class="st-issues">'+issues.map(i=>`<li class="${i.severity==='error'?'st-error':''}">${esc(i.text)}</li>`).join('')+'</ul>';
function levelOptions(){return draftLevels.filter(l=>l.id!=='foundations'&&l.id!=='roof').map(l=>[l.id,l.name+' · '+fmt(l.elevation)+' m']);}
function draftModel(){return {...app.model,levels:draftLevels,elements:app.model.elements.map(e=>draftWalls[e.id]?{...e,...draftWalls[e.id]}:e),structureDesign:draft,foundationAutomation:draftFA};}
function current(){return draft.floors.find(f=>f.id===selected);}
function supports(f){return app.model.elements.filter(e=>S.isSupport(e)&&e.levelId===f.sourceLevelId).map((e,i)=>[e.id,`${i+1}. ${e.type==='beam'?'Poutre':e.type==='wallBearing'?'Porteur':'Extérieur'} · ${fmt(Math.hypot(e.b.x-e.a.x,e.b.y-e.a.y))} m · centre (${fmt((e.a.x+e.b.x)/2)} ; ${fmt((e.a.y+e.b.y)/2)})`]);}
function selectOptions(){const s=$('#stFloorList');s.innerHTML=draft.floors.length?draft.floors.map(f=>`<option value="${esc(f.id)}">${esc(f.name)} — ${esc(draftLevels.find(l=>l.id===f.levelId)?.name||'?')}</option>`).join(''):'<option>Aucune zone</option>';s.value=selected;}
function addFloor(){const levels=draftLevels.filter(l=>l.id!=='roof'&&l.id!=='foundations').sort((a,b)=>a.elevation-b.elevation),active=levels.find(l=>l.id===app.model.activeLevelId),target=active&&levels.indexOf(active)>0?active:(levels[1]||levels[0]);
 if(!target)return;const source=levels[Math.max(0,levels.indexOf(target)-1)],f={...S.floorDefaults(),id:'floor-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),name:'Plancher '+(draft.floors.length+1),levelId:target.id,sourceLevelId:source.id};
 if(target.id===source.id){f.system='ground';f.ceiling=0;f.ceilingThickness=0;}draft.floors.push(f);selected=f.id;selectOptions();renderFloor();}
function renderFloor(){const f=current(),box=$('#stFloorForm');if(!f){box.innerHTML='<p>Aucune zone. Cliquez sur « Ajouter une zone » puis choisissez ses deux appuis.</p>';$('#stResult').innerHTML='';return;}
 const opts=[['','Choisir un appui'],...supports(f)];
 box.innerHTML=
 row('Nom de cette zone','name',f.name,'text')+row('Afficher le dessin lié','enabled',f.enabled,'checkbox')+
 row('Niveau du plancher fini','levelId',f.levelId,'select',levelOptions())+row('Niveau des appuis / du contour','sourceLevelId',f.sourceLevelId,'select',levelOptions())+
 row('Composition','system',f.system,'select',[['wood','Bois : solives + panneau'],['concrete','Dalle béton portée'],['ground','Dallage béton sur le sol']])+
 '<p class="st-muted">Une zone rectangulaire entre deux appuis parallèles. La portée et le dessin suivent ces appuis. Définissez séparément les autres travées, sans recouvrement.</p>'+
 row('Premier appui A','supportA',f.supportA,'select',opts)+row('Deuxième appui B','supportB',f.supportB,'select',opts)+
 '<div class="st-inline"><button type="button" data-st-pick="supportA">Mur sélectionné → A</button><button type="button" data-st-pick="supportB">Mur sélectionné → B</button></div>'+
 (f.system==='wood'?'<details open><summary>Solives — section nette et espacement</summary>'+row('Entraxe maximal des axes (m)','spacing',f.spacing)+row('Largeur b (mm)','b',f.b)+row('Hauteur h (mm)','h',f.h)+row('Rechercher une section d’essai','autoSection',f.autoSection,'checkbox')+
 row('Classe de résistance du bois','grade',f.grade,'select',[['unknown','À justifier'],['C24','C24 — hypothèse du scénario']])+row('Classe de service','service',f.service,'select',[[1,'1 — intérieur sec'],[2,'2 — ambiance plus humide']])+row('Maintien latéral continu prévu','restraint',f.restraint,'checkbox')+
 row('Reprise sur les solives','transfer',f.transfer,'select',[['unknown','Cheminement à déterminer'],['none','Plancher seul, aucun porteur au-dessus'],['bearing','Mur / poteau / autre étage sur la travée']])+
 '<p class="st-muted">Comparateur habitation C24, deux appuis simples, pas de trémie. Sans ces hypothèses, la recherche et le dessin des solives sont suspendus. Les assemblages, l’appui réel et la stabilité ne sont pas vérifiés.</p></details>':
 '<details open><summary>Béton</summary>'+row('Épaisseur du béton (mm)','slabThickness',f.slabThickness??'')+(f.system==='ground'?row('Domaine maison individuelle confirmé','houseScope',f.houseScope,'checkbox')+'<button type="button" id="stSlabMin">Reporter le seuil conditionnel de 120 mm</button><p class="st-muted">Terre-plein seulement, dans le domaine NF DTU 13.3 P1-1-2. Ni une dalle portée ni une dalle sur vide sanitaire. Le seuil n’est pas un dimensionnement.</p>':'<p class="st-muted">Épaisseur issue d’une étude béton / fabricant. Aucun calcul de dalle portée ni de ferraillage automatique ; n’utilisez pas le seuil 120 mm du terre-plein.</p>')+'</details>')+
 '<details open><summary>Poids du plancher : léger ou alourdi</summary><div class="st-inline"><button type="button" data-st-preset="light">Exemple sans chape</button><button type="button" data-st-preset="heavy">Exemple avec chape</button></div><p class="st-muted">Exemples modifiables, pas des compositions prescrites. « Léger / lourd » décrit ici les matériaux ; la masse calculée prime.</p>'+
 (f.system==='wood'?row('Épaisseur panneau (mm)','panel',f.panel)+row('Masse volumique panneau (kg/m³)','panelDensity',f.panelDensity):'')+
 row('Épaisseur chape (mm)','screed',f.screed)+row('Masse volumique chape (kg/m³)','screedDensity',f.screedDensity)+row('Revêtements : poids (kN/m²)','finishes',f.finishes)+row('Plafond : poids (kN/m²)','ceiling',f.ceiling)+row('Isolation : poids (kN/m²)','insulation',f.insulation)+row('Cloisons non porteuses : charge (kN/m²)','partitions',f.partitions)+
 '<p class="st-muted">Saisissez la charge réelle des cloisons ; le forfait d’exemple n’est pas une reprise de mur porteur. Le panneau n’est pas dimensionné ici : tableaux fabricant et DTU 51.3 à vérifier.</p></details>'+
 '<details><summary>Usage, confort et épaisseur totale</summary>'+row('Exploitation habitation Q (kN/m²)','q',f.q)+row('Charge ponctuelle P (kN)','p',f.p)+row('Charges du scénario revues','loadsConfirmed',f.loadsConfirmed,'checkbox')+row('Objectif de flèche finale du projet','deflection',f.deflection,'select',[[300,'L / 300'],[400,'L / 400'],[500,'L / 500']])+row('Épaisseur revêtement (mm)','finishThickness',f.finishThickness)+row('Épaisseur plafond sous structure (mm)','ceilingThickness',f.ceilingThickness)+row('Objectif hauteur libre (m)','clearHeight',f.clearHeight)+row('Afficher aussi le panneau en plan','showDeck',f.showDeck,'checkbox')+
 '<p class="st-muted">Pas de minimum universel de hauteur libre ou de flèche revendiqué. Les critères de confort sont des filtres de préétude, pas un contrôle vibratoire complet. Altitudes du projet supposées au sol fini.</p>'+
 (f.system!=='ground'?'<button type="button" id="stCoordinate">Coordonner altitude et hauteur des 2 murs d’appui</button><p class="st-muted">Prépare seulement ces trois modifications ; application avec le bouton « Appliquer ». Aucun autre étage n’est déplacé. Ne convient pas à des poutres d’appui.</p>':'')+'</details>';
 box.querySelectorAll('[data-st-floor]').forEach(el=>{const change=()=>{f[el.dataset.stFloor]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;
  if(['sourceLevelId','system'].includes(el.dataset.stFloor)){if(el.dataset.stFloor==='sourceLevelId'){f.supportA='';f.supportB='';}renderFloor();}else preview();};el.addEventListener(el.tagName==='SELECT'||el.type==='checkbox'?'change':'input',change);});
 box.querySelectorAll('[data-st-pick]').forEach(b=>b.onclick=()=>{const e=app.selectedElement;if(!S.isSupport(e)||e.levelId!==f.sourceLevelId){$('#stResult').textContent='Sélectionnez d’abord un mur porteur au niveau des appuis, puis rouvrez ce panneau.';return;}f[b.dataset.stPick]=e.id;renderFloor();});
 box.querySelectorAll('[data-st-preset]').forEach(b=>b.onclick=()=>{f.screed=b.dataset.stPreset==='heavy'?60:0;f.screedDensity=2000;f.loadsConfirmed=false;renderFloor();});
 if($('#stSlabMin'))$('#stSlabMin').onclick=()=>{if(!f.houseScope||f.q>2.5){$('#stResult').textContent='Confirmez le domaine maison individuelle et les charges admissibles du domaine avant de reporter ce seuil.';return;}f.slabThickness=Math.max(120,Number(f.slabThickness)||0);renderFloor();};
 if($('#stCoordinate'))$('#stCoordinate').onclick=()=>{const r=S.floorReport(draftModel(),f);if(!r.geometry||!Number.isFinite(r.suggestedElevation)||r.check&&(!r.check.screened||r.hypothetical)||[r.geometry.a,r.geometry.b].some(w=>w.type==='beam')){$('#stResult').textContent='Coordination impossible avec les données actuelles : choisir deux murs, puis corriger les hypothèses et le calcul.';return;}
  draftLevels.find(l=>l.id===f.levelId).elevation=r.suggestedElevation;const fresh=S.floorReport(draftModel(),f),source=draftLevels.find(l=>l.id===f.sourceLevelId);for(const w of [r.geometry.a,r.geometry.b])draftWalls[w.id]={height:fresh.baseZ-source.elevation};preview();};
 preview();
}
function renderFoundation(){const f=draft.foundation,a=draftFA;
 $('#stFoundationForm').innerHTML='<p class="st-notice"><strong>Profondeur sous terrain ≠ épaisseur de semelle ≠ hauteur de longrine.</strong> Sans données de sol et de hors-gel, le minimum complet reste indéterminé.</p>'+
 row('Suivre les minima connus dans le dessin','autoDepth',f.autoDepth,'checkbox',null,'foundation')+row('Profondeur hors-gel prescrite (m)','frostDepth',f.frostDepth??'','number',null,'foundation')+row('Profondeur d’assise étude de sol (m)','studyDepth',f.studyDepth??'','number',null,'foundation')+row('Altitude terrain horizontal (m)','terrainZ',a.terrainZ??'','number',null,'fa')+
 row('Exposition argiles','rga',a.rga,'select',[['unknown','À déterminer à la parcelle'],['low','Faible / non classée'],['medium','Moyenne'],['high','Forte']],'fa')+row('Voie applicable aux argiles','rgaMethod',a.rgaMethod,'select',[['unknown','À déterminer'],['study','Prescriptions de l’étude'],['standard','Dispositions types de l’arrêté']],'fa')+
 '<p class="st-muted">Voie dispositions types : seuils 0,80 / 1,20 m pour exposition moyenne / forte, hors exception justifiée. Les autres mesures restent à contrôler, notamment le vide sanitaire sans sous-sol. Les sols en pente ne sont pas traités.</p>'+
 row('Semelles filantes : domaine DTU 13.1 confirmé','stripScope',f.stripScope,'checkbox',null,'foundation')+
 '<p class="st-muted">Pour les semelles filantes de ce domaine : contrôle de 20 cm de hauteur et 40 cm de largeur. Ce ne sont pas les dimensions calculées pour le bâtiment, ni des minima de longrine.</p>'+
 row('Épaisseur semelle prescrite par étude (m)','minFootingHeight',f.minFootingHeight??'','number',null,'foundation')+row('Hauteur longrine prescrite par étude (m)','minBeamHeight',f.minBeamHeight??'','number',null,'foundation')+
 '<p class="st-muted">L’automatisme ne réduit jamais une profondeur ou une section déjà plus grande. Vérifications de sol, tassement, béton et armatures non effectuées.</p><div id="stFoundationResult" role="status"></div>';
 $('#stFoundationForm').querySelectorAll('input,select').forEach(el=>el.addEventListener(el.tagName==='SELECT'||el.type==='checkbox'?'change':'input',()=>{const isfa=el.hasAttribute('data-st-fa'),obj=isfa?draftFA:draft.foundation,key=isfa?el.dataset.stFa:el.dataset.stFoundation;obj[key]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;preview();}));
}
function preview(){if(!draft)return;const m=draftModel(),r=S.report(m),f=current(),fr=f?r.floors.find(x=>x.floor.id===f.id):null;
 const fd=r.foundation;$('#stFoundationResult').innerHTML=`<div class="st-result"><strong>Maximum des seuils connus : ${fd.minimum===null?'indéterminé':fmt(fd.minimum)+' m'}</strong><br>Profondeur représentée : ${fmt(fd.depth)} m · sous-face : ${fmt(fd.proposedBase)} m.<br><small>Minimum partiel, pas conformité.</small></div>`+issueHTML(fd.issues);
 if(fr){let html='<div class="st-result"><strong>'+esc(fr.label||'Données à compléter')+'</strong>';
 if(fr.geometry)html+=`<br>Portée entre axes : <b>${fmt(fr.geometry.L)} m</b> · entre faces : ${fmt(fr.geometry.clear)} m.<br>Zone : ${fmt(fr.area)} m²${f.system==='wood'?` · ${fr.count} solives · entraxe réel ${fmt(fr.spacing*100,1)} cm`:''}.`;
 if(fr.check)html+=`<br><b>${fr.suggestion?'Section d’essai recalculée':'Section examinée'} : ${fr.check.b} × ${fr.check.h} mm</b>${fr.hypothetical?' — hypothèses non confirmées':''}.`;
 if(Number.isFinite(fr.massKg))html+=`<br>Poids permanent du scénario : ${fmt(fr.G)} kN/m² ≈ ${fmt(fr.massKg,0)} kg/m² (y compris charges forfaitaires saisies).<br>Épaisseur totale représentée : ${fmt(fr.totalThickness*100,1)} cm.`;
 if(f.system!=='ground'&&Number.isFinite(fr.clearHeight))html+=`<br>Hauteur libre : ${fmt(fr.clearHeight)} m · altitude pour l’objectif : ${fmt(fr.suggestedElevation)} m.`;
 html+='<br><strong>PRÉÉTUDE — NON VALIDÉE POUR CONSTRUIRE</strong></div>';
 if(fr.check){const c=fr.check;html+=`<details><summary>Valeurs du comparateur partiel</summary><p>Flèche instantanée variable : ${fmt(c.instant)} mm.<br>Flèche finale estimée : ${fmt(c.final)} mm.<br>Souplesse sous 1 kN : ${fmt(c.point1)} mm.<br>Fréquence 1D indicative : ${fmt(c.frequency)} Hz.<br>Réaction de calcul enveloppe / solive : ${fmt(c.reaction)} kN.<br>Rapport flexion : ${fmt(c.ratios.flexion)} · cisaillement : ${fmt(c.ratios.cisaillement)}.</p><p class="st-muted">Le passage de ces filtres ne valide ni le plancher ni ses appuis. Le contrôle vibratoire complet n’est pas implémenté. Méthode, coefficients et exclusions dans la note technique.</p></details>`;}
 $('#stResult').innerHTML=html+issueHTML(fr.issues);
 }
 $('#stSummary').innerHTML=`<p class="st-notice">${esc(r.globalNotice)}</p><p>Un ajout d’étage n’augmente pas mécaniquement toutes les sections. Les murs, poutres, poteaux et fondations doivent être revérifiés ; aucune descente de charges complète n’est calculée.</p>`+(r.missing.length?'<p class="st-error">Niveaux sans plancher défini : '+r.missing.map(l=>esc(l.name)).join(', ')+'.</p>':'')+
 r.floors.map(x=>`<div class="st-result"><b>${esc(x.floor.name)}</b> · ${esc(m.levels.find(l=>l.id===x.floor.levelId)?.name||'?')}<br>${esc(x.label||'À compléter')}<br>Zone : ${fmt(x.area)} m² · charges permanentes : ${fmt(x.permanentTotal)} kN · exploitation : ${fmt(x.variableTotal)} kN.${Number.isFinite(x.lineG)?`<br>Chaque ligne d’appui : G = ${fmt(x.lineG)} kN/m ; Q = ${fmt(x.lineQ)} kN/m (répartition simplifiée).`:''}<br><small>Charges de cette zone seule, sans murs, toiture ni cumul des étages. Aucun contrôle de superposition des zones : pas de total bâtiment.</small></div>`).join('');
}
function selectTab(t){tab=t;for(const el of document.querySelectorAll('[data-st-tab]'))el.classList.toggle('active',el.dataset.stTab===t);for(const el of document.querySelectorAll('[data-st-page]'))el.hidden=el.dataset.stPage!==t;}
function open(t='floors'){draft=S.settings(app.model.structureDesign);draftFA=F.settings(app.model.foundationAutomation);draftLevels=clone(app.model.levels);draftWalls={};selected=draft.floors.find(f=>f.levelId===app.model.activeLevelId)?.id||draft.floors[0]?.id||'';renderFoundation();selectOptions();renderFloor();selectTab(t);preview();$('#stDialog').showModal();}
function init(){
 const style=document.createElement('style');style.textContent=`
 .st-card{border-bottom:1px solid #e1e6eb;padding:8px 0}.st-card button{width:100%;font-size:12px;margin-bottom:5px}.st-card small{font-size:10px;color:#657582;line-height:1.35;display:block}#stDialog{width:min(560px,94vw);max-height:92vh;overflow:auto}#stForm{display:block;padding:15px}#stForm h3{font-size:17px;margin:0 0 10px}#stForm p{font-size:12px;line-height:1.45}#stForm details{margin:12px 0;padding-top:9px;border-top:1px solid #e1e5e9}#stForm summary{font-size:12px;font-weight:700;cursor:pointer;margin-bottom:9px}#stForm [hidden]{display:none!important}.st-row{display:grid!important;grid-template-columns:minmax(0,1fr) minmax(100px,44%);align-items:center;gap:10px;font-size:12px;margin:9px 0}#stForm input:not([type=checkbox]),#stForm select{width:100%;min-width:0;border:1px solid #ccd5dd;border-radius:5px;padding:6px;background:white;font-size:12px}.st-check input{justify-self:start}.st-tabs,.st-inline{display:flex;flex-wrap:wrap;gap:6px;margin:9px 0}.st-inline button,.st-tabs button{font-size:11px;padding:6px 8px}.st-tabs{position:sticky;top:-15px;background:white;padding:8px 0;z-index:2}.st-tabs .active{background:#e8f1f7;color:#214962;border-color:#9ebacb}.st-muted{font-size:11px!important;color:#657582;line-height:1.45}.st-notice{border-left:3px solid #b78735;background:#fff8e8;padding:9px;font-size:12px;color:#77551b}.st-result{background:#f0f4f6;border:1px solid #dee6eb;border-radius:6px;padding:9px;margin:9px 0;font-size:12px;line-height:1.6}.st-error{color:#a03421;font-weight:600}.st-issues{font-size:11px;line-height:1.5;padding-left:18px}.st-issues li{margin-bottom:7px}.st-actions{position:sticky;bottom:-15px;display:flex;justify-content:flex-end;gap:8px;background:white;border-top:1px solid #dce2e7;margin:12px -15px -15px;padding:12px 15px}.st-primary{background:#245c7d;color:white}#stBadge{position:absolute;bottom:38px;left:8px;z-index:4;max-width:calc(100% - 16px);background:#fff8e9;color:#77561b;border:1px solid #dec897;border-radius:5px;padding:5px 8px;font-size:10px;pointer-events:none}#stBadge[hidden]{display:none}
 `;document.head.appendChild(style);
 const card=document.createElement('div');card.className='st-card';card.innerHTML='<button id="stOpen">▤ Dalles & solivage</button><button id="stFoundationOpen">Minima des fondations</button><small id="stState"></small>';$('.fa-card').after(card);
 const b=document.createElement('div');b.id='stBadge';b.hidden=true;$('#canvasShell').appendChild(b);
 const dlg=document.createElement('dialog');dlg.id='stDialog';dlg.innerHTML=`<form id="stForm"><h3>Structure · minima & planchers</h3><div class="st-notice"><b>Avant-projet, pas plan d’exécution.</b> Les règles vérifiées sont partielles. Les sections d’essai et valeurs d’exemple exigent une étude géotechnique / structure adaptée au bâtiment.</div><div class="st-tabs"><button type="button" data-st-tab="foundation">Fondations</button><button type="button" data-st-tab="floors">Dalles & solives</button><button type="button" data-st-tab="summary">Étages & charges</button></div><section data-st-page="foundation"><div id="stFoundationForm"></div></section><section data-st-page="floors"><select id="stFloorList" aria-label="Zone de plancher"></select><div class="st-inline"><button type="button" id="stAdd">+ Ajouter une zone</button><button type="button" id="stRemove">Supprimer cette zone</button></div><div id="stFloorForm"></div><div id="stResult" role="status"></div></section><section data-st-page="summary"><div id="stSummary"></div></section><details><summary>Références et méthode — consultation du 23/09/2026</summary><p class="st-muted">Minima conditionnels et modèle simplifié, pas une implémentation intégrale des normes.</p><p><a href="docs/STRUCTURE.md" target="_blank" rel="noopener">Ouvrir la note technique et les limites</a></p><p><a href="${S.SOURCES.clay}" target="_blank" rel="noopener">Arrêté argiles du 22 juillet 2020</a><br><a href="${S.SOURCES.slab}" target="_blank" rel="noopener">NF DTU 13.3 — dallages de maisons individuelles</a><br><a href="${S.SOURCES.timber}" target="_blank" rel="noopener">Eurocode 5</a> · <a href="${S.SOURCES.annex}" target="_blank" rel="noopener">Annexe nationale française</a><br><a href="${S.SOURCES.guide}" target="_blank" rel="noopener">Guide FCBA / CODIFAB</a></p></details><div class="st-actions"><button type="button" id="stCancel">Annuler</button><button class="st-primary" type="submit">Appliquer au projet</button></div></form>`;document.body.appendChild(dlg);
 $('#stOpen').onclick=()=>open('floors');$('#stFoundationOpen').onclick=()=>open('foundation');$('#stCancel').onclick=()=>dlg.close();$('#stAdd').onclick=addFloor;
 $('#stFloorList').onchange=e=>{selected=e.target.value;renderFloor();};$('#stRemove').onclick=()=>{draft.floors=draft.floors.filter(f=>f.id!==selected);selected=draft.floors[0]?.id||'';selectOptions();renderFloor();};
 document.querySelectorAll('[data-st-tab]').forEach(b=>b.onclick=()=>selectTab(b.dataset.stTab));
 $('#stForm').onsubmit=e=>{e.preventDefault();app.model.commit();app.model.structureDesign=S.settings(draft);app.model.foundationAutomation=F.settings(draftFA);app.model.levels=clone(draftLevels);for(const el of app.model.elements)if(draftWalls[el.id])Object.assign(el,draftWalls[el.id]);
  const f=current();if(tab==='floors'&&f&&app.model.levels.some(l=>l.id===f.levelId))app.model.activeLevelId=f.levelId;
  const sel=$('#levelSelect');sel.replaceChildren();for(const l of app.model.levels){const o=document.createElement('option');o.value=l.id;o.textContent=l.name+' ('+fmt(l.elevation)+' m)';sel.appendChild(o);}sel.value=app.model.activeLevelId;sel.dispatchEvent(new Event('change',{bubbles:true}));dlg.close();refresh();};
 const notice=document.createElement('p');notice.className='fa-notice';notice.textContent='Les minima et profondeurs liés se règlent aussi dans « Minima des fondations ». S’ils sont activés, ils peuvent augmenter les valeurs de représentation ci-dessous.';$('#faEnabled').closest('label').before(notice);
 $('.version').textContent='v0.7';document.title='Plan Bâtiment Pro — v0.7';ready=true;window.PBPStructureReady=true;refresh();
}
window.PBPStructureUI={open,refresh,getReport:()=>clone(report())};
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();
