/* v0.14.1 — organize the existing controls, without replacing their handlers. */
(function(root){
'use strict';
const $=s=>document.querySelector(s),app=root.planApp;
function init(){
 const style=document.createElement('style');style.textContent=`#app{grid-template-rows:auto minmax(0,1fr) 30px}.topbar{min-height:54px;flex-wrap:wrap;padding:8px 10px;align-content:center;gap:7px}.top-actions{flex-wrap:wrap;overflow:visible;justify-content:flex-end;flex:1}.top-actions button,.top-actions select,.top-actions .file-button{font-size:11px;padding:6px 8px}.brand{font-size:13px}.tools-panel{flex:0 0 220px;width:220px;padding:10px;min-height:0;overflow:auto}.tools-panel .mode-title{font-size:11px;color:#486578;text-transform:uppercase;margin-bottom:5px;padding:3px}.work-category{border:1px solid #cddbe4;border-radius:8px;margin:8px 0;overflow:hidden;background:#f8fbfc}.work-category>summary{padding:10px 8px;font-size:12px;font-weight:700;color:#2f5569;cursor:pointer;background:#eef4f7;list-style:none}.work-category>summary:before{content:'▸ ';font-size:10px}.work-category[open]>summary:before{content:'▾ '}.work-content{padding:8px}.work-content>button{width:100%;text-align:left;margin:3px 0;padding:7px 6px;font-size:11px}.work-content>small{display:block;font-size:10px;color:#69808e;line-height:1.4;margin:4px 0 8px}.work-content .placement-settings{padding:7px;margin:8px 0 0}.work-content .setting-row{grid-template-columns:1fr 68px}.work-content .tool-section,.work-content .fa-card{border:0;margin:0;padding:0}#autoBadge{top:auto;bottom:35px;max-width:calc(100% - 20px)}#drawingToolbar{gap:5px;padding:6px 8px}#drawingToolbar .draw-title{display:none}.work-sourcebar{display:flex;align-items:center;gap:5px;margin:3px 0;font-size:11px}.work-sourcebar button{font-size:10px;padding:4px}@media(max-width:850px){.tools-panel{flex-basis:166px;width:166px}.topbar{padding:6px}.work-category>summary{font-size:11px}}@media(max-width:550px){.tools-panel{flex-basis:132px;width:132px;padding:5px}.work-content{padding:5px}.work-content>small{font-size:9px}.work-content .placement-settings{display:none}.top-actions{justify-content:flex-start}}`;
 document.head.append(style);
 const sidebar=$('.tools-panel'),title=$('.mode-title');title.textContent='Outils du projet';
 const definitions=[
 ['Projet & contexte','Définir le bâtiment, ses données et ses vérifications.',['#autoOpen']],
 ['Architecture','Tracer → régler les dimensions → placer les ouvertures.',['[data-tool="select"]','[data-tool="wallExterior"]','[data-tool="wallBearing"]','[data-tool="partition"]','[data-tool="column"]','[data-tool="beam"]','[data-tool="door"]','[data-tool="window"]','[data-tool="opening"]','[data-tool="stair"]','#placementSettings']],
 ['Fondations & planchers','Choisir les appuis puis les zones de solivage.',['#faOpen','#stFoundationOpen','#faShow','#joistAutoBtn','[data-tool="foundation"]','[data-tool="slab"]']],
 ['Toiture & charpente','Niveaux → zones → pans → sens → pente.',['#rfOpen']],
 ['Isolation & cloisons','Doublages intérieurs/extérieurs et parois sèches.',['#envOpen']],
 ['Pièces, cotes & métré','Nommer les pièces, mesurer et quantifier.',['#spaceNames','[data-tool="dimension"]','#bOpenMaterials']]
 ];
 const groups=[];definitions.forEach(([name,note,selectors],i)=>{const d=document.createElement('details');d.className='work-category';d.id='workCategory'+i;const sum=document.createElement('summary');sum.textContent=(i+1)+' · '+name;const content=document.createElement('div');content.className='work-content';const small=document.createElement('small');small.textContent=note;content.append(small);selectors.forEach(s=>{const el=$(s);if(el)content.append(el);});d.append(sum,content);d.open=i===1;sidebar.append(d);groups.push(d);d.addEventListener('toggle',()=>{if(d.open)groups.forEach(other=>{if(other!==d)other.open=false;});});});
 // Only empty scaffolds are removed. Moved controls retain listeners, IDs and state.
 sidebar.querySelectorAll(':scope>.tool-section,:scope>.auto-card,:scope>.env-card,:scope>.rf-card,:scope>.rz-card,:scope>.b-card,:scope>.fa-card,:scope>.st-card').forEach(c=>{c.hidden=true;});
 const hint=$('.hint');if(hint)sidebar.append(hint);
 const importLabel=$('#importInput')?.closest('label');if(importLabel){[...importLabel.childNodes].filter(n=>n.nodeType===3).forEach(n=>n.textContent='Ouvrir JSON');importLabel.title='Ouvrir un projet natif déjà enregistré';}
 const importBtn=$('#importPlanBtn');if(importBtn&&importLabel)importLabel.after(importBtn);if($('#rfOpen'))$('#rfOpen').textContent='⌂ Toiture & charpente auto';
 const base=$('#gShowFloor')?.closest('label');if(base){const label=document.createElement('label');label.title='Affichage de la couverture seulement : chevrons et rives conservés';label.innerHTML='<input id="gShowRoofCover" type="checkbox"> Couverture du toit';base.after(label);const input=$('#gShowRoofCover');input.checked=app.model.view3D?.showRoofCover!==false;input.onchange=()=>{app.model.commit();app.model.view3D={...app.model.view3D,showRoofCover:input.checked};app.renderer3d?.draw();};const old=root.ConstructionRenderer3D.prototype.draw;root.ConstructionRenderer3D.prototype.draw=function(...a){input.checked=this.app.model.view3D?.showRoofCover!==false;return old.apply(this,a);};}
 const source=document.createElement('button');source.type='button';source.id='togglePlanSource';source.textContent='Fond importé ✓';source.title='Afficher/masquer le document de référence, sans masquer les objets convertis';$('#drawViews')?.append(source);source.onclick=()=>{const current=(app.model.planSources||[]).filter(s=>s.levelId===app.model.activeLevelId),show=current.some(s=>s.hidden);current.forEach(s=>s.hidden=!show);source.textContent=show?'Fond importé ✓':'Fond importé —';app.renderer2d?.draw();};
 $('.version').textContent='v0.14.1';document.title='Plan Bâtiment Pro — v0.14.1';root.PBPWorkspaceReady=true;app.renderer2d?.resize();app.renderer3d?.resize();
}
if(document.readyState==='loading')root.addEventListener('DOMContentLoaded',init);else init();
})(window);
