const assert=require('node:assert/strict'),B=require('../building-core.js'),G=require('../geometry-tools.js'),S=require('../structure-core.js'),F=require('../foundations-core.js');
let n=0;const test=(s,f)=>{f();console.log('PASS',++n,s);},close=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function model(){const p=[[0,0],[8,0],[8,4],[0,4]];return{levels:[{id:'foundations',name:'Fondations',elevation:-.8,height:.8},{id:'ground',name:'RDC',elevation:0,height:2.8},{id:'r1',name:'R+1',elevation:3.2,height:2.8},{id:'r2',name:'R+2',elevation:6.4,height:2.8}],activeLevelId:'ground',elements:p.map((q,i)=>({id:'w'+i,type:'wallExterior',mode:'construction',levelId:'ground',a:{x:q[0],y:q[1]},b:{x:p[(i+1)%4][0],y:p[(i+1)%4][1]},thickness:.2,height:2.8})),buildingDesign:B.settings(),structureDesign:S.defaults()};}
function setup(){const m=model(),f={...B.config(S,m.levels[1],m.levels[2]),grade:'C24',restraint:true,loadsConfirmed:true,transfer:'none'};m.buildingDesign.floors=[f];return{m,f};}
test('Parallel slide preserves rectangle despite diagonal pointer',()=>{const m=model(),r=G.slide(G.dragPlan(m.elements,m.elements[1]),{x:2,y:1});assert(r.ok);const e=r.updates.find(e=>e.id==='w1');close(e.a.x,10);close(e.a.y,0);close(e.b.y,4);assert(!r.updates.some(e=>e.id==='w3'));});
test('Interior T junction stretches along same axis',()=>{const m=model();m.elements.push({id:'T',type:'wallBearing',mode:'construction',levelId:'ground',a:{x:4,y:0},b:{x:4,y:4},thickness:.2,height:2.8});const r=G.slide(G.dragPlan(m.elements,m.elements[0]),{x:1,y:-1});assert(r.ok);close(r.updates.find(e=>e.id==='T').a.x,4);close(r.updates.find(e=>e.id==='T').a.y,-1);});
test('Collapsed neighbours rejected',()=>{const m=model();assert(!G.slide(G.dragPlan(m.elements,m.elements[1]),{x:-10,y:0}).ok);});
test('All lower 3D levels; foundations opt-in only',()=>{const m=model();m.activeLevelId='r2';assert.deepEqual(G.visible(m,false).map(l=>l.id),['ground','r1','r2']);assert(G.visible(m,true).some(l=>l.id==='foundations'));});
test('Automatic joists and selectable full floor-level geometry',()=>{const {m,f}=setup(),r=B.floorReport(m,f,G,S);assert(r.complete);assert(r.count>0);assert(r.section);assert(r.level.autoFloor);close(r.area,32);assert(r.layers.some(l=>l.role==='panel'));assert(r.elements.every(e=>e.levelId===f.id));close(r.sourceTop,2.8);close(r.top,3.2);});
test('Shorter side selected, dividing bearing wall creates two bays',()=>{const {m,f}=setup();m.elements.push({id:'mid',type:'wallBearing',mode:'construction',levelId:'ground',a:{x:3,y:0},b:{x:3,y:4},thickness:.2,height:2.8});let r=B.floorReport(m,f,G,S);assert.equal(r.bays.length,2);assert.deepEqual(r.bays.map(b=>b.geometry.L),[3,4]);});
test('Non-bearing partition ignored',()=>{const {m,f}=setup();m.elements.push({id:'p',type:'partition',mode:'construction',levelId:'ground',a:{x:3,y:0},b:{x:3,y:4},thickness:.07,height:2.8});assert.equal(B.floorReport(m,f,G,S).bays.length,1);});
test('Missing confirmations never invent a section',()=>{for(const patch of [{grade:'unknown'},{restraint:false},{loadsConfirmed:false},{transfer:'unknown'}]){const {m,f}=setup();Object.assign(f,patch);assert.equal(B.floorReport(m,f,G,S).elements.length,0);}});
test('Insufficient vertical gap suspends solids, not compresses members',()=>{const {m,f}=setup();m.levels[2].elevation=2.9;const r=B.floorReport(m,f,G,S);assert(r.gap<0);assert.equal(r.elements.length,0);assert(r.section.h>100);});
test('Technical plenum affects envelope and headroom, not concrete volume',()=>{const {m,f}=setup();f.technical={location:'plenum',prescribed:200,clearance:20,reference:'scénario test',networks:[{enabled:true,kind:'ventilation',diameter:125,insulation:20}]};const r=B.floorReport(m,f,G,S);close(r.technical.required,200);close(r.bottom,2.8-.2-.013);close(r.clearHeight,2.8-.2-.013);assert(r.elements.some(e=>e.role==='technical'&&e.void));});
test('Drainage envelope uses actual prescribed slope and run',()=>{const r=B.techReport({location:'plenum',prescribed:0,clearance:20,reference:'test',networks:[{enabled:true,kind:'evacuation',diameter:100,insulation:0,slope:1,length:5}]});close(r.geometric,150);close(r.required,170);assert(r.complete);});
test('Unspecified prescriptions remain unknown, not zero-compliance',()=>{const r=B.techReport({networks:[{enabled:true,kind:'electricite',diameter:20}]});assert.equal(r.complete,false);assert(r.issues.length);close(r.geometric,20);});
test('Overlaid networks sum; side by side takes maximum',()=>{const t={networks:[{enabled:true,kind:'eau',diameter:20},{enabled:true,kind:'ventilation',diameter:125}],clearance:10,prescribed:0,reference:'test'};close(B.techReport(t).required,135);close(B.techReport({...t,stacked:true}).required,155);});
test('Gas, structure penetrations and incorporation in screed are never validated',()=>{for(const t of [{gas:true},{location:'structure'},{location:'chape'}]){const r=B.techReport({...t,networks:[{enabled:true,kind:'eau',diameter:20}],prescribed:30,clearance:10,reference:'test'});assert(!r.complete);assert(r.issues.some(i=>i.severity==='error'));}});
test('Ravoirage is separate from screed and influences the section study',()=>{const {m,f}=setup();f.technical={location:'ravoirage',networks:[{enabled:true,kind:'electricite',diameter:20}],prescribed:50,clearance:0,reference:'test'};let r=B.floorReport(m,f,G,S);close(r.layers.find(l=>l.role==='ravoirage').h,.05);});
test('Different story wall materials are kept separate',()=>{const m=model();m.buildingDesign.materials.ground={...B.material(),type:'concrete',core:200};m.elements.push({...structuredClone(m.elements[0]),id:'upper',levelId:'r1'});m.buildingDesign.materials.r1={...B.material(),type:'brick',rate:10,core:200};const r=B.report(m,G,S,F).quantities;const concrete=r.rows.find(r=>r.material==='béton'&&r.level==='RDC');close(concrete.quantity,24*2.8*.2);const brick=r.rows.find(r=>r.material==='briques');close(brick.quantity,8*2.8*10);});
test('Missing manufacturer unit rate not fabricated',()=>{const m=model();m.buildingDesign.materials.ground={...B.material(),type:'block'};const r=B.report(m,G,S,F).quantities;assert(!r.rows.some(r=>r.material==='parpaings'));assert(r.issues.some(s=>s.includes('unités/m²')));});
test('Timber studs and plates quantified, no full core as wood',()=>{const m=model();m.buildingDesign.materials.ground={...B.material(),type:'timber',core:145,studWidth:45,studSpacing:600,rails:2};const r=B.report(m,G,S,F).quantities;const wood=r.rows.find(r=>r.label==='Ossature courante brute');assert(wood.quantity>0&&wood.quantity<24*2.8*.145);});
test('Void/reserve is never quantified as concrete',()=>{const {m,f}=setup();f.system='concrete';f.slabThickness=200;m.levels[2].elevation=3.5;const r=B.report(m,G,S,F);const V=r.quantities.rows.find(r=>r.material==='béton'&&r.label==='Dalle béton'&&r.unit==='m³');close(V.quantity,32*.2);assert(!r.quantities.rows.some(r=>r.label==='Réserve'));});
test('Opening or overlapping legacy floor suspends new floor',()=>{const {m,f}=setup();m.elements.push({type:'opening',mode:'construction',levelId:'r1',x:2,y:2});assert.equal(B.floorReport(m,f,G,S).elements.length,0);m.elements.pop();m.structureDesign.floors=[{...S.floorDefaults(),levelId:'r1',enabled:true}];assert.equal(B.floorReport(m,f,G,S).elements.length,0);});
test('Wall deletion removes associated automatic floor solids',()=>{const {m,f}=setup();m.elements.pop();assert.equal(B.floorReport(m,f,G,S).elements.length,0);});
test('Duplicate automatic floor above same story is excluded',()=>{const {m,f}=setup();m.buildingDesign.floors.push({...f,id:'other'});const r=B.report(m,G,S,F);assert.equal(r.floors[1].elements.length,0);});
test('Report is pure and settings survive JSON round-trip',()=>{const {m}=setup(),before=JSON.stringify(m);B.report(m,G,S,F);assert.equal(JSON.stringify(m),before);assert.deepEqual(B.settings(B.settings(m.buildingDesign)),B.settings(m.buildingDesign));});
console.log(n+' building tests passed');
