'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const I=require('../plan-import-core.js'),G=require('../geometry-tools.js'),S=require('../structure-core.js'),Z=require('../spaces-core.js'),R=require('../roof-core.js'),C=require('../coverage-core.js'),H=require('../roof-forms.js');
function bitmap(W=500,H=350){const data=new Uint8ClampedArray(W*H*4).fill(255);return{width:W,height:H,data};}
function rect(im,x,y,w,h){for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++){const k=(yy*im.width+xx)*4;im.data[k]=im.data[k+1]=im.data[k+2]=0;}}
function solid(){const im=bitmap();rect(im,50,50,400,8);rect(im,50,290,400,8);rect(im,50,50,8,248);rect(im,442,50,8,248);rect(im,246,50,8,248);rect(im,50,320,400,1);return im;}
function model(){return{levels:[{id:'ground',name:'RDC',elevation:0,height:2.8},{id:'roof',name:'Toiture',elevation:2.8,height:2}],elements:[['a',[0,0],[8,0]],['b',[8,0],[8,6]],['c',[8,6],[0,6]],['d',[0,6],[0,0]]].map(([id,a,b])=>({id,type:'wallExterior',mode:'construction',levelId:'ground',a:{x:a[0],y:a[1]},b:{x:b[0],y:b[1]},height:2.8,thickness:.2}))};}
function group(pans,rotation){return{...R.defaults(),id:'test',name:'Toiture',enabled:true,supportLevelId:'ground',basis:'exterior',coverageZones:{mode:'all',ids:[]},pans,rotation,snowLoad:null,windPressure:null};}
test('known distance calibration and invalid scale rejection',()=>{assert.equal(I.scaleFrom({x:0,y:0},{x:500,y:0},10),.02);assert.throws(()=>I.scaleFrom({x:0,y:0},{x:0,y:0},10));assert.throws(()=>I.scaleFrom({x:0,y:0},{x:500,y:0},0));});
test('five filled walls detected, thin dimension line excluded',()=>{const r=I.recognize(solid(),{scale:.02,minLength:40});assert.equal(r.walls.length,5);assert.ok(r.walls.every(w=>w.type==='partition'&&w.thickness===8));assert.ok(r.walls.every(w=>w.a.y<310&&w.b.y<310));});
test('outlined walls recognized as paired faces',()=>{const im=bitmap();for(const [x,y,w,h] of [[50,50,400,1],[50,50,1,248],[449,50,1,248],[50,297,400,1],[58,58,384,1],[58,58,1,232],[441,58,1,232],[58,289,384,1]])rect(im,x,y,w,h);const r=I.recognize(im,{minLength:40});assert.equal(r.walls.length,4);assert.ok(r.walls.every(w=>w.method==='paired-outlines'));});
test('transparent pixels do not create black walls',()=>{const im=bitmap();im.data.fill(0);assert.equal(I.recognize(im).walls.length,0);});
test('bad image dimensions rejected',()=>{assert.throws(()=>I.recognize({width:10000,height:10000,data:[]}));});
test('native objects are editable and make two rooms',()=>{const r=I.recognize(solid()),es=I.toElements(r.walls,{scale:.02,levelId:'ground',height:2.8,idPrefix:'test'}),m=model();m.elements=es;assert.equal(es.length,5);assert.ok(es.every(e=>!e.generator&&!e.locked&&e.designStatus==='unverified-import'));assert.equal(Z.rooms(m,'ground',G).rows.length,2);const before=es[0].a.x;es[0].a.x-=1;assert.equal(es[0].a.x,before-1);});
test('classification remains user selected; no bearing inference',()=>{const r=I.recognize(solid());r.walls[0].type='wallBearing';const es=I.toElements(r.walls,{scale:.02,levelId:'ground'});assert.equal(es.filter(e=>e.type==='wallBearing').length,1);});
test('opening gaps are hypotheses, deselected by default',()=>{const w=[{id:'a',a:{x:0,y:0},b:{x:100,y:0},thickness:10},{id:'b',a:{x:145,y:0},b:{x:260,y:0},thickness:10}];const op=I.possibleOpenings(w,.02);assert.equal(op.length,1);assert.equal(op[0].accepted,false);assert.equal(I.toElements(op,{scale:.02,levelId:'ground'}).length,0);op[0].accepted=true;assert.ok(Math.abs(I.toElements(op,{scale:.02,levelId:'ground'})[0].width-.9)<1e-10);});
test('zero or negative input does not generate invalid elements',()=>{const r=I.recognize(solid());assert.throws(()=>I.toElements(r.walls,{scale:0,levelId:'ground'}));r.walls[0].thickness=-1;assert.throws(()=>I.toElements(r.walls,{scale:.02,levelId:'ground'}));});
test('repeat import deduplicates geometry only on the same level',()=>{const r=I.recognize(solid()),es=I.toElements(r.walls,{scale:.02,levelId:'ground'});assert.equal(I.deduplicate(es,es).length,0);assert.equal(I.deduplicate(es,es.map(e=>({...e,levelId:'r1'}))).length,5);});
function area(ps){return Math.abs(ps.reduce((s,p,i)=>s+p.x*ps[(i+1)%ps.length].y-ps[(i+1)%ps.length].x*p.y,0)/2);}
for(const pans of [1,2,4])test(pans+' roof planes cover one rectangle without overlap',()=>{const f=H.forms(8,6,35*Math.PI/180,pans,0);assert.equal(f.surfaces.length,pans);assert.ok(f.surfaces.every(s=>s.vertices.length>=3));assert.ok(Math.abs(f.surfaces.reduce((n,s)=>n+area(s.vertices),0)-48)<1e-8);assert.ok(f.surfaces.flatMap(s=>s.vertices).every(p=>Number.isFinite(p.z)));});
test('roof overhang preserves continuous facets',()=>{const f=H.forms(8,6,.5,4,.3);assert.ok(Math.abs(f.surfaces.reduce((n,s)=>n+area(s.vertices),0)-8.6*6.6)<1e-8);const heights=new Map();for(const s of f.surfaces)for(const p of s.vertices){const key=p.x.toFixed(5)+','+p.y.toFixed(5);if(heights.has(key))assert.ok(Math.abs(heights.get(key)-p.z)<1e-8);heights.set(key,p.z);}});
test('mono and hip groups are explicit geometry-only, not fake sizing results',()=>{for(const pans of [1,4]){const m=model(),r=C.roofGroupReport(m,group(pans,0),G,S,R);assert.equal(r.geometryComplete,true);assert.equal(r.complete,false);assert.equal(r.section,null);assert.equal(r.elements.filter(e=>e.type==='roofSurface').length,pans);assert.ok(r.elements.every(e=>e.designStatus==='geometry-only'||e.visualGuide));}});
test('180 degrees reverses the high side of a mono roof',()=>{const m=model(),a=C.roofGroupReport(m,group(1,0),G,S,R),b=C.roofGroupReport(m,group(1,180),G,S,R);const high=r=>r.elements.find(e=>e.type==='roofSurface').vertices.reduce((p,q)=>q.z>p.z?q:p);assert.ok(high(a).y>3);assert.ok(high(b).y<3);});
test('saved roof choices survive group serialization',()=>{const g=group(4,270),s=C.roofSettings({groups:[g]},R);assert.equal(s.groups[0].pans,4);assert.equal(s.groups[0].rotation,270);});
