'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const G=require('../geometry-tools.js'),S=require('../structure-core.js'),F=require('../foundations-core.js'),B=require('../building-core.js'),R=require('../roof-core.js'),Z=require('../spaces-core.js'),C=require('../coverage-core.js');
const copy=x=>JSON.parse(JSON.stringify(x));
function model(){const m={levels:[{id:'foundations',name:'Fondations',elevation:-.8,height:.8},{id:'ground',name:'RDC',elevation:0,height:2.8},{id:'r1',name:'R+1',elevation:3.5,height:2.8},{id:'roof',name:'Toiture',elevation:6.3,height:1.5}],elements:[],buildingDesign:{floors:[],materials:{}},spaceDesign:{names:{}}};
 const wall=(id,a,b,type='wallExterior',levelId='ground')=>m.elements.push({id,type,levelId,mode:'construction',a:{x:a[0],y:a[1]},b:{x:b[0],y:b[1]},height:2.8,thickness:.2});
 wall('a',[0,0],[6,0]);wall('b',[6,0],[6,4]);wall('c',[6,4],[0,4]);wall('d',[0,4],[0,0]);wall('e',[3,0],[3,4],'wallBearing');return m;}
function floor(m,sel){return{...B.config(S,m.levels[1],m.levels[2]),scenarioMode:'standard-prestudy',assistant:true,grade:'C24',rimAuto:false,coverageZones:sel};}
test('two named rooms and useful areas, not axis areas',()=>{const m=model(),r=Z.rooms(m,'ground',G);assert.equal(r.rows.length,2);assert.ok(r.rows.every(x=>/^Pièce [12]$/.test(x.name)));for(const row of r.rows){assert.ok(Math.abs(row.area-2.8*3.8)<1e-9);assert.equal(row.axisArea,12);}});
test('edited name survives movement of its boundary walls',()=>{const m=model(),left=Z.rooms(m,'ground',G).rows.find(r=>r.anchor.x<3);m.spaceDesign.names[left.id]='Séjour cathédrale';m.elements.find(w=>w.id==='e').a.x=4;m.elements.find(w=>w.id==='e').b.x=4;const r=Z.rooms(m,'ground',G).rows.find(r=>r.id===left.id);assert.equal(r.name,'Séjour cathédrale');assert.ok(Math.abs(r.area-3.8*3.8)<1e-9);});
test('rotated room area is rotation invariant',()=>{const m=model();for(const w of m.elements)for(const k of ['a','b']){const p=w[k],a=.47;w[k]={x:p.x*Math.cos(a)-p.y*Math.sin(a),y:p.x*Math.sin(a)+p.y*Math.cos(a)};}assert.ok(Z.rooms(m,'ground',G).rows.every(r=>Math.abs(r.area-10.64)<1e-8));});
test('partition is a room boundary but NOT a bearing-zone boundary',()=>{const m=model();m.elements.find(w=>w.id==='e').type='partition';assert.equal(Z.rooms(m,'ground',G).rows.length,2);assert.equal(Z.zones(m,'ground','structure',G,S).rows.length,1);});
test('partial floor: calculation, slabs and joists all stay in selected zone',()=>{const m=model(),rows=Z.zones(m,'ground','structure',G,S).rows,left=rows.find(r=>r.anchor.x<3),c=floor(m,{mode:'selected',ids:[left.id]}),r=B.floorReport(m,c,G,S);assert.equal(r.complete,true,JSON.stringify(r.issues));assert.equal(r.bays.length,1);assert.ok(r.count>0);assert.equal(r.zoneCoverage.selectedArea,12);assert.equal(r.zoneCoverage.excludedArea,12);for(const e of r.elements){for(const p of e.polygon||[e.a,e.b].filter(Boolean))assert.ok(p.x<=3.0001,'geometry escaped selected zone');}m.buildingDesign.floors=[c];assert.equal(B.report(m,G,S,F).elements.length,r.elements.length);});
test('empty selection really means no joists, panels or horizontal ceiling',()=>{const m=model(),r=B.floorReport(m,floor(m,{mode:'selected',ids:[]}),G,S);assert.equal(r.complete,true);assert.equal(r.empty,true);assert.equal(r.elements.length,0);assert.equal(r.count,0);assert.equal(r.zoneCoverage.excludedArea,24);});
test('lost boundary identity blocks instead of silently covering a different room',()=>{const m=model(),id=Z.zones(m,'ground','structure',G,S).rows[0].id;m.elements=m.elements.filter(w=>w.id!=='e');const r=B.floorReport(m,floor(m,{mode:'selected',ids:[id]}),G,S);assert.equal(r.complete,false);assert.equal(r.elements.length,0);assert.equal(r.zoneCoverage.missing.length,1);});
test('selection metadata survives JSON roundtrip',()=>{const m=model(),id=Z.zones(m,'ground','structure',G,S).rows[0].id;m.buildingDesign.floors=[floor(m,{mode:'selected',ids:[id]})];m.spaceDesign.names[id]='Bureau';const restored=copy(m);assert.equal(B.report(restored,G,S,F).floors[0].zoneCoverage.selectedArea,12);assert.ok(Z.rooms(restored,'ground',G).rows.some(r=>r.name==='Bureau'));});
function twoRoofs(){const m=model();for(const w of copy(m.elements.filter(e=>e.id!=='e'))){w.id='upper-'+w.id;w.levelId='r1';w.a.x+=10;w.b.x+=10;m.elements.push(w);}const lo=Z.zones(m,'ground','structure',G,S).rows.find(r=>r.anchor.x<3),hi=Z.zones(m,'r1','structure',G,S).rows[0];m.roofDesign={groups:[{...R.defaults(),id:'low',name:'Séjour',enabled:true,supportLevelId:'ground',basis:'structure',coverageZones:{mode:'selected',ids:[lo.id]},snowLoad:.7,windPressure:.5,slopeDeg:35},{...R.defaults(),id:'high',name:'Étage',enabled:true,supportLevelId:'r1',basis:'structure',coverageZones:{mode:'selected',ids:[hi.id]},snowLoad:.7,windPressure:.5,slopeDeg:25}]};return m;}
test('two roof groups keep their independent supporting levels and heights',()=>{const m=twoRoofs(),r=R.report(m,G,S);assert.equal(r.groups.length,2);assert.ok(r.groups.every(g=>g.geometryComplete));assert.equal(r.groups[0].geometry.zones[0].eaveZ,2.8);assert.equal(r.groups[1].geometry.zones[0].eaveZ,6.3);assert.ok(r.elements.some(e=>e.roofGroupId==='low'));assert.ok(r.elements.some(e=>e.roofGroupId==='high'));assert.equal(new Set(r.elements.map(e=>e.id)).size,r.elements.length);});
test('missing snow is not treated as zero load',()=>{const m=twoRoofs();m.roofDesign.groups[0].snowLoad=null;const r=R.report(m,G,S).groups[0];assert.equal(r.section,null);assert.equal(r.complete,false);assert.equal(r.geometryComplete,true);assert.ok(r.elements.every(e=>e.designStatus==='geometry-only'||e.visualGuide));});
test('roof support is never silently moved to a different storey',()=>{const m=twoRoofs();m.roofDesign.groups[0].supportLevelId='missing';const r=R.report(m,G,S).groups[0];assert.equal(r.elements.length,0);assert.ok(r.issues.some(e=>e.severity==='error'));});
test('overhang preserves pitch at the real support line',()=>{const m=twoRoofs(),r=R.report(m,G,S).groups[0],z=r.geometry.zones[0],e=r.elements.find(e=>e.role==='rafters'),pitch=r.settings.slopeDeg*Math.PI/180;assert.ok(Math.abs(e.a.z-(z.eaveZ-r.settings.overhang*Math.tan(pitch)))<1e-9);assert.ok(Math.abs((e.b.z-e.a.z)/Math.hypot(e.b.x-e.a.x,e.b.y-e.a.y)-Math.tan(pitch))<1e-9);});
test('adjacent selected rectangles merge only when their union is rectangular',()=>{const m=model(),rows=Z.zones(m,'ground','structure',G,S).rows,merged=C.rectangleUnion(rows);assert.equal(merged.length,1);assert.equal(merged[0].area,24);assert.ok(merged[0].sides.every(s=>s.members.length));});
test('duplicate roof coverage on the same level is identified',()=>{const m=twoRoofs();m.roofDesign.groups[1]={...m.roofDesign.groups[0],id:'duplicate',name:'Doublon'};const r=R.report(m,G,S);assert.equal(r.complete,false);assert.ok(r.issues.some(i=>i.text.startsWith('Deux toitures')));});

test('load-bearing element above an omitted zone remains blocking',()=>{const m=model(),rows=Z.zones(m,'ground','structure',G,S).rows,left=rows.find(r=>r.anchor.x<3);m.elements.push({id:'unsupported-upper',type:'wallBearing',mode:'construction',levelId:'r1',a:{x:4,y:1},b:{x:5,y:1},height:2.8,thickness:.2});const r=B.floorReport(m,floor(m,{mode:'selected',ids:[left.id]}),G,S);assert.equal(r.complete,false);assert.ok(r.issues.some(i=>i.code==='load-above-void'));});
